### ISSUE TITLE
bug(YouTube/Hide layout components): `Hide YouTube settings menu` setting does not hide some settings

### ISSUE THREAD

**Issue by Aryan-Chauhan** [inotia00/ReVanced_Extended#1964] opened 2024-05-09 12:14 UTC
### Type

Cosmetic

### Tools used

Revancify

### Application

YT v19.16.39

Patches v4.8.0-dev.1

Integrations v1.8.2

### Bug description

In "Hide YouTube Settings Menu", all options are working except the following:

1. Background and downloads
2. ReVanced Extended
3. About

So, please fix them if you get time.

Thanks!
![Screenshot_2024-05-09-21-47-15-66_a9acfd2263b6b7a65bf2540b0d9449ca.jpg](https://github.com/inotia00/ReVanced_Extended/assets/91815107/e856bdc4-180d-4141-b453-2b9cf73193aa)
![Screenshot_2024-05-09-21-47-43-33_a9acfd2263b6b7a65bf2540b0d9449ca.jpg](https://github.com/inotia00/ReVanced_Extended/assets/91815107/9a075e0d-d12c-47b5-bc26-43babb15221c)

### Error logs

```shell
No logs.
```

### Solution

Ability to hide the 3 options mentioned above.

### Additional context

The above-mentioned options can be hidden in anddea's RVX using a patch called as "Tuck Away Preferences". But in that patch, "Account" & "Your data in YouTube" cannot be hidden, but in your RVX, these two can be hidden.

### Device Environment

Realme 7 Pro running on Android 12 (skin name is Realme UI 3.0).

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by GucekPL** [comment] 2024-05-09 15:14
In Polish, hiding don't work only for "Your data in YouTube" and "About"

**Comment by Aryan-Chauhan** [comment] 2024-05-10 00:02
> fixed in [revanced-patches-4.8.0-dev.2](https://github.com/inotia00/revanced-patches/releases/tag/v4.8.0-dev.2)

Thank you, now "About" can be hidden.

But still "Background and downloads" and "ReVanced Extended" cannot be hidden.
![Screenshot_2024-05-10-05-28-49-10_a9acfd2263b6b7a65bf2540b0d9449ca.jpg](https://github.com/inotia00/ReVanced_Extended/assets/91815107/24fd3daf-6d33-4609-b191-32a1d080538d)
![Screenshot_2024-05-10-05-27-53-68_a9acfd2263b6b7a65bf2540b0d9449ca.jpg](https://github.com/inotia00/ReVanced_Extended/assets/91815107/91b6938e-0f51-405a-9f92-c49837e4198a)
![Screenshot_2024-05-10-05-30-13-87_a9acfd2263b6b7a65bf2540b0d9449ca.jpg](https://github.com/inotia00/ReVanced_Extended/assets/91815107/d5bf3f25-5667-4c56-a7fc-48c6704cca86)

**Comment by inotia00** [comment] 2024-05-10 00:36
On my device, it appears as the `Background & downloads` setting instead of the `Background and downloads` setting.
Therefore, I tried hiding it with the `Background & downloads` keyword, and it was hidden well as intended.

 `ReVanced Extended` setting is hardcoded to not be hidden, so it is normal for it to not be hidden.

**Comment by inotia00** [comment] 2024-05-10 00:58
If it is A/B tests, there is no way for me to test it until it is applied to my account.

Instead, it seems possible to add an option to hide all settings except for specific keywords.
(Whitelist method - e.g. hiding all settings except `General` settings)

**Comment by Aryan-Chauhan** [comment] 2024-05-10 01:07
> If it is A/B tests, there is no way for me to test it until it is applied to my account.
> 
> Instead, it seems possible to add an option to hide all settings except for specific keywords.
> (Whitelist method - e.g. hiding all settings except `General` settings)

That sounds better.

**Comment by inotia00** [comment] 2024-05-10 17:17
reflected in [revanced-patches-4.8.0-dev.4](https://github.com/inotia00/revanced-patches/releases/tag/v4.8.0-dev.4)

**Comment by inotia00** [comment] 2024-05-11 02:19
![0511111819250351](https://github.com/inotia00/ReVanced_Extended/assets/108592928/e378646d-2398-4d81-b1c2-769b68988f71)

I was able to fix this bug, but I found a big drawback with the whitelist method.
The whitelist method hides even the settings in the submenu of YouTube settings.

To use the whitelist method without issues, you should add the names of all upper menu settings and the names of all submenu settings.
It also makes the integrations code overly complex.

For this reason I'll just drop the whitelist method.

**Comment by Alxon4789** [comment] 2024-05-17 19:37
> ![0511111819250351](https://private-user-images.githubusercontent.com/108592928/329747105-e378646d-2398-4d81-b1c2-769b68988f71.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5NzQxMzksIm5iZiI6MTcxNTk3MzgzOSwicGF0aCI6Ii8xMDg1OTI5MjgvMzI5NzQ3MTA1LWUzNzg2NDZkLTIzOTgtNGQ4MS1iMWMyLTc2OWI2ODk4OGY3MS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxN1QxOTIzNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MTQ0MjEzMTRhNjMwNjQ1OTNmNGQ0NzdhYWY0YmEyNmJkMjgwYzVhMGMyMzVlZjE1NWFlOTI0NmNkYjk0MTFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iNQH8kPnck0cGSPOFzLEEAyPjMeQ_Vlp_KLQC4oXl6w)
> 
> I was able to fix this bug, but I found a big drawback with the whitelist method. The whitelist method hides even the settings in the submenu of YouTube settings.
> 
> To use the whitelist method without issues, you should add the names of all upper menu settings and the names of all submenu settings. It also makes the integrations code overly complex.
> 
> For this reason I'll just drop the whitelist method.

Using patches 4.8.0-dev.6, it is still impossible to remove "Your data in Youtube" (at least using the Polish language). I tried various combinations: "data", "your" "data in YouTube", none of them worked. As proof, I am sending screenshots and patchlog

<img src="https://github.com/inotia00/ReVanced_Extended/assets/143010511/1c3e80a5-e0d6-41de-b0ff-058527385dd0" width=30% height=30%><img src="https://github.com/inotia00/ReVanced_Extended/assets/143010511/2e372868-d17d-4305-80ef-257bce426db7" width=30% height=30%>

[patch_log.txt](https://github.com/inotia00/ReVanced_Extended/files/15357651/patch_log.txt)

**Comment by Aryan-Chauhan** [comment] 2024-06-27 15:48
I'm using latest dev patches on YT v19.23.40 and able to hide all stock settings.

![Screenshot_2024-06-27-21-15-15-50_a9acfd2263b6b7a65bf2540b0d9449ca.jpg](https://github.com/inotia00/ReVanced_Extended/assets/91815107/0dd9686b-d310-4107-8df8-7ac01600e1b6)

**Comment by inotia00** [comment] 2024-06-27 16:12
Thanks for reporting back
I can now close the issue

**Comment by hlytus** [comment] 2024-06-28 16:22
It doesn't hide on my end. Am on the latest version as well. 
I think it's region related, set your VPN to India or Germany, then you'll see Background and downloads.

**Comment by Aryan-Chauhan** [comment] 2024-06-29 00:23
I am in India and always has been.

On.
![Screenshot_2024-06-29-05-52-42-18_a9acfd2263b6b7a65bf2540b0d9449ca.jpg](https://github.com/inotia00/ReVanced_Extended/assets/91815107/07f576e7-11f0-48af-8b36-d196dd28fcee)

Off.
![Screenshot_2024-06-29-05-53-10-00.jpg](https://github.com/inotia00/ReVanced_Extended/assets/91815107/cc579fda-762f-4182-89cf-997c2f67fc4a)

**Comment by inotia00** [comment] 2024-06-29 00:56
It may be different depending on the region, or it may be A/B tests

**Comment by inotia00** [comment] 2024-07-27 08:59
merge into the issue https://github.com/inotia00/ReVanced_Extended/issues/2043

**Closed by inotia00** 2024-07-27 08:59 UTC
Labels: Bug report
