### ISSUE TITLE
bug(YouTube): opening YouTube links not displaying correctly when user logs out

### ISSUE THREAD

**Issue by ANewDawn** [inotia00/ReVanced_Extended#1510] opened 2023-10-10 12:57 UTC
### Type

Cosmetic

### Tools used

Revancify

### Application

YouTube 18.33.40

### Bug description

This bug also exists in official ReVanced, and it has not yet been identified which patch is causing the bug.

### Steps to reproduce

Step 1. Include only the default patches.
Step 2. Not signing in to your Google account
Step 3. Close RVX completely and open YouTube in an external browser.

### Relevant log output

```shell
No sure how get log output. Will provide if needed.
```

### Screenshots or videos

![Screenshot_2023-10-10-13-25-35-388_app rvx2 android youtube-edit](https://github.com/inotia00/ReVanced_Extended/assets/51456745/5797b4b4-cd53-47a2-9ced-9d00e3917e9f)

### Solution

Just sign in to your Google account

### Device Environment

Xiaomi Poco M4 pro
Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by Hennadz** [comment] 2023-10-10 20:58
Just log into your YouTube account.

**Comment by ANewDawn** [comment] 2023-10-10 21:04
> Just log into your YouTube account.

I use revanced without an account. Is the problem solved when logged in?

**Comment by Hennadz** [comment] 2023-10-10 21:34
@ANewDawn 
You spent more time writing a question and waiting for an answer than it would have taken to check my advice. 


> Is the problem solved when logged in?

Exactly

**Comment by ANewDawn** [comment] 2023-10-10 21:40
Ok. Thanks for testing. I don't sign in on revanced so not sure if there I workaround fix without signing in but least it narrows down the issue.

**Comment by inotia00** [comment] 2023-10-12 15:26
Since the same issue is reproduced in the official ReVanced, it is not possible to identify which patch is causing the bug
Instead, I add the bug's symptoms and workarounds to the text

**Comment by inotia00** [comment] 2024-05-08 22:10
This issue appears to be reproduced in unpatched YouTube v19.16.39 as well.
Closing issue.

**Closed by inotia00** 2024-05-08 22:10 UTC
Labels: Bug report
