### ISSUE TITLE
Add several color themes to the settings.

### ISSUE THREAD

**Issue by Rusikxxx** [inotia00/ReVanced_Extended#1257] opened 2023-07-28 13:34 UTC
### Application

YouTube

### Description

I suggest adding a selection of additional color themes to the settings.

Dark:
```
<color name="yt_black1">#ff0f0f0f</color>
<color name="yt_black3">#ff0f0f0f</color>
```
Gray:
```
<color name="yt_black1">#ff212121</color>
<color name="yt_black3">#ff212121</color>
```
Black:
```
<color name="yt_black1">#ff000000</color>
<color name="yt_black3">#ff000000</color>
```
Blue:
```
<color name="yt_black1">#ff000332</color>
<color name="yt_black3">#ff000332</color>
```
Green:
```
<color name="yt_black1">#ff002700</color>
<color name="yt_black3">#ff002700</color>
```
Orange:
```
<color name="yt_black1">#ff4b1c00</color>
<color name="yt_black3">#ff4b1c00</color>
```
Violet
```
<color name="yt_black1">#ff442245</color>
<color name="yt_black3">#ff442245</color>
```

![28226282](https://github.com/inotia00/ReVanced_Extended/assets/54509082/6babe5d2-2b36-47dc-b547-d04212728863)
![28226283](https://github.com/inotia00/ReVanced_Extended/assets/54509082/53bd903e-c304-4553-8021-fa5d7717e8c7)
![28226284](https://github.com/inotia00/ReVanced_Extended/assets/54509082/9ff5f7ac-0c4d-43e0-bfa2-b7e475b25686)
![28226285](https://github.com/inotia00/ReVanced_Extended/assets/54509082/9aeb3cf3-42b0-4e0d-b77d-751f66d4a33e)
![28226286](https://github.com/inotia00/ReVanced_Extended/assets/54509082/4b359775-7e20-4521-b027-904f5a983d52)
![28226287](https://github.com/inotia00/ReVanced_Extended/assets/54509082/4221a666-7113-4935-906b-fb08d16c657d)
![28226288](https://github.com/inotia00/ReVanced_Extended/assets/54509082/a4e7fc28-3123-4bfa-9b50-c9f25d4eef06)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment] 2023-07-28 14:04
This is a duplicate of the following issue https://github.com/inotia00/ReVanced_Extended/issues/667

**Closed by inotia00** 2023-07-28 14:04 UTC
Labels: suggestion
