### ISSUE TITLE
bug(new-splash-animation): opening youtube link is buggy in Android 13+

### ISSUE THREAD

**Issue by madhurvarshney** [inotia00/ReVanced_Extended#1086] opened 2023-07-07 10:11 UTC
### Type

Error at runtime

### Tools used

Revancify

### Application

YouTube v18.25.39 non-root
Patch v2.181.6

### Bug description

When opening a youtube link, it opens in RVX but the screen turns black although the audio can be heard.

### Steps to reproduce

N.A.

### Relevant log output

```shell
N.A.
```

### Screenshots or videos

TURN THE VOLUME ON

https://github.com/inotia00/ReVanced_Extended/assets/125809686/8fc82c5b-5dfc-4a82-91fc-81f6be2ca63f

### Device Environment

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment] 2023-07-07 18:29
Please specify if this is a root build or not a root build

**Comment by madhurvarshney** [comment] 2023-07-07 18:30
Non root build

**Comment by inotia00** [comment] 2023-07-09 03:33
re-patch to the following environment, and let me know if the issue reproduces

YouTube v18.25.40 or YouTube v18.20.39
revanced-patches-v2.182.1

**Comment by Adity1243** [comment] 2023-07-09 09:29
https://github.com/inotia00/ReVanced_Extended/assets/131557644/b393b437-6b56-4ab6-a18c-63972f4ccb8d

The issue is not reproducing in my device try to choose all links that is shown in that option.in seetings  go miscellaneous choose open default app settings and select all you tube links as shown.

**Comment by anil-al** [comment] 2023-07-09 09:58
This is also happening on my device with the difference that it shows a white page in the app and on the PiP. This sometimes happens when I open a different app while a video is playing and the PiP is not activated nevertheless. Opening app, closing the PiP does not work. The only way is to restart the app. This wasn't producible before inotia00 took a break so, this is about something new.

**Comment by ANewDawn** [comment] 2023-07-09 10:14
Had this issue as well. Black screen with blank mini player at bottom.

It seems to open fine if you first have app open in background first then links display correctly. Only if app isn't open then links open to blank screen.

**Comment by madhurvarshney** [comment] 2023-07-09 18:32
> re-patch to the following environment, and let me know if the issue reproduces
> 
> YouTube v18.25.40 or YouTube v18.20.39 revanced-patches-v2.182.1

I re-patched with YouTube v18.25.40 and patch v2.182.1 and I checked for the issue immediately after the app installed and the issue was still there.
So I disabled the 'open supported links' settings of the RVX and then opened a youtube video link on chrome so that it opens in browser itself. Then i re-enabled the 'open supported links' settings and thereafter, the issue vanished, but unfortunately not for long. Sometimes (like 1-2 out of 10 times) the issue still appears.
I couldn't find any particular way that reproduces the issue every time.
P.S. this issue wasn't there patch v2.173.10 (May update). This started happening only after I updated to patch v2.181.4 (I didn't try patch v2.181.1)

**Comment by madhurvarshney** [comment] 2023-07-09 18:34
> Screenrecorder-2023-07-09-14-56-03-469.mp4 
> The issue is not reproducing in my device try to choose all links that is shown in that option.in seetings go miscellaneous choose open default app settings and select all you tube links as shown.

All youtube links are selected.

**Comment by madhurvarshney** [comment] 2023-07-09 18:38
> Had this issue as well. Black screen with blank mini player at bottom.
> 
> It seems to open fine if you first have app open in background first then links display correctly. Only if app isn't open then links open to blank screen.

In my case, it doesn't matter if the RVX app is open in background or not. The issue seems to me to appear at random. I couldn't find any particular way to reproduce the issue every time.

**Comment by madhurvarshney** [comment] 2023-07-12 12:57
Ig it is happening only if I enable new splash animation. Just check it.

**Comment by ANewDawn** [comment] 2023-07-12 13:07
> Ig it is happening only if I enable new splash animation. Just check it.

Where is that setting?

**Comment by madhurvarshney** [comment] 2023-07-12 13:09
> > Ig it is happening only if I enable new splash animation. Just check it.
> 
> Where is that setting?

Settings > ReVanced Extended > Miscellaneous > Enable new splash animation

**Comment by Adity1243** [comment] 2023-07-12 14:36
What is your android version ?

**Comment by madhurvarshney** [comment] 2023-07-12 14:37
> What is your android version ?

Android 13

**Comment by inotia00** [comment] 2023-07-12 14:54
> Ig it is happening only if I enable new splash animation. Just check it.

Is `Enable new splash animation` causing this bug?

**Comment by madhurvarshney** [comment] 2023-07-12 14:56
> > Ig it is happening only if I enable new splash animation. Just check it.
> 
> Is `Enable new splash animation` causing this bug?

Yes apparently. I have disabled it now and since then I haven't encountered the issue.

**Comment by Adity1243** [comment] 2023-07-13 03:11
> > Ig it is happening only if I enable new splash animation. Just check it.
> 
> Is `Enable new splash animation` causing this bug?

No,i had android 12 and this option  working flawlessly in my device maybe android version compatibility issues occuring or maybe background process.

**Comment by ciro-mota** [comment] 2023-07-15 23:49
I have a similar problem related to the new startup animation, when launching the app to the background opening another or going to the home screen when returning to YouTube minutes later I get a white screen as you can see in the attachment. 

If I disable the use of the new boot animation the problem does not occur. I use Samsung with Android 13 and non-root version.

![Screenshot_20230715_204315_One UI Home](https://github.com/inotia00/ReVanced_Extended/assets/57502603/605fb73b-4aae-4e8d-a982-4e4f47ddfb1e)

**Comment by inotia00** [comment] 2023-08-04 23:57
already fixed in the latest patches, closing the issue

**Closed by inotia00** 2023-08-04 23:57 UTC
Labels: bug

**Comment by ANewDawn** [comment] 2023-10-10 12:44
I'm getting similar bug error as this. Have disabled splash animation. On android 13 patched YouTube 18.33.40 with revancify.
