### ISSUE TITLE
bug(spoof-player-parameters): playback issue persists despite spoofing applied

### ISSUE THREAD

**Issue by laethy1** [inotia00/ReVanced_Extended#1238] opened 2023-07-26 15:04 UTC
### Type

Error at runtime

### Tools used

ReVanced Manager

### Application

YouTube v18.27.35

### Bug description

Video stuck loading  but enabling spoof player parameters doesn't work

### Steps to reproduce

N/A

### Relevant log output

```shell
N/A
```

### Screenshots or videos

https://github.com/inotia00/ReVanced_Extended/assets/121911559/18e80125-9f3b-4f15-a5ff-6a534725ad8f

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment] 2023-07-26 15:17
plase upload screenshot of Miscellaneous settings

![Miscellaneous settings ](https://github.com/inotia00/ReVanced_Extended/assets/108592928/2821c36e-20a1-48b3-ae96-73a24ed8a532)

**Comment by inotia00** [comment] 2023-07-26 15:18
ah, I checked
looks like a valid issue

**Comment by Fkkbjnbhnb** [comment] 2023-07-26 15:26
Enable "disable quic ptotocol" and try again, also try to clear cache/data. If that doesnt help reset your network settings.

**Comment by KobeW50** [comment] 2023-07-26 19:02
@laethy1 Did you just enable the spoof before recording? Because you need to restart the app after changing any of the spoof toggles.

**Comment by laethy1** [comment] 2023-07-26 23:15
> @laethy1 Did you just enable the spoof before recording? Because you need to restart the app after changing any of the spoof toggles in order to take effect
It was already enabled at the start when I patched the app

**Comment by inotia00** [comment] 2023-07-27 15:30
Nothing is certain yet

For optimal testing, please set up the following environment

- patch to `YouTube v18.20.39`
- turn on `spoof player parameters`
- change the spoof player parameter type to `incognito mode`

Test to see if the playback issue reproduces

**Comment by Spacellary** [comment] 2023-07-27 16:01
I am also not affected by this issue yet, but for those that are, please provide feedback when possible after testing as needed.

**Comment by Spacellary** [comment] 2023-07-27 19:16
> There is no such option in miscellaneous 

@Shailesh2002 Hey! We're looking for these options:

![Screenshot_2023-07-27-16-11-58-574_app.rvx.android.youtube.png](https://github.com/inotia00/ReVanced_Extended/assets/39604793/e7e8ee08-d0b4-4066-b07b-1f10d7700b41)

Can you please share your complete Patch log? It seems something either went wrong or you're missing by not including a required Patch...

Also just for completeness sake report the **version of YouTube** and **patches version** you're reporting from now, and weather or not you're using the **Default** recommend list of patches.

**Comment by Shailesh2002** [comment] 2023-07-27 21:51
![Screenshot_20230728-032101_YouTube.jpg](https://github.com/inotia00/ReVanced_Extended/assets/108743640/d23a8b24-7e3f-43b3-bf67-851e6bb7e5c8)

**Comment by Shailesh2002** [comment] 2023-07-27 21:53
![Screenshot_20230728-032149_YouTube.jpg](https://github.com/inotia00/ReVanced_Extended/assets/108743640/d1eb6ba6-c799-4c58-8665-65b628dc79b0)

**Comment by Shailesh2002** [comment] 2023-07-27 21:53
![Screenshot_20230728-032221_YouTube.jpg](https://github.com/inotia00/ReVanced_Extended/assets/108743640/e6dac17b-5357-4d65-ae93-762771cfeef2)

**Comment by Shailesh2002** [comment] 2023-07-27 22:03
> > There is no such option in miscellaneous 
> 
> @Shailesh2002 Hey! We're looking for these options:
> 
> ![Screenshot_2023-07-27-16-11-58-574_app.rvx.android.youtube.png](https://github.com/inotia00/ReVanced_Extended/assets/39604793/e7e8ee08-d0b4-4066-b07b-1f10d7700b41)
> 
> Can you please share your complete Patch log? It seems something either went wrong or you're missing by not including a required Patch...
> 
> Also just for completeness sake report the **version of YouTube** and **patches version** you're reporting from now, and weather or not you're using the **Default** recommend list of patches.

![Screenshot_20230728-032149_YouTube.jpg](https://github.com/inotia00/ReVanced_Extended/assets/108743640/32b8e28b-10a9-4971-bc8b-958d892c5a11)

![Screenshot_20230728-032221_YouTube.jpg](https://github.com/inotia00/ReVanced_Extended/assets/108743640/2af6ea4b-d6b1-42ea-a52b-53d2b7777421)

![Screenshot_20230728-032101_YouTube.jpg](https://github.com/inotia00/ReVanced_Extended/assets/108743640/a54c3d84-7a58-499e-a6d7-df74ca3c2a71)

**Comment by KobeW50** [comment] 2023-07-27 22:06
@Shailesh2002 update

**Comment by Shailesh2002** [comment] 2023-07-27 22:08
> @Shailesh2002 update

They asked for screenshot  of my vanced settings...

**Comment by Spacellary** [comment] 2023-07-27 22:35
> > @Shailesh2002 update
> 
> @KobeW50 
> They asked for screenshot  of my vanced settings...

@Shailesh2002 We need testing with the Latest patches and in the YouTube version specified.

**Comment by KobeW50** [comment] 2023-07-27 22:40
> @Shailesh2002 – We need testing with the Latest patches and in the YouTube version specified.
> 
> You need to update. Your version is very old and probably what is causing issues. If you update it will likely work fine.
> 
> If you want I can provide an APK with the requirments **for your testing** that you can install without affecting your current application. Let me know and I'll share with you.
> 
> _This is intended only as a means to ease the testing and providing a controllable version for testing._

For testing, inotia00 said to use 18.20.39

**Comment by Spacellary** [comment] 2023-07-27 22:45
> For testing, inotia00 said to use 18.20.39

I can make a Pre-Release version with the specific version and make it available as necessary for testing purposes.

**Comment by Shailesh2002** [comment] 2023-07-28 00:39
> > @Shailesh2002 – We need testing with the Latest patches and in the YouTube version specified.
> > 
> > You need to update. Your version is very old and probably what is causing issues. If you update it will likely work fine.
> > 
> > If you want I can provide an APK with the requirments **for your testing** that you can install without affecting your current application. Let me know and I'll share with you.
> > 
> > _This is intended only as a means to ease the testing and providing a controllable version for testing._
> 
> For testing, inotia00 said to use 18.20.39

@KobeW50 
Please provide apk

**Comment by KobeW50** [comment] 2023-07-28 00:41
@Shailesh2002 

https://www.apkmirror.com/apk/google-inc/youtube/youtube-18-20-39-release/youtube-18-20-39-android-apk-download/

**Comment by Shailesh2002** [comment] 2023-07-28 00:43
> @Shailesh2002 – We need testing with the Latest patches and in the YouTube version specified.
> 
> You need to update. Your version is very old and that's what is causing your issues. If you update it will very likely work fine.
> 
> You don't even have the fix for the issue in your application.
> 
> If you want I can provide an APK with the requirments **for your testing** that you can install without affecting your current application. Let me know and I'll share with you.
> 
> _This is intended only as a means to ease the testing and providing a controllable version for testing._

@Spacellary 

Provide apk so that I can install new version

**Comment by Spacellary** [comment] 2023-07-28 00:43
@Shailesh2002 you can patch the one Kobe provided using the latest [RVX Manager](https://github.com/inotia00/revanced-manager/releases/latest).

**Comment by Shailesh2002** [comment] 2023-07-28 00:48
> @Shailesh2002 you can patch the one Kobe provided using the latest [RVX Manager](https://github.com/inotia00/revanced-manager/releases/latest).

@Spacellary 
Please provide download link

**Comment by Spacellary** [comment] 2023-07-28 00:54
> Please provide download link

@Shailesh2002 -- Please beware that you must patch your own Revanced Extended, I am just another user trying to help and I'll link you this testing build for you to use just to validade the issue or not.

Report back as soon as possible after testing it...

[Re-youtube-182039-output.apk](https://github.com/Spacellary/ReVanced-Extended-Automated-Builds/releases/download/Build-2023.07.27-21.53.08/Re-youtube-182039-output.apk)

**Comment by Shailesh2002** [comment] 2023-07-28 00:54
> @Shailesh2002 
> 
> https://www.apkmirror.com/apk/google-inc/youtube/youtube-18-20-39-release/youtube-18-20-39-android-apk-download/

@KobeW50 


Can u give me latest version apk

**Comment by Spacellary** [comment] 2023-07-28 00:56
@Shailesh2002 For the principle of testing I provided a link to a pre-release version you can use to validade the issue, as I said please report back once you have it set as instructed:

* turn on spoof player parameters

* change the spoof player parameter type to incognito mode

**Comment by KobeW50** [comment] 2023-07-28 00:57
> Can u give me latest version apk

If you want to patch the currently suggested apk version you can follow [this guide](https://www.reddit.com/r/revancedextended/comments/12vxggr/revanced_extended_guide_for_beginners/)

Support can be given in the subreddit if you need. This issue thread is only for the original issue of the author.

**Comment by Shailesh2002** [comment] 2023-07-28 00:58
> @Shailesh2002 For the principle of testing I provided a link to a pre-release version you can use to validade the issue, as I said please report back once you have it set as instructed:
> 
> * turn on spoof player parameters
> 
> * change the spoof player parameter type to incognito mode
> 
> 

@Spacellary 

Hey...thanks for helping me
But I don't know how to test and all
Please u only do something...if anything goes wrong it would problem

**Comment by Spacellary** [comment] 2023-07-28 01:00
@Shailesh2002 -- Alright my friend unfortunately this is far as I can help, go to the subreddit and follow the Pinned Guide for Beginners to get updated. This is related to the issue reported and looks like it isn't your case.

**Comment by Shailesh2002** [comment] 2023-07-28 01:04
> @Shailesh2002 -- Alright my friend unfortunately this is far as I can help, go to the subreddit and follow the Pinned Guide for Beginners to get updated. This is related to the issue reported and looks like it isn't your case.

@Spacellary 
I am new to this github so I don't where to go for subreddit

**Comment by Spacellary** [comment] 2023-07-28 01:07
@Shailesh2002 [Here you go.](https://www.reddit.com/r/revancedextended/comments/12vxggr/revanced_extended_guide_for_beginners/)

**Comment by Shailesh2002** [comment] 2023-07-28 01:10
> @Shailesh2002 [Here you go.](https://www.reddit.com/r/revancedextended/comments/12vxggr/revanced_extended_guide_for_beginners/)

@Spacellary 

Thank you so much sir

**Comment by Qanaden** [comment] 2023-07-28 04:12
I've had this issue as well. I patched to 18.20.39 turned on spoof player parameter and spoof player parameter type. I have every battery optimization and data saver setting I can find turned off even battery protect (limit to 85%.) I set both the manager and apps battery settings to unrestricted. I still have the issue it'll run for about 3 minutes when the screen is off then stop.

**Comment by Spacellary** [comment] 2023-07-28 04:22
@Qanaden The issue you are referring to is a different one, we are testing playback with screen on.

How is that?

Your issue seems to be this one: https://github.com/ReVanced/revanced-patches/issues/2313

**Comment by Qanaden** [comment] 2023-07-28 04:35
> @Qanaden The issue you are referring to is a different one, we are testing playback with screen on stopping after ~1m10s.
> 
> How is that?
> 
> Your issue seems to be this one: https://github.com/ReVanced/revanced-patches/issues/2313

Idk I'm following the link I got on reddit in the post I made on the revanced extended sub. I have used revanced and had the same issue on there as well but atm I'm using revanced extended.

**Comment by Spacellary** [comment] 2023-07-28 04:44
@Qanaden 

Yeah yeah just saying you were linked this one:

![Screenshot_2023-07-28-01-42-34-855_com.laurencedawson.reddit_sync.png](https://github.com/inotia00/ReVanced_Extended/assets/39604793/a50ba9d6-bb51-4cd1-9d62-251f07450573)

Well, no problem. If you face playback issues let us know 👍

**Comment by savvaki** [comment] 2023-07-28 05:53
I can confirm that I also have playback issues. After a minute or so, videos get stuck and buffer indefinitely. I had an old version of the app and this issue occured, and when I updated the issue still persists.

**Comment by inotia00** [comment] 2023-07-28 05:59
> I am using the prebuilt APKs.

I do not provide support for issues arising from using prebuilt APKs.

**Comment by savvaki** [comment] 2023-07-28 06:05
> > I am using the prebuilt APKs.
> 
> I do not provide support for issues arising from using prebuilt APKs.

Just providing info, since multiple versions are failing at once, perhaps that could help with debugging. Otherwise, thanks for the speedy response and good luck!

**Comment by Shailesh2002** [comment] 2023-07-28 09:17
@Spacellary ![Screenshot_20230728-144536_YouTube.jpg](https://github.com/inotia00/ReVanced_Extended/assets/108743640/02c0e949-492b-4bc8-b671-33667b7f3d2c)
 How to hide that which I have circled

**Comment by Spacellary** [comment] 2023-07-28 09:30
>  How to hide that which I have circled

This is not the place for this, please ask questions in the general community channels like Reddit for example, this place is for discussion of issues only.

**Comment by Shailesh2002** [comment] 2023-07-28 09:33
> >  How to hide that which I have circled
> 
> This is not the place for this, please ask questions in the general community channels like Reddit for example, this place is for discussion of issues only.

@Spacellary 
Video stopping at 1min 10s

**Comment by inotia00** [comment] 2023-07-30 09:32
fixed in [revanced-patches-v2.186.10](https://github.com/inotia00/revanced-patches/releases/tag/v2.186.10)

**Closed by inotia00** 2023-07-30 09:32 UTC
Labels: bug, A/B test
