### ISSUE TITLE
Seekbar in fullscreen 

### ISSUE THREAD

**Issue by bosaad21** [inotia00/ReVanced_Extended#57] opened 2022-12-26 17:26 UTC
### Type

Error at runtime

### Application

YouTube 17.49.37

### Bug description

Issues with using the Seekbar in fullscreen
(Seekbar tapping is enabled)

### Steps to reproduce

Open any video in fullscreen mode.. you can't forward the video from the dot on the bar. You need to click on the empty place.

### Relevant log output

```shell
No logs
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by bosaad21** [comment] 2022-12-26 17:30
https://user-images.githubusercontent.com/71277632/209571823-b60a9a04-2384-41a3-b19d-93470cda162f.mp4

**Comment by inotia00** [comment] 2022-12-26 17:31
duplicate of the following issue:
https://github.com/inotia00/ReVanced_Extended/issues/54

**Closed by inotia00** 2022-12-26 17:31 UTC
Labels: bug
