### ISSUE TITLE
bugs(YouTube): known bugs for tablet ui

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1381] opened 2023-09-17 16:26 UTC
### Type

Error at runtime

### Tools used

Revancify

### Application

YouTube 18.19.36 ~ 18.31.40

### Bug description

IMPORTANT NOTICE!!! I opened issue to not u say that u won't fix these bugs, please not close it, i opened it to someone will find a possible fix, for this moment just block this switches in settings for tablet users, ok?
1. Hide channel avatar section of the subscriptions feed doesnt work for tablets cause of different places: in phone ui this section is in top of the subscriptions page, on tablet ui this section placed in the left side like this
![20230917_192033](https://github.com/inotia00/ReVanced_Extended/assets/110785596/8b44730e-1fea-4249-ace8-8f5aff135648)
2.Hide feed flyout menu and feed flyout menu filter doesnt work for tablets cause those menus has difference
1) phone
![266793865-b408b31e-b149-4288-b4e6-d459dab4eb99](https://github.com/inotia00/ReVanced_Extended/assets/110785596/da8cbd77-cac0-40f0-ba4b-103d14e24322)
2) tablet
![266793886-b36c3081-548c-4cd2-86f1-04f954b5afda (1)](https://github.com/inotia00/ReVanced_Extended/assets/110785596/c4e8ac65-98c5-4dbf-8e57-a6bd963be977)

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by girshcatt** [comment] 2023-09-17 16:27
And u said that u cant fix tablet problems, but i think u can fix hide channel avatar section, because it is the same if u will turn on tablet ui

**Comment by inotia00** [comment] 2023-09-17 16:37
1. For the `hide channel avatar section` patch, it is by design that it does not work on tablets.

This is because when the patch was first introduced, it was made to work only on the phone layout.

I disabled the `hide channel avatar section` switch on tablet devices or when the tablet UI is enabled to let users know that this feature is not available on tablets.

2. It appears to be a new layout applied to the tablet.

Simply using YouTube v18.19.36~v18.21.35 will fix this issue, probably.

**Comment by girshcatt** [comment] 2023-09-17 16:41
1. If u blocked this setting for tablets i have a related issue that for some reason blocked settings appear like normal, i dont know how this happen, clear random

**Comment by girshcatt** [comment] 2023-09-17 16:42
2.let my try 18.19.36 ~ 18.21.35, but if i not do a mistake i already tried 18.19.36, i will check it again

**Comment by girshcatt** [comment] 2023-09-17 17:04
I patched 18.21.35, nothing changed, and feed flyout panel looks the same

**Comment by girshcatt** [comment] 2023-09-17 17:17
Also strange thing i found that for some reason at 18.21.35 i see old flyout panel that was removed after 18.20.39

**Comment by inotia00** [comment] 2023-09-17 17:59
There are no plans to fix #1, but instead I will add in the patch description that it only works with the phone layout.

#2 was not a new layout
It was possible to reproduce it with a clean install at 720dpi, and it was easy to fix.

it will be reflected in the next patch

**Comment by girshcatt** [comment] 2023-09-17 20:04
> There are no plans to fix #1, but instead I will add in the patch description that it only works with the phone layout.
> 
> #2 was not a new layout It was possible to reproduce it with a clean install at 720dpi, and it was easy to fix.
> 
> it will be reflected in the next patch

Big thanks, i was sad that i thought u cant fix this problem, thank u so much ❤

**Comment by inotia00** [comment] 2023-09-20 07:26
fixed in [revanced-patches-v2.190.8](https://github.com/inotia00/revanced-patches/releases/tag/v2.190.8)

**Closed by inotia00** 2023-09-20 07:26 UTC
Labels: bug
