### ISSUE TITLE
bug: hide MixPlaylists causes weird glitches

### ISSUE THREAD

**Issue by anyujinie** [inotia00/ReVanced_Extended#320] opened 2023-02-23 19:08 UTC
### Type

Error at runtime

### Application

18.06.41 non-root

### Bug description

I was now just scrolling my feed and saw a weird video which had the 3 dot menu close to the profile picture and didn't have a video title. After around 7 secs of focusing on it the video title suddenly showed, and the 3 dot menu returned to it's correct place. I'm wondering is this glitch somehow related to 'hide mix playlist' patch?

EDIT: Now I'm seeing more and more of these glitches + the feed ends very soon. Only bit of scrolling needed. Isn't it supposed to load content infinitely no matter how much you scroll?

![Screenshot_20230223-200458152 (1)](https://user-images.githubusercontent.com/73917917/221006004-801e0769-03d0-4c77-8e90-d339895f30cf.png)

![Screenshot_20230223-200509418 (1)](https://user-images.githubusercontent.com/73917917/221006012-1350be1a-392d-4ff0-ba46-7645add2f5b8.png)

**Comment by anyujinie** [comment] 2023-02-24 01:48
More glitches. Missing buttons under video.

![Screenshot_20230224-024659245 (1).png](https://user-images.githubusercontent.com/73917917/221072097-d56e6081-4755-49f6-82e5-c96deeb345ce.png)

**Comment by inotia00** [comment] 2023-02-24 01:50
Temporarily disable Hide MixPlaylists

**Comment by anyujinie** [comment] 2023-02-24 01:50
> Temporarily disable Hide MixPlaylists

Ok have you seen my previous comment with the screenshot of missing buttons under video?

**Comment by inotia00** [comment] 2023-02-24 01:52
Aggressive filter applied to Hide Mix Playlists is causing the bug

**Comment by anyujinie** [comment] 2023-02-24 02:19
Just a black space being added?

![Screenshot_20230224-031858668 (1).png](https://user-images.githubusercontent.com/73917917/221076081-7688b478-2f98-49e8-b83f-024f178658d7.png)

**Comment by Issam28** [comment] 2023-02-24 12:02
The like, dislike and comment buttons have disappeared too when in Fullscreen mode. I don't know if this is an intended behavior or a bug. This seems to happens when hiding the share button. Here is a screenshot for reference.
![Screenshot_20230224-130005](https://user-images.githubusercontent.com/22579217/221174346-99c195c1-3953-4223-8282-c85b720421b8.png)

**Comment by anyujinie** [comment] 2023-02-24 12:09
@inotia00 I have long disabled hide mix playlists but regardless getting the glitches.

Seems like this empty space is 'remix' button even tho I have disabled that button aswell.

See here:
https://streamable.com/40ld5e

**Comment by inotia00** [comment] 2023-02-24 15:09
this bug will fix in tomarrow

**Comment by inotia00** [comment] 2023-02-24 22:30
fixed in [revanced-patches-v2.164.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.164.1)

**Closed by inotia00** 2023-02-24 22:30 UTC
Labels: bug

**Comment by inotia00** [comment] 2023-02-24 23:46
> @inotia00 I have long disabled hide mix playlists but regardless getting the glitches.
> 
> See here: https://streamable.com/40ld5e
> 
> Seems like this empty space is 'remix' button even tho I have disabled(don't want to see remix button) that button.
> 
> In another vid the share button seems missing:
> 
> ![Screenshot_20230224-132828980 (1).png](https://user-images.githubusercontent.com/73917917/221179180-4031f80f-e038-461b-9001-885468fa5ac4.png)
> 
> Seriously this release is fucked up 😅

If it still persists, please open a separate issue with an appropriate title.

**Comment by anyujinie** [comment] 2023-02-24 23:50
> If it still persists, please open a separate issue with an appropriate title.>

Ok, I guess there will be a new release soon
