### ISSUE TITLE
bug: Hide comment box causes live chat handling to fail. Probably litho change

### ISSUE THREAD

**Issue by jhon1282** [inotia00/ReVanced_Extended#1021] opened 2023-05-13 13:53 UTC
### Type

Other

### Tools used

Revancify

### Application

Youtube 18:17:43

### Bug description

In the new version of youtube live chat has been integrated into the comment box.
Disabling
![Screenshot_2023-05-13-15-23-00-549_app rvx android youtube](https://github.com/inotia00/ReVanced_Extended/assets/125223735/2334c4d0-0eea-48e0-833d-389be186364f)
![Screenshot_2023-05-13-15-23-10-908_app rvx android youtube](https://github.com/inotia00/ReVanced_Extended/assets/125223735/87a7e91a-9a07-4596-a312-182d2c66b78c)
 comments also disables live chat

### Steps to reproduce

Disable the comment box
Now try to open live chat
It won't open because part of the comments themselves

### Relevant log output

```shell
Na
```

### Solution

I assume modify the related litho component

### Device Environment

Android 12 miui 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment] 2023-05-13 15:56
As you said, the live chat area has been merged into a comment box.

And if you hide the comment box, the comment box is hidden as intended.

And when the comment box is hidden, the live chat area is also hidden
(because it's integrated).

This is a changelog from stock YouTube, so it's hard to see it as a bug

**Closed by inotia00** 2023-05-13 15:56 UTC
Labels: bug

**Comment by jhon1282** [comment] 2023-05-13 16:05
Apologies, but since the patch plans to hide the comment box and not the live chat as well I saw it as a bug.
I think it would be better to separate the two if possible.
Thanks a lot anyway :-)

**Comment by inotia00** [comment] 2023-05-13 16:09
yeah i will implement a patch to separate the two later if time permits
I haven't implemented it yet because I don't have enough time to do the reverse engineering
