### ISSUE TITLE
bug: Recurring certain intervals in case of low buffer?

### ISSUE THREAD

**Issue by sssh7710** [inotia00/ReVanced_Extended#1152] opened 2023-07-13 17:42 UTC
### Type

Other

### Tools used

Revancify

### Application

Youtube 18.25.40

### Bug description

This happens when you watch a video

### Steps to reproduce

1. Patch more than recommended
2. Open any video on YouTube
3. Move to near buffered area
4. Slowly pull forward for 5 seconds

### Relevant log output

```shell
Unable to find a way to export logs
```

### Screenshots or videos

https://github.com/inotia00/ReVanced_Extended/assets/98168192/83c51438-2d8e-4ecb-bcaa-1b4c68e8a685

### Additional context

This phenomenon occurs on both tablets and phones

### Device Environment

Android 13, one ui 5.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by sssh7710** [comment] 2023-07-13 17:44
I did a debug patch, but I don't know how to export it
If you tell me how to do it, I'll fix it including that

**Comment by inotia00** [comment] 2023-07-13 17:56
not reproduced

also the debug logging patch only outputs logs of layout components name

It doesn't print an error log

**Comment by sssh7710** [comment] 2023-07-13 19:10
> not reproduced
> 
> also the debug logging patch only outputs logs of layout components name
> 
> It doesn't print an error log

Then how do I submit the log?

**Comment by inotia00** [comment] 2023-07-13 19:14
Error logs in logcat are output only when fatal errors occur, such as force close due to an exception.

The attached video is not such a fatal error, so it won't be caught by logcat.

As you previously reported, I suspect this issue is related to SponsorBlock.

Exclude the `sponsorblock` patch and check if the issue reproduces.

**Comment by inotia00** [comment] 2023-07-24 07:41
fixed in [revanced-patches-v2.186.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.186.1)

**Closed by inotia00** 2023-07-24 07:41 UTC
Labels: bug
