### ISSUE TITLE
bug(YouTube/Settings) : In RVX Settings, `header text` & `back button` are not side-by-side.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [inotia00/ReVanced_Extended#2201] opened 2024-06-28 04:12 UTC
### Type

Cosmetic

### Tools used

Revancify

### Application

YT v19.23.40

Latest dev patches & dev integrations, as of today.

### Bug description

In RVX Settings, `header text` and `back button` are not side-by-side. In other words, they are not in alignment with reference to each other's position.

Few months ago, this bug didn't existed. I think it happened after the re-organization of settings took place (or maybe not).

The misalignment is same for the sub-menus like Ads, Feed, General, Player, etc.

![Screenshot_2024-06-28-09-31-32-01_a9acfd2263b6b7a65bf2540b0d9449ca](https://github.com/inotia00/ReVanced_Extended/assets/91815107/9bdf1e91-e6de-4c54-a306-eff81810ee5c)

![Screenshot_2024-06-28-09-45-32-74_a9acfd2263b6b7a65bf2540b0d9449ca.jpg](https://github.com/inotia00/ReVanced_Extended/assets/91815107/5546f3c2-5230-447c-88d9-71b64b2b6336)

![Screenshot_2024-06-28-09-45-40-68_a9acfd2263b6b7a65bf2540b0d9449ca.jpg](https://github.com/inotia00/ReVanced_Extended/assets/91815107/c857e72b-4924-4d2b-b471-13b8aaa58625)

### Error logs

```shell
No logs.
```

### Solution

Both of them should be side-by-side, just like so many other Android apps.

### Additional context

No additional context.

### Device Environment

Realme 7 Pro.

Android 12 (Realme UI 3.0).

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment] 2024-06-28 06:03
It does not reproduce on my side

Doesn't the issue reproduce when you turn off the pre-releases setting and patch again?
(Instead of installing the patched app, patch it again)

**Comment by Aryan-Chauhan** [comment] 2024-06-28 11:21
Still the same.

![Screenshot_2024-06-28-16-50-13-73_d11ae654701a5fadb313ea6fa9a6836f.jpg](https://github.com/inotia00/ReVanced_Extended/assets/91815107/902e9287-df78-42ea-bb43-8baaaca49c76)

![Screenshot_2024-06-28-16-50-29-53_d11ae654701a5fadb313ea6fa9a6836f.jpg](https://github.com/inotia00/ReVanced_Extended/assets/91815107/33bfc4fa-8cf0-4130-8592-c7186d6a3ac1)

**Comment by inotia00** [comment] 2024-06-28 12:39
If so, this is probably not a bug that originated in the latest release

It appears to be a bug that has been around for quite some time, or a bug related to system fonts

**Comment by ILoveOpenSourceApplications** [comment] 2024-06-28 13:02
How is it inside YouTube's General setting?

**Comment by sr-shishir** [comment] 2024-06-28 15:30
> Still the same.
> 
> ![Screenshot_2024-06-28-16-50-13-73_d11ae654701a5fadb313ea6fa9a6836f.jpg](https://private-user-images.githubusercontent.com/91815107/344143365-902e9287-df78-42ea-bb43-8baaaca49c76.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1ODcxNzAsIm5iZiI6MTcxOTU4Njg3MCwicGF0aCI6Ii85MTgxNTEwNy8zNDQxNDMzNjUtOTAyZTkyODctZGY3OC00MmVhLWJiNDMtOGJhYWFjYTQ5Yzc2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI4VDE1MDExMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3NWZmYzJmOTcyYTAxZTM3OWJhNDc3MDMyZjJkYmE2MGZjMjExYzViNmYzZjk0NWM0N2U1YmIwMGU0ZDY3ZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-wOalzkjeVUKqnRWv8CN38o-RD_0P7scc29Xd5HRyis)
> 
> ![Screenshot_2024-06-28-16-50-29-53_d11ae654701a5fadb313ea6fa9a6836f.jpg](https://private-user-images.githubusercontent.com/91815107/344143416-33bfc4fa-8cf0-4130-8592-c7186d6a3ac1.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1ODcxNzAsIm5iZiI6MTcxOTU4Njg3MCwicGF0aCI6Ii85MTgxNTEwNy8zNDQxNDM0MTYtMzNiZmM0ZmEtOGNmMC00MTMwLTg1OTItYzcxODZkNmEzYWMxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI4VDE1MDExMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1OTQ3NzhlMjFmZWI5OGVjYWRjYWU0ZGQ4ZWVmYmJlODAyYzJmZTYyNjNiMzg0NDgyNzkyY2Y1YzMyMmZlMWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-PBqFldzBEaR5Px05ItOyUpmjx1CcKm42PfJ75FYYhs)

I think it's not a bug. I checked official YouTube settings UI, there also a slight up & down between these two signs.

**Comment by inotia00** [comment] 2024-06-28 15:59
It may have been fixed by https://github.com/inotia00/revanced-integrations/commit/f36f3b0900dcf6e1e2f729023272410812442cbf

**Comment by Aryan-Chauhan** [comment] 2024-06-28 16:01
> How is it inside YouTube's General setting?

Not perfect, but better than RVX.

![Screenshot_2024-06-28-21-30-40-41_a9acfd2263b6b7a65bf2540b0d9449ca.jpg](https://github.com/inotia00/ReVanced_Extended/assets/91815107/3947e006-7ab1-4947-83a5-683eabee78bd)

**Comment by Aryan-Chauhan** [comment] 2024-06-28 16:02
> > Still the same.
> > 
> > ![Screenshot_2024-06-28-16-50-13-73_d11ae654701a5fadb313ea6fa9a6836f.jpg](https://private-user-images.githubusercontent.com/91815107/344143365-902e9287-df78-42ea-bb43-8baaaca49c76.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1ODcxNzAsIm5iZiI6MTcxOTU4Njg3MCwicGF0aCI6Ii85MTgxNTEwNy8zNDQxNDMzNjUtOTAyZTkyODctZGY3OC00MmVhLWJiNDMtOGJhYWFjYTQ5Yzc2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI4VDE1MDExMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3NWZmYzJmOTcyYTAxZTM3OWJhNDc3MDMyZjJkYmE2MGZjMjExYzViNmYzZjk0NWM0N2U1YmIwMGU0ZDY3ZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-wOalzkjeVUKqnRWv8CN38o-RD_0P7scc29Xd5HRyis)
> > 
> > ![Screenshot_2024-06-28-16-50-29-53_d11ae654701a5fadb313ea6fa9a6836f.jpg](https://private-user-images.githubusercontent.com/91815107/344143416-33bfc4fa-8cf0-4130-8592-c7186d6a3ac1.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1ODcxNzAsIm5iZiI6MTcxOTU4Njg3MCwicGF0aCI6Ii85MTgxNTEwNy8zNDQxNDM0MTYtMzNiZmM0ZmEtOGNmMC00MTMwLTg1OTItYzcxODZkNmEzYWMxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI4VDE1MDExMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1OTQ3NzhlMjFmZWI5OGVjYWRjYWU0ZGQ4ZWVmYmJlODAyYzJmZTYyNjNiMzg0NDgyNzkyY2Y1YzMyMmZlMWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-PBqFldzBEaR5Px05ItOyUpmjx1CcKm42PfJ75FYYhs)
> 
> I think it's not a bug. I checked official YouTube settings UI, there also a slight up & down between these two signs.

Yes, slight. 

But in RVX Settings, it's much more noticeable.

**Comment by Aryan-Chauhan** [comment] 2024-06-28 16:14
No difference on my side.

![Screenshot_2024-06-28-21-43-51-65_a9acfd2263b6b7a65bf2540b0d9449ca.jpg](https://github.com/inotia00/ReVanced_Extended/assets/91815107/ed67c49d-6203-4ca9-9021-3e9ec0c56530)

**Comment by Francesco146** [comment] 2024-06-29 12:17
https://github.com/inotia00/revanced-patches/commit/ab2db2b8b88337ded3ea43e91600819fab5e48f1

this might be the cause

**Comment by Francesco146** [comment] 2024-06-29 12:19
@Aryan-Chauhan test the latest stable Release of RVX, should work as expected.

**Comment by Aryan-Chauhan** [comment] 2024-06-29 12:29
> @Aryan-Chauhan test the latest stable Release of RVX, should work as expected.
> 
> 

I already tried v4.9.2 and it is the same.

I showed screenshot of v4.9.2 as well.

**Comment by Francesco146** [comment] 2024-06-29 12:43
mmh, then the code you are running works fine on my phone, might be a font style issue

**Comment by inotia00** [comment] 2024-07-01 03:40
Yeah.. There haven't been any changes to the toolbar side of RVX settings in recent months

It was an issue that could not be reproduced even though I tested it on 3 devices
(can't be fixed on the RVX side)

Closing issue

**Closed by inotia00** 2024-07-01 03:40 UTC
Labels: Bug report
