### ISSUE TITLE
bug: `music-microg-support` patch causes YT settings to crash

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [inotia00/ReVanced_Extended#874] opened 2023-04-28 09:57 UTC
### Type

Error at runtime

### Application

YT Music v5.54.52

### Bug description

When patching YT Music with the latest patches 2.171.1 and going into any of the apps settings, the app either crashes or goes back into the home page.

### Steps to reproduce

Step 1: Patch with the latest patches (2.171.1)
Step 2: Go into any of the YT Music settings.
Step 3: Crashes.

### Relevant log output

```shell
Nil
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by anyujinie** [comment] 2023-04-28 10:25
Same here. Just updated now and pressing any of the YTM settings crashes the app.
https://user-images.githubusercontent.com/73917917/235123132-bf84ffd7-2d46-47b5-9277-1bcf3d306d17.mp4

**Comment by inotia00** [comment] 2023-04-28 11:24
'music-microg-support' patch is the cause

Fortunately I found the cause quickly so wait for the next release
(hotfix will be released tomorrow or the day after tomorrow)

**Comment by inotia00** [comment] 2023-04-28 18:46
reflected in [revanced-patches-v2.171.2](https://github.com/inotia00/revanced-patches/releases/tag/v2.171.2)

**Closed by inotia00** 2023-04-28 18:46 UTC
Labels: bug
