### ISSUE TITLE
feat(patch): disable exiting fullscreen mode after turning screen off/on

### ISSUE THREAD

**Issue by MondayNitro** [inotia00/ReVanced_Extended#947] opened 2023-05-04 05:15 UTC
### Application

YouTube

### Issue

if you turn off the screen while in fullscreen mode and then turn on the screen again, the app exits fullscreen and goes to portrait mode. add a patch that disables this and keeps the player in fullscreen mode.

### Patch

if you turn off the screen while in fullscreen mode and then turn on the screen again, the app exits fullscreen and goes to portrait mode. add a patch that disables this and keeps the player in fullscreen mode.

### Motivation

saves the effort of having to enter fullscreen mode again after turning the screen on

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Metallifani666** [comment] 2023-05-04 07:38
Duplicate of #872 

@inotia00 You can close this one.

**Closed** 2023-05-04 12:33 UTC
Labels: patch-request
