### ISSUE TITLE
bug(YouTube/Toolbar components) : `Hide trending searches` doesn't work

### ISSUE THREAD

**Issue by Aryan-Chauhan** [inotia00/ReVanced_Extended#1993] opened 2024-05-11 06:52 UTC
**NOTE** : Check all comments for new information.

### Type

Cosmetic

### Tools used

Revancify

### Application

YT v19.16.39

Patches v4.8.0-dev.4

Integrations v1.9.0-dev.3

### Bug description

**Hide Trending Searches** doesn't work if watch history has zero videos.

To make it work, I enabled my watch history, then I watched one video, then disabled watch history. After doing this, **Hide Trending Searches** immediately starts working perfectly. It has been like this for months.

But this comes with a cost. With 1 video in your watch history, Home Feed suggestions come back for you.

So, it is requested to make **Hide Trending Searches** work even if user's watch history has zero videos.
![Screenshot_2024-05-11-12-05-17-63_a9acfd2263b6b7a65bf2540b0d9449ca](https://github.com/inotia00/ReVanced_Extended/assets/91815107/cc9b060a-7146-41ec-9ef5-ef3335c4ec8c)
![Screenshot_2024-05-11-12-05-52-44_a9acfd2263b6b7a65bf2540b0d9449ca](https://github.com/inotia00/ReVanced_Extended/assets/91815107/fa0fa8a9-7e76-4ce8-81ba-de1e90164c4e)

### Error logs

```shell
No logs.
```

### Solution

The functionality of **Hide Trending Searches** shouldn't depend on the number of videos in user's watch history.

### Additional context

No additional context.

### Device Environment

Realme 7 Pro running on Android 12 (skin name is Realme UI 3.0).

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment] 2024-05-11 10:44
`Hide trending search` setting hides the `search term suggestion` contains the `Fire` icon.

All other search terms are not hidden.

**Comment by Aryan-Chauhan** [comment] 2024-05-19 00:51
> `Hide trending search` setting hides the `search term suggestion` contains the `Fire` icon.
> 
> All other search terms are not hidden.

If I open another issue like `Improve Hide Trending Searches to hide all type of trending searches,`, will you consider or not interested?

**Comment by Aryan-Chauhan** [comment] 2024-05-19 00:51
> > `Hide trending search` setting hides the `search term suggestion` contains the `Fire` icon.
> > 
> > All other search terms are not hidden.
> 
> If I open another issue like `Improve Hide Trending Searches to hide all type of trending searches,`, will you consider it or not interested?

**Comment by Aryan-Chauhan** [comment] 2024-05-19 01:30
Just now, I noticed this.
`Hide Trending Searches` is just hiding the fire icon & not the whole search suggestion. Compare these two screenshots.

`Hide Trending Searches` disabled:
![Screenshot_2024-05-19-06-54-39-73_fe557b5c831afa8eecca413bd340ebe7.jpg](https://github.com/inotia00/ReVanced_Extended/assets/91815107/75099ac8-7837-4c12-9633-00425c2f58e4)

`Hide Trending Searches` enabled:
![Screenshot_2024-05-19-06-54-39-73_fe557b5c831afa8eecca413bd340ebe7.jpg](https://github.com/inotia00/ReVanced_Extended/assets/91815107/fbe6fbc6-307a-4f34-8129-470039d30203)

**Comment by inotia00** [comment] 2024-05-19 03:28
It makes sense.
It seems that the patch no longer works due to server-side changes.
`Hide trending search` setting will be removed in the next release.

**Comment by Aryan-Chauhan** [comment] 2024-05-19 03:47
Thanks!

Any chance of making it work in accordance to the new server-side changes?

**Comment by inotia00** [comment] 2024-05-19 03:50
When I checked the bytecode, I couldn't make it support the new server-side changes right now.

`Hide trending searches` setting will be added again when server-side changes are supported in the future.
Until then the `Hide trending searches` setting will be removed.

**Comment by YT-Advanced** [comment] 2024-05-19 04:37
> When I checked the bytecode, I couldn't make it support the new server-side changes right now.
> 
> `Hide trending searches` setting will be added again when server-side changes are supported in the future.
> Until then the `Hide trending searches` setting will be removed.

You can filter this new "suggestion searches" via "yt_outline_new_search_black_24" drawable inside resources

**Comment by YT-Advanced** [comment] 2024-05-19 04:39
> > When I checked the bytecode, I couldn't make it support the new server-side changes right now.
> > 
> > `Hide trending searches` setting will be added again when server-side changes are supported in the future.
> > Until then the `Hide trending searches` setting will be removed.
> 

In the past, I have filtered this new "suggestion searches" via "yt_outline_new_search_black_24" drawable inside resources. However, it have some layout problem so I decided to reject this changes

**Comment by inotia00** [comment] 2024-05-19 04:42
Removing setting is not a big deal until server-side changes are supported.
Rather, not removing setting that is not working properly causes more confusion to users.

**Comment by YT-Advanced** [comment] 2024-05-19 04:42
Additational, trending search setting hides the search suggestion with the Fire icon, so I think you should close this issues without removing patch

**Comment by YT-Advanced** [comment] 2024-05-19 04:44
> Rather, not removing setting that is not working properly causes more confusion to users.

The patch is still worked, it did its jobs (hide searches with `Fire` icon)

**Comment by inotia00** [comment] 2024-05-19 04:45
> Additational, trending search setting hides the search suggestion with the Fire icon, not other search suggestion type so I think you should close this issues without removing patch

nah.. refer it

> Just now, I noticed this.
> Hide Trending Searches is just hiding the fire icon & not the whole search suggestion. Compare these two screenshots.

https://github.com/inotia00/ReVanced_Extended/issues/1993#issuecomment-2119053640

**Comment by YT-Advanced** [comment] 2024-05-19 04:53
> `Hide trending searches` setting changes fire icon to search icon instead of hiding it

Ah got it

**Comment by inotia00** [comment] 2024-05-26 09:32
reflected in [revanced-patches-4.8.3](https://github.com/inotia00/revanced-patches/releases/tag/v4.8.3)

**Closed by inotia00** 2024-05-26 09:32 UTC
Labels: Bug report

**Comment by Aryan-Chauhan** [comment] 2024-06-14 02:44
> `Hide trending searches` setting will be added again when server-side changes are supported in the future.
> Until then the `Hide trending searches` setting will be removed.

This means that there is a possibility of this feature returning in the future (if inotia00, anddea, YT-Advanced, ReVanced Team or other devs figures out how to make it work).

I think, for this reason alone, this issue should be kept open.

**Comment by 0xrxL** [comment] 2024-08-06 10:20
So the problem happens when the searchbar is empty and the suggested results (with zoom lens icon) are visible. In this case it should be possible to add a further check to hide all the results dinamically, once the searchbar is empty.

@inotia00 the removed patch allow to hide everything together in 3 steps (1 for every icon), just the empty searchbar check need to be implemented.

**Comment by Aryan-Chauhan** [comment] 2024-08-06 10:58
These `trending searches` doesn't show when you have 1 or 1+ videos in your watch history.

They do show when you have 0 videos in your watch history.

So, is there any way to "spoof" the search page making it think the user has some videos in their watch history? That could make it possible.

**Comment by 0xrxL** [comment] 2024-08-06 11:02
> These `trending searches` doesn't show when you have 1 or 1+ videos in your watch history.
> 
> They do show when you have 0 videos in your watch history.
> 
> So, is there any way to "spoof" the search page making it think the user has some videos in their watch history? That could make it possible.

Unfortunately I can't reproduce this issue on my side. I got always 0 trending results, also with an empty history list.

In the opposite case, I would have already tried to solve the problem.

**Comment by 0xrxL** [comment] 2024-08-06 11:05
Anyway...try to patch the latest RvX version with the removed patch, and check if the bug has been solved. A similar problem happened to me 4 months ago, and solved itself after some weeks.

**Comment by Aryan-Chauhan** [comment] 2024-08-06 11:13
Hmm.

BTW, people who doesn't add account to RVX app also don't get `trending searches` in their search page.

Any way to spoof that?

**Comment by Aryan-Chauhan** [comment] 2024-08-06 11:17
> Anyway...try to patch the latest RvX version with the removed patch, and check if the bug has been solved. A similar problem happened to me 4 months ago, and solved itself after some weeks.

Using these patches + 0 videos in watch history + watch history paused.

![Screenshot_2024-08-06-16-45-48-91_f22faf49515899f9781ec174a4d85388.jpg](https://github.com/user-attachments/assets/685d0b9d-ff80-4880-8d06-cd20be42ae07)

Getting this:

![Screenshot_2024-08-06-16-47-01-30_f22faf49515899f9781ec174a4d85388.jpg](https://github.com/user-attachments/assets/8f50547c-3eb4-4e8c-9337-4c705ee4e536)

**Comment by 0xrxL** [comment] 2024-08-06 11:18
> Hmm.
> 
> BTW, people who doesn't add account to RVX app also don't get `Trending Searches` in their search page.
> 
> Any way to spoof that?

If there is a way, I don't actually know how to achieve it. But it's pointless, due to others (and more easier) way to fix it. If the bug still exists on last version of RvX, a check on the searchbar digited text could be done.

**Comment by 0xrxL** [comment] 2024-08-06 11:20
> > Anyway...try to patch the latest RvX version with the removed patch, and check if the bug has been solved. A similar problem happened to me 4 months ago, and solved itself after some weeks.
> 
> Using these patches + 0 videos in watch history + watch history paused.
> 
> ![Screenshot_2024-08-06-16-45-48-91_f22faf49515899f9781ec174a4d85388.jpg](https://private-user-images.githubusercontent.com/91815107/355427323-685d0b9d-ff80-4880-8d06-cd20be42ae07.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NDMzNjMsIm5iZiI6MTcyMjk0MzA2MywicGF0aCI6Ii85MTgxNTEwNy8zNTU0MjczMjMtNjg1ZDBiOWQtZmY4MC00ODgwLThkMDYtY2QyMGJlNDJhZTA3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDExMTc0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkZjExZjA2ZmU1NTZkMWQwMDYyN2JiMGE3MWU5ZmY2NmJjYzBjM2E0OTk2MDU3ZjQ3YmJjMmQxOTMyMGE5YzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ytNtkLrEHeO3ayrwt-W4Vycw85m-eqFGAoOz70TDk-g)
> 
> Getting this:
> 
> ![Screenshot_2024-08-06-16-47-01-30_f22faf49515899f9781ec174a4d85388.jpg](https://private-user-images.githubusercontent.com/91815107/355427441-8f50547c-3eb4-4e8c-9337-4c705ee4e536.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NDMzNjMsIm5iZiI6MTcyMjk0MzA2MywicGF0aCI6Ii85MTgxNTEwNy8zNTU0Mjc0NDEtOGY1MDU0N2MtM2ViNC00ZThjLTkzMzctNGM3MDVlZTRlNTM2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDExMTc0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjMDU0YWZmYmM0MzczMmU1NWY5OTM2MDBmNzY5YjE1YmQ5ZmExM2FiNjYwMmRkYzY5NjZhNDQ3NjljMDE2NDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3oPHpTvisMSBDlEy_WLIGbwYlb6ft9GXQ8k2W2NYVTY)

You are using a version without patch (has been removed by inotia 2 months ago, waiting for the A/B test to finish).

**Comment by 0xrxL** [comment] 2024-12-11 02:27
@inotia00 https://github.com/ReVanced/revanced-patches/issues/4101

**Comment by 0xrxL** [comment] 2024-12-11 04:33
> @inotia00 [ReVanced/revanced-patches#4101](https://github.com/ReVanced/revanced-patches/issues/4101)

@YT-Advanced Can you port this mod to RvX? I'm allergic to kotlin. 👍

**Comment by YT-Advanced** [comment] 2024-12-12 08:03
> > @inotia00 [ReVanced/revanced-patches#4101](https://github.com/ReVanced/revanced-patches/issues/4101)
> 
> @YT-Advanced Can you port this mod to RvX? I'm allergic to kotlin. 👍

Uhm rn it seem like A/B Testing, so I cannot test this stuff in my side
