### ISSUE TITLE
bug(sponsorblock): slight audio delay when skipping segments

### ISSUE THREAD

**Issue by sleepingiv** [inotia00/ReVanced_Extended#682] opened 2023-04-09 15:12 UTC
### Type

Error at runtime

### Application

YouTube 18.13.38
Patch 2.168.27

### Bug description

.

### Steps to reproduce

.

### Relevant log output

```shell
.
```

### Device Environment

Android 13 , MIUI 14 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by madhurvarshney** [comment] 2023-04-09 15:20
Please attach a screen recording showing it.

**Comment by inotia00** [comment] 2023-04-09 15:20
please add a description

**Comment by sleepingiv** [comment] 2023-04-09 15:55
https://user-images.githubusercontent.com/64865031/230783127-95dd156d-cb37-4639-80bc-f872ccd8708e.mp4

**Comment by sleepingiv** [comment] 2023-04-09 15:59
https://user-images.githubusercontent.com/64865031/230783324-05f236b4-783b-4105-91a3-121e572cc9c7.mp4

**Comment by inotia00** [comment] 2023-04-09 16:05
I don't know what the issue is even though I watched the video
(The circular animation shown when the buffer occurs also does not appear)

Please reopen the issue with additional information about what the symptom is and under what conditions the issue is reproducible.

**Comment by sleepingiv** [comment] 2023-04-09 16:11
I don't know how to reproduce cause this is happening with every skip in every video . I am giving the patchlog if it can help - 

INFO: Reading dex files 
INFO: Loading resource table... 
INFO: Decoding AndroidManifest.xml only, because resources are not needed 
INFO: Loading resource table from file: revanced-cache/1.apk 
INFO: Skipping bypass-ambient-mode-restrictions: Excluded by default 
INFO: Skipping change-homepage: Excluded by default 
INFO: Skipping client-spoof: Excluded by default 
INFO: Skipping custom-branding-icon-afn-blue: Excluded by default 
INFO: Skipping custom-branding-icon-afn-red: Excluded by default 
INFO: Skipping custom-branding-icon-revancify: Excluded by default 
INFO: Skipping disable-haptic-feedback: Excluded by default 
INFO: Skipping disable-landscape-mode: Excluded by default 
INFO: Skipping disable-quic-protocol: Excluded by default 
INFO: Skipping disable-startup-shorts-player: Excluded by default 
INFO: Skipping enable-external-browser: Excluded by default 
INFO: Skipping enable-old-layout: Excluded by default 
INFO: Skipping enable-tablet-miniplayer: Excluded by default 
INFO: Skipping enable-tablet-navigation-bar: Excluded by default 
INFO: Skipping enable-wide-searchbar: Excluded by default 
INFO: Skipping force-player-button-background: Excluded by default 
INFO: Skipping force-premium-heading: Excluded by default 
INFO: Skipping force-vp9-codec: Excluded by default 
INFO: Skipping header-switch: Excluded by default 
INFO: Skipping hide-account-menu: Excluded by default 
INFO: Skipping hide-autoplay-preview: Excluded by default 
INFO: Skipping hide-captions-button: Excluded by default 
INFO: Skipping hide-category-bar: Excluded by default 
INFO: Skipping hide-collapse-button: Excluded by default 
INFO: Skipping hide-comment-component: Excluded by default 
INFO: Skipping hide-email-address: Excluded by default 
INFO: Skipping hide-endscreen-overlay: Excluded by default 
INFO: Skipping hide-filmstrip-overlay: Excluded by default 
INFO: Skipping hide-fullscreen-buttoncontainer: Excluded by default 
INFO: Skipping hide-fullscreen-panels: Excluded by default 
INFO: Skipping hide-live-chat-button: Excluded by default 
INFO: Skipping hide-player-button-background: Excluded by default 
INFO: Skipping hide-player-overlay-filter: Excluded by default 
INFO: Skipping hide-previous-next-button: Excluded by default 
INFO: Skipping hide-seekbar: Excluded by default 
INFO: Skipping hide-snackbar: Excluded by default 
INFO: Skipping hide-suggested-actions: Excluded by default 
INFO: Skipping hide-time-stamp: Excluded by default 
INFO: Skipping layout-switch: Excluded by default 
INFO: Skipping protobuf-spoof: Excluded by default 
INFO: Skipping switch-create-notification: Excluded by default 
INFO: Skipping translations: Excluded by default 
INFO: Merging inotia00-integrations-v0.101.27.apk 
INFO: Loading resource table... 
INFO: Deleting existing resource cache directory 
INFO: Decoding resources 
INFO: Decoding AndroidManifest.xml with resources... 
INFO: Loading resource table from file: revanced-cache/1.apk 
INFO: Regular manifest package... 
INFO: Decoding file-resources... 
INFO: Decoding values */* XMLs... 
INFO: custom-branding-icon-mmt succeeded 
INFO: custom-branding-name succeeded 
INFO: custom-seekbar-color succeeded 
INFO: custom-video-speed succeeded 
INFO: default-video-quality succeeded 
INFO: default-video-speed succeeded 
INFO: enable-minimized-playback succeeded 
INFO: enable-old-quality-layout succeeded 
INFO: enable-open-links-directly succeeded 
INFO: enable-seekbar-tapping succeeded 
INFO: enable-timestamps-speed succeeded 
INFO: hide-auto-captions succeeded 
INFO: hide-auto-player-popup-panels succeeded 
INFO: hide-autoplay-button succeeded 
INFO: hide-button-container succeeded 
INFO: hide-cast-button succeeded 
INFO: hide-channel-avatar-section succeeded 
INFO: hide-channel-watermark succeeded 
INFO: hide-create-button succeeded 
INFO: hide-crowdfunding-box succeeded 
INFO: hide-endscreen-cards succeeded 
INFO: hide-floating-microphone succeeded 
INFO: hide-flyout-panel succeeded 
INFO: hide-general-ads succeeded 
INFO: hide-info-cards succeeded 
INFO: hide-mix-playlists succeeded 
INFO: hide-music-button succeeded 
INFO: hide-pip-notification succeeded 
INFO: hide-shorts-button succeeded 
INFO: hide-shorts-component succeeded 
INFO: hide-shorts-navbar succeeded 
INFO: hide-stories succeeded 
INFO: hide-tooltip-content succeeded 
INFO: hide-video-ads succeeded 
INFO: lift-vertical-video-restriction succeeded 
INFO: materialyou succeeded 
INFO: microg-support succeeded 
INFO: optimize-resource succeeded 
INFO: overlay-buttons succeeded 
INFO: patch-options succeeded 
INFO: return-youtube-dislike succeeded 
INFO: settings succeeded 
INFO: sponsorblock succeeded 
INFO: swipe-controls succeeded 
INFO: theme succeeded 
INFO: Compiling resources 
INFO: Writing modified dex files 
INFO: Aligning YouTube-18-13-38.apk to YouTube-Revanced-18-13-38_aligned.apk 
INFO: Signing YouTube-Revanced-18-13-38_aligned.apk to YouTube-Revanced-18-13-38_signed.apk 
INFO: Found existing keystore: revanced.keystore 
INFO: Copying YouTube-Revanced-18-13-38_signed.apk to YouTube-Revanced-18-13-38.apk 
INFO: Cleaned up cache directory 
INFO: Finished 



Variant: nonRoot
Arch: arm64-v8a
App: YouTube-18-13-38.apk
CLI: inotia00-cli-v2.21.0.jar
Patches: inotia00-patches-v2.168.27.jar
Integrations: inotia00-integrations-v0.101.27.apk
Patches argument: -i custom-branding-icon-mmt
-i custom-branding-name
-i custom-seekbar-color
-i custom-video-speed
-i default-video-quality
-i default-video-speed
-i enable-minimized-playback
-i enable-old-quality-layout
-i enable-open-links-directly
-i enable-seekbar-tapping
-i enable-timestamps-speed
-i hide-auto-captions
-i hide-auto-player-popup-panels
-i hide-autoplay-button
-i hide-button-container
-i hide-cast-button
-i hide-channel-avatar-section
-i hide-channel-watermark
-i hide-create-button
-i hide-crowdfunding-box
-i hide-endscreen-cards
-i hide-floating-microphone
-i hide-flyout-panel
-i hide-general-ads
-i hide-info-cards
-i hide-mix-playlists
-i hide-music-button
-i hide-pip-notification
-i hide-shorts-button
-i hide-shorts-component
-i hide-shorts-navbar
-i hide-stories
-i hide-tooltip-content
-i hide-video-ads
-i lift-vertical-video-restriction
-i materialyou
-i microg-support
-i optimize-resource
-i overlay-buttons
-i patch-options
-i return-youtube-dislike
-i settings
-i sponsorblock
-i swipe-controls
-i theme

**Comment by sleepingiv** [comment] 2023-04-10 05:21
> I don't know what the issue is even though I watched the video
> (The circular animation shown when the buffer occurs also does not appear)
> 
> Please reopen the issue with additional information about what the symptom is and under what conditions the issue is reproducible.

Listen with sound, then you can understand the issue clearly

**Comment by madhurvarshney** [comment] 2023-04-10 05:24
Ahh...there is a little rewind after the segment is skipped.

**Comment by sleepingiv** [comment] 2023-04-10 15:01
> Ahh...there is a little rewind after the segment is skipped.

Yup , you got it. May inotia notices it and fixes this .

**Comment by inotia00** [comment] 2023-04-10 22:32
fixed in [revanced-patches-v2.168.30](https://github.com/inotia00/revanced-patches/releases/tag/v2.168.30)

**Closed by inotia00** 2023-04-10 22:32 UTC
Labels: bug
