### ISSUE TITLE
bug(YouTube/Video playback): Default video quality does not apply

### ISSUE THREAD

**Issue by Cast0r-999** [inotia00/ReVanced_Extended#2157] opened 2024-06-15 10:08 UTC
### Type

Error at runtime

### Tools used

RVX Manager

### Application

Youtube 19.21.40
Patch 4.9.2 dev.1
Noticed this on 4.8.6

### Bug description

Some videos randomly start on low resolution (360p/480p), even when my automatic set to 1080p. I don't know exact pattern or reason: maybe it's often when i continue video; maybe it's ~1/10 or ~1/20 frequency. 

### Solution

Reset resolution manually, which is obviously annoying. 

### Additional context

Any king of spoofing (playback, device, codec) is turned OFF.

### Device Environment

Android 10, MIUI 12.0.1, Global, Official, non-root. 

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by GucekPL** [comment] 2024-06-15 16:30
Same, it seems the `Default Video Quality` option is working randomly - I have set 1080 on Wi-Fi and mobile network, but the videos are starting between 360p and 720p

**Comment by inotia00** [comment] 2024-06-16 11:45
Google added delay for video quality changes in YouTube 18.39.41+. (server side)

Even if you change the video quality, there is a delay of 3 to 7 seconds to apply it.

This is the cause of the bug, and it is an issue that is reproduced not only in RVX but also in ReVanced.

Temporary workaround is as follows:
1. Patches YouTube 18.38.44 or earlier.
2. Use `Skip preload buffer` setting (Experimental Flag)

**Comment by Cast0r-999** [comment] 2024-06-27 08:23
Does Google 1-3 days ago changed something again with resolution mechanism ??? 
"Skip preload buffer" now doesn't help and some videos stuck at 480p, until i restart the app.

**Comment by GKid94** [comment] 2024-07-15 16:43
Still a issue
![Screenshot_2024-07-15-18-34-15-585_app rvx android youtube](https://github.com/user-attachments/assets/e46bf0bd-9507-40f2-9d82-fc994211518a)
![Screenshot_2024-07-15-18-39-32-876_app rvx android youtube](https://github.com/user-attachments/assets/ed98b52f-97a3-4ab0-8f7e-3369f9315a2c)
![Screenshot_2024-07-15-18-41-48-459_com miui securitycenter](https://github.com/user-attachments/assets/43f1055b-d986-4ded-bc6f-66b698bb4db3)

**Comment by CoolCooler0** [comment] 2024-07-15 17:05
Spoof Youtube version to 18.20.39 that fixed it for me. I had it on Revanced as well before moving to rvx.

**Comment by inotia00** [comment] 2024-07-15 18:34
As mentioned in the [comments,](https://github.com/inotia00/ReVanced_Extended/issues/2157#issuecomment-2171466598) it's a behavior of the new YouTube client, not a bug

**Comment by CoolCooler0** [comment] 2024-07-15 18:55
> As mentioned in the [comments,](https://github.com/inotia00/ReVanced_Extended/issues/2157#issuecomment-2171466598) it's a behavior of the new YouTube client, not a bug

I did read through it. I thought it will be a good idea to comment this. Maybe someone wants a quick "fix" until you release an update.

**Comment by inotia00** [comment] 2024-07-17 18:10
reflected in [revanced-patches-4.10.2](https://github.com/inotia00/revanced-patches/releases/tag/v4.10.2)

**Closed by inotia00** 2024-07-17 18:10 UTC
Labels: Bug report
