### ISSUE TITLE
suggestion: the share button should be removed from action buttons category 

### ISSUE THREAD

**Issue by sleepingiv** [inotia00/ReVanced_Extended#625] opened 2023-04-02 11:40 UTC
### Application

YouTube

### Issue

Share button is used by many unlike the other ones in that category, so it should be seperated.

### Patch

.

### Motivation

.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment] 2023-04-02 11:45
https://github.com/inotia00/ReVanced_Extended/issues/541 https://github.com/inotia00/ReVanced_Extended/issues/339
Because of these bugs, `Hide share button` has been merged into `Hide action buttons`

This bug is also reproduced in official ReVanced, and there are no plans to reflect this since there is no way to fix the bug other than integrating it.

**Closed by inotia00** 2023-04-02 11:45 UTC
Labels: patch-request
