### ISSUE TITLE
bug: Swipe controls doesn't work on recent version of patches

### ISSUE THREAD

**Issue by Faszom11** [inotia00/ReVanced_Extended#505] opened 2023-03-17 21:23 UTC
### Type

Error at runtime

### Application

Youtube version 18.10.36

### Bug description

After patching when you first open youtube it works just fine, when you setup your layout (e.g. enable/disable various features) and close the app, on reopening the swipe controls become buggy and won't work. (Screenshot of layout setup included below)

### Steps to reproduce

Open youtube, set up layout, open a video and swipe up / down.

### Relevant log output

```shell
No logs
```

### Screenshots or videos

![Screenshot_20230317_171827_YouTube RobEdition](https://user-images.githubusercontent.com/127752289/226055073-5e1d7bd8-6777-4d8d-bb45-3a8eeec0f35d.jpg)

https://user-images.githubusercontent.com/127752289/226055176-91e05a30-d2a2-4482-8159-4ddb83c93881.mp4

### Additional context

Selected patches:

Variant: nonRoot
Arch: arm64-v8a
App: YouTube-18-10.36.apk
CLI: inotia00-cli-v2.21.0.jar
Patches: inotia00-patches-v2.166.1.jar
Integrations: inotia00-integrations-v0.100.2.apk
Patches argument: -i custom-branding-icon-afn-red
-i custom-branding-name
-i custom-video-speed
-i default-video-quality
-i enable-external-browser
-i enable-minimized-playback
-i enable-old-quality-layout
-i enable-seekbar-tapping
-i force-premium-heading
-i hide-auto-captions
-i hide-auto-player-popup-panels
-i hide-channel-watermark
-i hide-email-address
-i hide-endscreen-cards
-i hide-general-ads
-i hide-info-cards
-i hide-mix-playlists
-i hide-player-button-background
-i hide-video-ads
-i microg-support
-i optimize-resource
-i overlay-buttons
-i patch-options
-i return-youtube-dislike
-i settings
-i sponsorblock
-i swipe-controls
-i theme

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment] 2023-03-17 22:12
it's weird..
because it works fine for me

Could you please export and upload the ReVanced settings json file?

**Comment by Faszom11** [comment] 2023-03-17 22:18
Yes sure, hiw can I upload the json file here? (Sorry, I'm a noob on github, just registered a couple day ago)

**Comment by Faszom11** [comment] 2023-03-17 22:31
Got it, just zipped it and now it let me add it as attachment.
[YouTube RobEdition_v18.10.36_2023-03-17.zip](https://github.com/inotia00/ReVanced_Extended/files/11006785/YouTube.RobEdition_v18.10.36_2023-03-17.zip)

**Comment by inotia00** [comment] 2023-03-17 22:34
great
In a little while I will proceed with patching in the same environment, do a clean install, and import these settings.

Then I'll check if the issue reproduces.

**Comment by Faszom11** [comment] 2023-03-17 22:35
Thank you for your work, you're the best!

**Comment by inotia00** [comment] 2023-03-17 22:46
ahh.. fortunately, the issue was reproduced with the json file you uploaded, and I found the cause

`hide-autoplay-preview` patch was the cause

Include the `hide-autoplay-preview` patch, and turn on the following settings:

Settings - ReVanced Settings - Fullscreen Layout - Hide autoplay preview

This issue will be fixed in the next releases

**Comment by inotia00** [comment] 2023-03-18 14:16
fixed in [revanced-patches-v2.166.4](https://github.com/inotia00/revanced-patches/releases/tag/v2.166.4)

**Closed by inotia00** 2023-03-18 14:16 UTC
Labels: bug
