### ISSUE TITLE
bug: `protobuf-spoof` patch causes always playing sound in search results

### ISSUE THREAD

**Issue by Tasin5541** [inotia00/ReVanced_Extended#480] opened 2023-03-14 13:40 UTC
### Type

Error at runtime

### Application

Youtube v.18.09.39

### Bug description

After searching something, the result screen plays the videos with sound. 

### Steps to reproduce

1. Have autoplay turned on
2. Search for something
3. Scroll to a video and let it autoplay 

### Relevant log output

```shell
No relevant logs
```

### Device Environment

Android 13, miui 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by JahidulOnFire** [comment] 2023-03-14 13:43
https://user-images.githubusercontent.com/115993964/225020118-c7d2a8d9-f0c1-4fbb-b22d-13f0ae636491.mp4

**Comment by inotia00** [comment] 2023-03-14 23:01
Exclude the `protobuf-spoof` patch until the issue is fixed

**Comment by inotia00** [comment] 2023-03-15 02:48
fixed in revanced-patches-v2.165.1

**Closed by inotia00** 2023-03-15 02:48 UTC
Labels: bug
