### ISSUE TITLE
bug: `Hide movies shelf` doesn't hide the movie shelf at the bottom of the player

### ISSUE THREAD

**Issue by MondayNitro** [inotia00/ReVanced_Extended#427] opened 2023-03-07 16:52 UTC
### Application

YouTube

### Issue

In some videos containing excerpts of movies, there is a movie description banner below the comments box. It would be great to have a patch that hides these. (The movie shelf patch doesnt hide these)
Check this video to get a better idea https://youtu.be/8WfRcnF4iZI

### Patch

![photo_6071310794500453071_y](https://user-images.githubusercontent.com/87489540/223491902-798e192b-2350-4271-9292-b002f970416b.jpg)

### Motivation

A clutter-free UI

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment] 2023-03-07 18:01
Already implemented (`General layout` > `Hide movies shelf`)

The default value is off to prevent loading errors in the home feed.
just change it to on

**Comment by inotia00** [comment] 2023-03-07 18:04
nah... this is a bug
As intended, `Hide movies shelf` option should hide this movie shelf

I will change the label of this issue to bug

**Comment by inotia00** [comment] 2023-03-09 00:49
fixed in [revanced-patches-v2.164.21](https://github.com/inotia00/revanced-patches/releases/tag/v2.164.21)

**Closed by inotia00** 2023-03-09 00:49 UTC
Labels: bug
