### ISSUE TITLE
bug: App crashes when "Hide shorts player pivobar" option is enabled

### ISSUE THREAD

**Issue by buiducanh142qn** [inotia00/ReVanced_Extended#492] opened 2023-03-15 11:24 UTC
### Type

Error at runtime

### Application

YouTube v18.09.39 (revanced-patches-2.165.1)

### Bug description

App crashes 1 time when "Hide Shorts player at app startup" option is disabled and "Hide Shorts player pivobar" is enabled.

### Steps to reproduce

When you set up the RVX Settings like this:
1. Disable "Hide shorts player at app startup".
2. Enable "Hide shorts player pivobar"
Then watch any short video and restart app, it will crash 1 time.

### Relevant log output

```shell
-
```

### Screenshots or videos

https://user-images.githubusercontent.com/54460494/225294626-3654b8d0-162e-4b9d-aa05-7f805a0d2618.mp4

![photo_2023-03-15_18-21-18](https://user-images.githubusercontent.com/54460494/225294639-9beef20d-5e0d-4fca-b72e-14f4bd659e7e.jpg)

### Device Environment

Redmi K20 Pro
Android 11, MIUI 12.5.6

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment] 2023-03-18 14:59
I found the cause of this issue

Patch to hide 'Paid Promotion' banner on shorts players causes crash
(The patch to hide the 'Paid Promotion' banner in the general player still works fine)

This patch is difficult to work with dynamically due to structural limitations, and often breaks.

So I decided to just drop the features that hide the 'Paid Promotion' banner on shorts players.

**Comment by inotia00** [comment] 2023-03-18 15:35
fixed in revanced-patches-v2.166.5

**Closed by inotia00** 2023-03-18 15:35 UTC
Labels: bug
