### ISSUE TITLE
bug(YouTube Music/Hide ads): `Hide fullscreen ads` setting also closes non-ad dialogs

### ISSUE THREAD

**Issue by soyDESKTOP68A2MRFT** [inotia00/ReVanced_Extended#1971] opened 2024-05-09 16:46 UTC
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YT music 6.51.52

### Bug description

When i try to create a playlist the create playlist dialog doesn't appear, and the playlist don't get created, it happens when i press save button and when i try to create it directly on library

### Error logs

```shell
I don't know how to get them
```

### Solution

Maybe using 6.50.53

### Additional context

NaN

### Device Environment

Android 12 One UI 5.1

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment] 2024-05-09 16:59
This is related to the `Hide fullscreen ads` setting.
just disable `Hide fullscreen ads` setting until the issue is resolved.

**Comment by inotia00** [comment] 2024-05-10 17:18
fixed in [revanced-patches-4.8.0-dev.4](https://github.com/inotia00/revanced-patches/releases/tag/v4.8.0-dev.4)

**Comment by soyDESKTOP68A2MRFT** [comment] 2024-05-10 17:28
Have you fixed that problem when creating playlists?, or is it from google
side?

**Comment by soyDESKTOP68A2MRFT** [comment] 2024-05-10 17:29
When i try to create a playlist the dialog disappears

**Comment by inotia00** [comment] 2024-05-10 17:34
Are you sure you patched with `revanced-patches-4.8.0-dev.4`?

**Comment by soyDESKTOP68A2MRFT** [comment] 2024-05-10 17:39
Is this problem in my reply resolved in this new release?

**Comment by soyDESKTOP68A2MRFT** [comment] 2024-05-10 17:40
I didn't

**Comment by soyDESKTOP68A2MRFT** [comment] 2024-05-10 17:40
But i will

**Comment by soyDESKTOP68A2MRFT** [comment] 2024-05-10 17:58
The playlist are working now, thanks

**Comment by inotia00** [comment] 2024-05-26 09:38
fixed in [revanced-patches-4.8.3](https://github.com/inotia00/revanced-patches/releases/tag/v4.8.3)

**Closed by inotia00** 2024-05-26 09:38 UTC
Labels: Bug report
