### ISSUE TITLE
suggestion(YouTube): make it not clickable

### ISSUE THREAD

**Issue by federicogith** [inotia00/ReVanced_Extended#2470] opened 2024-11-03 18:56 UTC
### Application

YouTube

### Suggestion description

Make it not clickable as it does nothing

https://github.com/user-attachments/assets/b7583ed7-c0dd-4697-a6b9-161e737d4ee8

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by federicogith** [comment] 2024-11-06 04:24
Sorry @inotia00, maybe I mis-labelled it
Shouldn't it be a bug?

**Comment by inotia00** [comment] 2024-11-06 15:01
This is not a bug

All Preferences are clickable by default - even if no click actions are assigned

![About](https://github.com/user-attachments/assets/a886469f-6401-4fd3-b062-279985f42b33)

As a prime example, the `App version` and `Company` in the `About` category in YouTube Settings are also clickable, but do not have any click actions assigned to them

**Closed** 2024-12-08 10:04 UTC
Labels: Suggestion
