### ISSUE TITLE
bug: clip button not work

### ISSUE THREAD

**Issue by Majeeed01** [inotia00/ReVanced_Extended#448] opened 2023-03-10 03:34 UTC
### Type

Error at runtime

### Application

YOUTUBE REVANCED 18.08.38

### Bug description

When I follow a clip, suddenly the clip stops working and the white circle appears and the clip does not work even though the original YouTube application does not have the same problem

### Steps to reproduce

.

### Relevant log output

```shell
.
```

### Device Environment

android 13 miui 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment] 2023-03-10 10:22
please attach screenshot

**Comment by inotia00** [comment] 2023-03-11 06:31
This is an issue that cannot be reproduced.

At least you should provide which patches you include or exclude.
or, you must attach logs or screenshots when the issue occurs

You didn't provide any additional information, and I'm closing the issue because it's not reproducible.

**Closed by inotia00** 2023-03-11 06:31 UTC
Labels: bug
