### ISSUE TITLE
bug(YouTube/Disable auto captions): turning on `Disable forced auto captions` will disable subtitles

### ISSUE THREAD

**Issue by KobeW50** [inotia00/ReVanced_Extended#2267] opened 2024-07-21 07:57 UTC
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YouTube 19.16.39

### Bug description

When playing some videos while the 'Disable forced auto captions' toggle is enabled, tapping the CC button does not enable captions. I can tap-and-hold the CC button to open the captions flyout menu, but even enabling captions in the menu has no effect. After closing the app, captions usually start working again.

https://github.com/user-attachments/assets/684729f1-dbec-481c-b428-b040ae1b2fca

**Steps to reproduce**

1. Patch and install YT 19.16.39 (I used default patches)

2. Enable the 'Disable forced auto captions' toggle in the ReVanced Extended settings.

3. Try enabling captions in several videos. You may need to restart the app a few times before the bug appears.

### Additional context

Sometimes the issue won't exist at all for an entire viewing session.

I have had this issue for several weeks now, and even existed after updating to to versions later than 19.16.39 when they were supported.

### Device Environment

Android 14, OneUI 6.1

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by KobeW50** [comment] 2024-07-22 01:47
After some testing, I believe I have narrowed down the issue to the 'Disable forced auto captions' toggle. Further testing is required since it is difficult to confirm that the issue ceases to exist *because* I disabled the toggle.

**Comment by KobeW50** [comment] 2024-07-23 15:56
After 2 days of only disabling the 'Disable forced auto captions' toggle and not having any issues since, I think it is fair to assume that the togfle causes the issue when enabled.

**Comment by inotia00** [comment] 2024-07-25 04:07
This issue does not reproduce on my side

Is this issue reproducible in ReVanced?

I haven't used ReVanced's code until now because the `Disable auto captions` patch in ReVanced had a bug that broke it in Shorts

Since this old bug has been fixed in the latest commit, it is now okay to merge ReVanced's code

**Comment by KobeW50** [comment] 2024-07-25 04:17
> Is this issue reproducible in official ReVanced?

Just tested on about 30 videos and the issue did not occur (It is also 19.16.39).

(Then I opened YT RVX, enabled the toggle, and the issue occured immediately)

**Comment by inotia00** [comment] 2024-07-27 08:56
reflected in [revanced-patches-4.10.3](https://github.com/inotia00/revanced-patches/releases/tag/v4.10.3)

**Closed by inotia00** 2024-07-27 08:56 UTC
Labels: Bug report
