### ISSUE TITLE
bug: hiding seekbar also hides seekbar color from the watch history page

### ISSUE THREAD

**Issue by BrilliantlyEducated** [inotia00/ReVanced_Extended#1013] opened 2023-05-12 03:39 UTC
### Type

Error at runtime

### Tools used

Revancify

### Application

YouTube v18.17.43

### Bug description

it hides the seekbar color under the videos

### Steps to reproduce

step 1. turn on hide seekbar
step 2. go to watch history

### Relevant log output

```shell
.
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment] 2023-05-12 05:25
not reproduced
Check that you have entered color codes in the correct format

**Comment by inotia00** [comment] 2023-05-12 05:36
I misunderstood the content of the issue
Issue is reproducible

This seems to be the intended part, so I won't fix it.

but I will edit the description of the hide seek bar patch later.

**Closed by inotia00** 2023-05-12 05:36 UTC
Labels: bug

**Comment by BrilliantlyEducated** [comment] 2023-05-12 09:37
> I misunderstood the content of the issue Issue is reproducible
> 
> This seems to be the intended part, so I won't fix it.
> 
> instead, I will edit the description of the hide seek bar patch later.

this is what i meant
![example(1)](https://github.com/inotia00/ReVanced_Extended/assets/36302515/aaf94de0-87b2-4931-92cf-0f2b64e04cea)

![example(2)](https://github.com/inotia00/ReVanced_Extended/assets/36302515/bbb16673-2f39-467f-b0c0-cc8bf5f7bda7)

it should be like this
![example(3)](https://github.com/inotia00/ReVanced_Extended/assets/36302515/b13d56b3-b8fb-49e2-b309-6bc0adb5bceb)

**Comment by inotia00** [comment] 2023-05-12 09:47
Yeah I understood that, but no plans to fix it

Instead, I would edit the description of `Hide seekbar` like this:
Hides the seekbar and the progress bar

**Comment by BrilliantlyEducated** [comment] 2023-05-13 10:01
> Yeah I understood that, but no plans to fix it
> 
> Instead, I would edit the description of `Hide seekbar` like this: Hides the seekbar and the progress bar

this only happens in v2.173.6 or v2.173.8 i'm not sure which version exactly

unanswered issues:

https://github.com/inotia00/ReVanced_Extended/issues/844

https://github.com/inotia00/ReVanced_Extended/issues/586

**Comment by inotia00** [comment] 2023-05-13 15:45
![chanelog](https://github.com/inotia00/ReVanced_Extended/assets/108592928/c85d8203-66ff-4231-8b1f-8bb2f994ca95)

That's the change in revanced-patches-v2.173.6

This is the result of applying the source code in the official ReVanced dev branch.
(intended part)

Users no longer have to change the progress bar color via options.json

Also, if you change hide seekbar to on, the progress bar is also hidden.

**Comment by inotia00** [comment] 2023-05-13 15:47
Also, I checked all patch-requests

patch-requests that are difficult to implement with current methods do not leave comments
