### ISSUE TITLE
bug(YouTube/Shorts components): `Hide Use this sound button` doesn't work

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#2356] opened 2024-09-01 02:49 UTC
### Type

Other

### Tools used

RVX Manager

### Application

YouTube v19.16.39
Patches v4.13.1-dev.2

### Bug description

https://github.com/user-attachments/assets/61ad435d-f255-417b-87e5-93bc02dde4f4

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I didn't use any settings marked as `Experimental Flags`.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment] 2024-09-01 02:53
This setting belongs to the PreferenceScreen `Shorts player`

That is, this setting hides the `Use this sound` banner in the Shorts player

https://github.com/inotia00/ReVanced_Extended/issues/2349

**Comment by Kuddus73** [comment] 2024-09-01 04:11
> That is, this setting hides the `Use this sound` button in the Shorts player #2349

I didn't know that there were two different buttons with the same name.

**Comment by Kuddus73** [comment] 2024-09-01 04:25
> That is, this setting hides the `Use this sound` button in the Shorts player #2349
> 
> The video you attached is not a button in the Shorts player

I didn't know that there were two different buttons with the same name.

**But still, the button is not hidden in all Shorts:**
![Screenshot_20240901_051455_YouTube](https://github.com/user-attachments/assets/ef4fcfc7-989d-4fb8-aa5d-c170c16bd5e9)

**Comment by Kuddus73** [comment] 2024-09-01 04:35
> That is, this setting hides the `Use this sound` button in the Shorts player #2349
> 
> The video you attached is not a button in the Shorts player

I didn't know that there were two different buttons with the same name.

**But still, the button is not hidden:**
![Screenshot_20240901_051455_YouTube](https://github.com/user-attachments/assets/ef4fcfc7-989d-4fb8-aa5d-c170c16bd5e9)

Perhaps it is another button with the same name again, but **this one is a button in the Shorts player.**

**Comment by inotia00** [comment] 2024-09-01 04:55
Are you sure you are using YouTube 19.16.39?
On my side, I don't see this button even when I open the same video

**Comment by Kuddus73** [comment] 2024-09-01 06:48
> Are you sure you are using YouTube 19.16.39?

Yes.

> I don't see this button even when I open the same video

https://github.com/user-attachments/assets/8672609b-2c9d-45fa-bea8-71e0faecc6f4

**Comment by Kuddus73** [comment] 2024-09-01 06:49
> Are you sure you are using YouTube 19.16.39?

Yes.

> I don't see this button even when I open the same video

Here:

https://github.com/user-attachments/assets/8672609b-2c9d-45fa-bea8-71e0faecc6f4

**Comment by inotia00** [comment] 2024-09-01 06:54
If so, there is a possibility of A/B tests

This is not reproducible on my side, so I will remove `Hide Use this sound button` setting in the next dev release
(Anyway this is valid issue)

**Comment by inotia00** [comment] 2024-09-01 07:26
Never mind, I can reproduce it on one of my Google accounts

https://github.com/user-attachments/assets/61ad435d-f255-417b-87e5-93bc02dde4f4

This will be added as a `Hide floating button` setting
(Since this setting can hide other floating buttons besides `Use this sound`)

https://github.com/user-attachments/assets/8672609b-2c9d-45fa-bea8-71e0faecc6f4

This will be integrated into the `Hide Use this sound button` setting

**Comment by inotia00** [comment] 2024-09-01 13:32
reflected in [revanced-patches-4.13.1-dev.3](https://github.com/inotia00/revanced-patches/releases/tag/v4.13.1-dev.3)

**Closed by inotia00** 2024-09-01 13:32 UTC
Labels: Bug report
