### ISSUE TITLE
feat(patch): Adding a search feature within the app

### ISSUE THREAD

**Issue by quangkiet2025** [inotia00/ReVanced_Extended#952] opened 2023-05-04 14:58 UTC
### Application

YouTube

### Issue

I have noticed that there are increasingly more options for customization in the Revanced Extended app, and while they have been categorized, there are still too many options within each category for me.

### Patch

I suggest that a search feature be added in the upcoming patch release, similar to what is already available in the rvx-builder app.

### Motivation

I think this would make it easier for some people, including myself, to find the features to customize in the app.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Metallifani666** [comment] 2023-05-04 15:05
Duplicate of #83 

@inotia00 You can close this one.

**Closed** 2023-05-04 15:07 UTC
Labels: patch-request
