### ISSUE TITLE
Bug: button containers still visible when turned off

### ISSUE THREAD

**Issue by ayushTNM** [inotia00/ReVanced_Extended#339] opened 2023-02-25 17:09 UTC
### Type

Error while patching

### Application

YouTube 18.07.35 with patches 2.164.5

### Bug description

Even if the button containers are off, some buttons are still visible. Only the like, dislike and download buttons seem to be working and can be hidden.

### Steps to reproduce

1. Go to other layout settings in revanced extended settings
2. Hide all buttons in "Hide button containers component" settings
3. Check which button containers are hidden and which aren't

### Relevant log output

```shell
N/A
```

### Screenshots or videos

https://user-images.githubusercontent.com/78740080/221370118-2756b1ae-4861-4e5b-8c8d-8f1484715951.mp4

### Device Environment

Android 13, stock

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by ILoveOpenSourceApplications** [comment] 2023-02-25 18:20
Can you also list all the patches that you've included?

**Comment by ayushTNM** [comment] 2023-02-25 19:16
"client-spoof",
        "custom-branding-icon-afn-red",
        "custom-seekbar-color",
        "default-video-quality",
        "enable-external-browser",
        "enable-minimized-playback",
        "enable-old-quality-layout",
        "enable-open-links-directly",
        "force-premium-heading",
        "force-vp9-codec",
        "header-switch",
        "hide-button-container",
        "hide-channel-watermark",
        "hide-collapse-button",
        "hide-comment-component",
        "hide-create-button",
        "hide-crowdfunding-box",
        "hide-endscreen-cards",
        "hide-fullscreen-buttoncontainer",
        "hide-general-ads",
        "hide-info-cards",
        "hide-mix-playlists",
        "hide-pip-notification",
        "hide-player-button-background",
        "hide-snackbar",
        "hide-stories",
        "hide-suggested-actions",
        "hide-tooltip-content",
        "hide-video-ads",
        "materialyou",
        "optimize-resource",
        "overlay-buttons",
        "patch-options",
        "return-youtube-dislike",
        "settings",
        "sponsorblock",
        "theme"

**Comment by inotia00** [comment] 2023-02-25 19:48
This issue cannot be reproduced.
It could be A/B testing, or there may be other causes.

Once this issue is reproducible I will fix it then.

**Comment by ayushTNM** [comment] 2023-02-25 22:23
It also seems that it chooses random button containers from the selected ones to hide everytime a video gets openend (even if it's the same video)

**Comment by ayushTNM** [comment] 2023-02-25 22:36
It also seems that it chooses random button containers from the selected ones to hide everytime a video gets openend (even if it's the same video)

![Screenshot_20230225-233526.png](https://user-images.githubusercontent.com/78740080/221382712-6c1f1e59-74a4-4a88-a4b8-5d6b192d7348.png)

This also happens from time to time

**Comment by inotia00** [comment] 2023-02-27 16:01
Check if it reproduces in revanced-patches-v2.164.9

**Comment by ayushTNM** [comment] 2023-02-27 16:19
Still reproduces.

**Comment by ILoveOpenSourceApplications** [comment] 2023-02-27 16:49
> Still reproduces on 18.08.34 with patches 2.164.9.

Can you try with minimal patches and see if it still exists, starting with just hide button containers, given that you're a rooted user.

**Comment by ayushTNM** [comment] 2023-02-27 17:09
Not a rooted user sadly, but the issue still persists with just "microg-support" and "Hide button containers" enabled

**Comment by ILoveOpenSourceApplications** [comment] 2023-02-27 17:19
> Not a rooted user sadly, but the issue still persists with just "microg-support" and "Hide button containers" enabled

I didn't see microg in the patch list you shared, so I assumed that you're a rooted user. Given that with just two of the patches you're still facing the issue, I believe it's due to the A/B testing from Google's side. Like inotia00 said you'll have to wait for it to get fixed.

**Comment by inotia00** [comment] 2023-03-09 12:04
No longer reproducible in latest release

**Comment by ayushTNM** [comment] 2023-03-09 12:23
Still reproduces on my end with yt 18.09.37 no root with all patches

**Comment by inotia00** [comment] 2023-03-09 12:35
hmm.. I completely rebased the patch structure, it doesn't reproduce, at least to me
But if it still persists, I will reopen

**Comment by manishloshali** [comment] 2023-03-21 03:35
Happening to me on 18.10.37 (patch 2.166.8) 

https://imgur.com/a/emK97b1

**Comment by ayushTNM** [comment] 2023-03-22 01:39
Seems to be working on my end now (18.10.37, patch 2.166.8)

**Comment by inotia00** [comment] 2023-03-22 02:57
Fixed by reflecting the official ReVanced code
(revanced-patches-v2.166.10)

Following the official ReVanced's code, the settings below have been removed:
- `Hide clip button`
- `Hide create short button`
- `Hide live chat button`
- `Hide report button`
- `Hide thanks button`

Instead, some settings have been merged into the settings below:
- `Hide action buttons`

**Closed by inotia00** 2023-03-22 02:57 UTC
Labels: bug

**Comment by MondayNitro** [comment] 2023-03-22 15:48
even in latest patches 2.166.10 and version 18.10.37, none of the clip, thanks, remix button get hidden

**Comment by MondayNitro** [comment] 2023-03-22 15:50
different videos have different buttons under them, remix button in all, while clip, thanks buttons are hidden in some while viible in others.

**Comment by manishloshali** [comment] 2023-03-22 15:55
I am having the same issue. [Sometimes ](https://imgur.com/a/f9s18jF)the buttons are just weird. 
Everything worked fine in patch v2.166.5

**Comment by manishloshali** [comment] 2023-03-22 16:03
Wait did you disable the new setting. Its commbined now and enabled by default

**Comment by MondayNitro** [comment] 2023-03-22 16:04
i dont know, if i hide every button, everything gets hidden, but if i try hiding some buttons, all are visible

**Comment by manishloshali** [comment] 2023-03-22 16:06
in the latest 2.166.10 update, under Bottom player layout its now 'Hide create. clip and thanks button'

**Comment by MondayNitro** [comment] 2023-03-22 16:08
> in the latest 2.166.10 update, under Bottom player layout its now 'Hide create. clip and thanks button'

yes but it doesnt work, it doesnt hide those buttons for me
