### ISSUE TITLE
feat(YouTube Music/Player components): add `Hide audio video switch toggle` setting

### ISSUE THREAD

**Issue by bean-factory** [inotia00/ReVanced_Extended#2009] opened 2024-05-14 03:32 UTC
### Application

YouTube Music

### Feature description

Add option to hide the song/video switcher at the top of the player in the YouTube Music app. I think it may already be possible to do this through a custom filter but i was not able to find any discussion in this direction.

![Screenshot_20240510_113025_YouTube Music (Medium)](https://github.com/anddea/revanced-patches/assets/76696071/6ebcd0f9-9d9d-4b85-aa73-224bf7a4e0ae)

### Motivation

A lot of songs dont even have a music video to go with them so the picker is pretty much useless and just clutters up the ui without providing any real functionality.

### Acknowledgements

- [X] This is not a feature request for YouTube.
- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment] 2024-05-15 18:19
reflected in [revanced-patches-4.8.0-dev.6](https://github.com/inotia00/revanced-patches/releases/tag/v4.8.0-dev.6)

**Comment by bean-factory** [comment] 2024-05-16 03:59
Tried the dev patches, seems to work great. Should I close this now?

**Comment by inotia00** [comment] 2024-05-16 04:19
The issue is still open because it has only been released to the `dev` branch and not merged into the `main` branch.
I will close the issue when it is merged into the `main` branch.

**Comment by inotia00** [comment] 2024-05-26 09:38
reflected in [revanced-patches-4.8.3](https://github.com/inotia00/revanced-patches/releases/tag/v4.8.3)

**Closed by inotia00** 2024-05-26 09:38 UTC
Labels: Feature request
