### ISSUE TITLE
bug(protobuf-spoof): Unbale to download videos in offline.

### ISSUE THREAD

**Issue by mrahmadmukhtar** [inotia00/ReVanced_Extended#788] opened 2023-04-20 00:35 UTC
### Type

Other

### Application

YouTube 18.14.41

### Bug description

Issue 1: Stopped Downloading
When attempting to download a video or playlist in offline using ReVanced, the download stops after downloading a certain percentage. Even when attempting to resume the download, it still says "downloading" but doesn't actually continue downloading. I'm talking about internal downloading in Revanced.

Issue 2: Audio Continues Playing
Sometimes, when playing a video on ReVanced and then closing the application, the audio from the video continues playing in the background. Even if the user quits the application or force stops ReVanced, the audio continues to play and the only solution is to restart the device.

### Steps to reproduce

Step 1: Fix download issue 

### Relevant log output

```shell
Didn't found or maybe not important
```

### Screenshots or videos

![IMG_20230420_053218](https://user-images.githubusercontent.com/115221450/233227550-9cb713ee-2f36-427d-a32f-6dd6b49a7447.jpg)

### Device Environment

MIUI 12.5
Based on Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Frog20707** [comment] 2023-04-22 20:03
И как решить проблему?

**Comment by inotia00** [comment] 2023-04-22 20:18
It is impossible to fix because it is an issue that is not reproducible to me

It works fine on my device

**Comment by mrahmadmukhtar** [comment] 2023-04-23 06:02
I'm still facing the issue. There is no solution yet.

**Comment by mrahmadmukhtar** [comment] 2023-04-23 06:03
Not only me, many guys are having the same problem. I'm using YouTube
vanced to download stuffs. And using Revanced to watch online.

**Comment by inotia00** [comment] 2023-08-05 00:07
since it is no longer spoofing with shorts player parameters in latest patches, closing the issue

**Closed by inotia00** 2023-08-05 00:07 UTC
Labels: bug
