### ISSUE TITLE
bug: correct/modify spaces in overlay buttons patch

### ISSUE THREAD

**Issue by MondayNitro** [inotia00/ReVanced_Extended#1520] opened 2023-10-12 17:50 UTC
### Type

Cosmetic

### Tools used

ReVanced Manager

### Application

youtube 18.25.40

### Bug description

i began using overlay buttons patch for ytdlnis yesterday and i saw that the contents above the seekbar shift towards the seekbar if you patch using overlay buttons patch, due to which the vertical space between seekbar and overlay buttons, fullscreen buttons. timestamps etc. gets reduced. to top it off, my device screen is small (5 in) which leads to accidentally tapping seekbar instead of overlay buttons.
i request you to keep the vertical space like it is when you dont include overlay buttons patch, so users with devices having low screen size dont tap the seekbar accidentally

### Steps to reproduce

compare rvx apks patched with and without overlay buttons patch to see the difference.

### Relevant log output

```shell
none
```

### Screenshots or videos

![photo_6142941357120010975_w](https://github.com/inotia00/ReVanced_Extended/assets/87489540/2bc551c4-6a8d-47e0-af01-bcf164b26f00)
![photo_6142941357120010974_w](https://github.com/inotia00/ReVanced_Extended/assets/87489540/821d3085-46d1-49d1-af90-65e41e4f52d5)

### Device Environment

LOS20

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by MondayNitro** [comment] 2023-10-12 17:51
also, would you consider thinning the overlay buttons a bit, because they look thicker than the fullscreen button

**Comment by inotia00** [comment] 2023-10-12 17:57
First of all this is not a bug

Someone pointed out that the height of the overlay button and the timestamp are different, so I just unified them.

If [this patch](https://github.com/inotia00/ReVanced_Extended/issues/1434) is introduced as a PR and merged, I think it will solve what you want.

**Closed by inotia00** 2023-10-12 17:57 UTC
Labels: bug
