### ISSUE TITLE
bug: 400 server problem

### ISSUE THREAD

**Issue by OjanGoslingk** [inotia00/ReVanced_Extended#2507] opened 2024-11-27 04:53 UTC
### Type

Error while patching

### Tools used

RVX Manager

### Application

19.25.39

### Bug description

cannot open any video

### Error logs

```shell
400 server
```

### Solution

-

### Additional context

-

### Device Environment

Android 13 One Ui 5

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [ ] This issue is not a duplicate of an existing bug report.
- [X] I didn't use any settings marked as `Experimental Flags`.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by KobeW50** [comment] 2024-11-27 05:06
Duplicate of https://github.com/inotia00/ReVanced_Extended/issues/2499

**Closed** 2024-11-27 08:32 UTC
Labels: Bug report
