### ISSUE TITLE
bug(YouTube/Minimized playback): buffer symbol showing up instead of play button 

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [inotia00/ReVanced_Extended#1482] opened 2023-10-04 13:39 UTC
### Type

Error at runtime

### Tools used

ReVanced Manager

### Application

YouTube v18.33.40

### Bug description

When pausing the video and letting YouTube run in the background and later coming back instead of showing the play button the user is welcomed by a buffering symbol. If the user taps on the buffer icon, the video will start playing and if it user doesn't do that they can stare at the buffer symbol.

### Steps to reproduce

1) Play any video and pause it.
2) Leave the app and let it run in the background.
3) Open YT again and see how a buffer symbol appears.
4) If tapped on, the video will play normally.

### Relevant log output

```shell
Nil
```

### Screenshots or videos

https://www.veed.io/view/34de0dad-60fc-45ec-9a46-07730c8e75da?sharingWidget=true&panel=

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by ILoveOpenSourceApplications** [comment] 2023-10-04 14:26
Strange. I tried doing a clean install as well but that didn't change anything. I haven't tried an older version to see if it's a version issue or not. These are the patches that I use:
![Screenshot_20231004-195240~2](https://github.com/inotia00/ReVanced_Extended/assets/117499019/157452d4-675a-4b9d-b090-a13b47c64597)

**Comment by inotia00** [comment] 2023-10-05 17:05
It seems to be reproduced very rarely on my side
Most likely, the Spoof player parameter patch is the cause

**Comment by ILoveOpenSourceApplications** [comment] 2023-10-05 20:26
I am able to reproduce this bug all the time. I tried turning off Spoof parameter in settings and tried the above steps and still the buffer icon was showing up. Can't try without the spoof parameter patch as it's integrated with MicroG, but like I said I did try by turning it off and still got the same results.

**Comment by inotia00** [comment] 2023-10-06 02:01
Would you try excluding the Minimized playback patch?

**Comment by ILoveOpenSourceApplications** [comment] 2023-10-06 05:49
Yes. Patching without Minimized Playback and repeating the above steps didn't reproduce the issue.

**Comment by inotia00** [comment] 2023-10-06 15:59
In [revanced-patches-v2.190.24](https://github.com/inotia00/revanced-patches/releases/tag/v2.190.24), the implementation method of `Minimized playback` patch has been slightly changed

I can't confirm if this issue has been resolved, as it only reproduces very rarely in my side

Please re-patch with revanced-patches-v2.190.24 and check if the issue reproduces

**Comment by ILoveOpenSourceApplications** [comment] 2023-10-06 17:29
Nope. It's still the same.

**Comment by inotia00** [comment] 2023-10-06 17:59
Can you pinpoint which version this issue starts occurring?

I have not been notified of this issue in the minimum version supported by the patch (v18.22.37)

**Comment by ILoveOpenSourceApplications** [comment] 2023-10-06 18:12
Okay somehow it's gone now and I don't know whether it'll be back or not. Here's what I did. I patched without minimized playback patch, when into incognito, tried to see if the issue is there or not. It's not. Went back and patched again but this time with minimized playback. Opened the app and I was still in incognito mode, left incognito and played the last video from history. And all of a sudden the issue is gone. Not sure if it's similar to your situation and I'll now start seeing it rarely or if it's actually fixed.

**Comment by sleepingiv** [comment] 2023-10-06 18:22
> Can you pinpoint which version this issue starts occurring?
> 
> I have not been notified of this issue in the minimum version supported by the patch (v18.22.37)

This issue persists for my case . 

I'm using 18.35.36 for a long time as all the patches used by me patch fine (Be it REX or RVX).

**Comment by ILoveOpenSourceApplications** [comment] 2023-10-06 18:23
Welp, It's back.

**Comment by inotia00** [comment] 2023-10-06 18:23
I don't think it's a patch issue

Maybe it's Google's new A/B test

**Comment by inotia00** [comment] 2023-10-06 18:28
Here are the characteristics of A/B testing:

1. It does not occur when the app is first installed, but occurs over time.
2. The issue does not appear on lower versions of YouTube.
3. The higher the version of YouTube, the easier it is to reproduce the issue.
(More likely to be targeted for A/B testing)
4. The issue does not occur normally, but it may occur in secret mode or on other accounts.

**Comment by inotia00** [comment] 2023-10-06 18:32
Since most A/B tests rely on the server side, a spoofed app version can handle most of them.

Sometimes, A/B tests are affected by the absolute version of the app.

Please check as the problem persists in YouTube v18.27.36.

As Google updated YouTube v18.27.36 to v18.29.38, there was a lot of code added on the client side.

**Comment by jojobozo** [comment] 2023-10-06 18:46
> Since most A/B tests rely on the server side, a spoofed app version can handle most of them.
> 
> Sometimes, A/B tests are affected by the absolute version of the app.
> 
> Please check as the issue persists in YouTube v18.27.36.
> 
> As Google updated YouTube v18.27.36 to v18.29.38, there was a lot of code added on the client side.

The playback doesn't work me for at all since this update

**Comment by inotia00** [comment] 2023-10-06 18:58
> > Since most A/B tests rely on the server side, a spoofed app version can handle most of them.
> > Sometimes, A/B tests are affected by the absolute version of the app.
> > Please check as the issue persists in YouTube v18.27.36.
> > As Google updated YouTube v18.27.36 to v18.29.38, there was a lot of code added on the client side.
> 
> The playback doesn't work me for at all since this update

This is an off-topic issue.
Reset all patch environments and try patching again.

If the issue still persists, open a new issue.

**Comment by jojobozo** [comment] 2023-10-06 19:13
> > > Since most A/B tests rely on the server side, a spoofed app version can handle most of them.
> > > Sometimes, A/B tests are affected by the absolute version of the app.
> > > Please check as the issue persists in YouTube v18.27.36.
> > > As Google updated YouTube v18.27.36 to v18.29.38, there was a lot of code added on the client side.
> > 
> > 
> > The playback doesn't work me for at all since this update
> 
> This is an off-topic issue. Reset all patch environments and try patching again.
> 
> If the issue still persists, open a new issue.

Fixed, thanks

**Comment by ILoveOpenSourceApplications** [comment] 2023-10-06 23:19
Looks like there's a chance that it could be an A/B testing as when I spoofed the app version to whatever the default one was, the issue seems to have stopped happening.

**Comment by ILoveOpenSourceApplications** [comment] 2023-10-13 19:26
Just a follow up, v18.20. & below seems to remove the buffer symbol and everything afterwards brings it back.

**Comment by inotia00** [comment] 2023-11-21 00:49
fixed in [revanced-patches-v2.199.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.199.1)

**Closed by inotia00** 2023-11-21 00:49 UTC
Labels: Bug report, A/B test
