### ISSUE TITLE
Hide Chapter Teaser under videos in the feed does not work

### ISSUE THREAD

**Issue by BadhuL** [inotia00/ReVanced_Extended#303] opened 2023-02-22 04:11 UTC
### Type

Error at runtime

### Application

Youtube 18.05.40

### Bug description

Im on rooted android 10. Had no problems in previous version patches. 

### Steps to reproduce

Patch with  these options enabled
![Screenshot_2023-02-22-09-39-52-281](https://user-images.githubusercontent.com/70265776/220519760-5b76c764-2e59-4c9f-a88a-0b4aa8020763.jpeg)

### Relevant log output

```shell
I don't know how to get one
```

### Screenshots or videos

![Screenshot_2023-02-22-09-24-25-682](https://user-images.githubusercontent.com/70265776/220518625-5f3de097-a135-4f83-954f-28d4201cd53a.jpeg)
![Screenshot_2023-02-22-09-26-46-775](https://user-images.githubusercontent.com/70265776/220518670-ecad7709-0724-400e-8a1a-7bb7ca8d12eb.jpeg)

### Device Environment

Android 10, Lenovo  TB 8505F

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment] 2023-02-22 16:06
fixed in [revanced-patches-v2.163.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.163.1)

**Comment by ILoveOpenSourceApplications** [comment] 2023-02-26 18:07
@inotia00 this needs to be reopened again.

**Comment by inotia00** [comment] 2023-02-27 15:35
Since this issue doesn't reproduce on my device, I can't fix it.
If this issue is fixed sometime, please close the issue then.

**Comment by ILoveOpenSourceApplications** [comment] 2023-02-27 16:22
You can close this again since after the latest patches version 2.164.8, once again the issue went away on its own. I have explained some other stuff related to this in #351 if you can check into it @inotia00.

**Comment by ILoveOpenSourceApplications** [comment] 2023-03-01 04:17
Or @BadhuL you can close this also.

**Comment by inotia00** [comment] 2023-03-01 05:06
thanks

**Closed by inotia00** 2023-03-01 05:06 UTC
Labels: bug
