### ISSUE TITLE
feat(patch): Play Next in Queue and Merge All Youtube Premium Features patches

### ISSUE THREAD

**Issue by Stale-1** [inotia00/ReVanced_Extended#1095] opened 2023-07-08 06:21 UTC
### Application

YouTube

### Issue

The Youtube Premium "Play Next in Queue" is not usable and requires premium subscription. 

### Patch

1) Add "Play Next in Queue"
2) Merge the Following Patches into "Get Youtube Premium Features"
* Minimized Background Play
* Force Premium Heading
* Hide General Ads
* Hide Video Ads
* Play Next in Queue

### Motivation

1) Get the Full Experience of having Youtube Premium because the new features is displays but not usable.
2) All of the Patches stated above are Features of Youtube Premium so it is easier to just combine them into one patch. Just like when the "Hide Get Premium" patch get merged into another patch. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment] 2023-07-08 06:43
ReVanced Extended does not unlock premium features

It only provides features similar to those present in Chrome Extensions

It is also a duplicate of the following issue https://github.com/inotia00/ReVanced_Extended/issues/1046

**Closed by inotia00** 2023-07-08 06:43 UTC
Labels: patch-request
