### ISSUE TITLE
bug: cant play a vid

### ISSUE THREAD

**Issue by CreedGo** [inotia00/ReVanced_Extended#2512] opened 2024-11-28 17:39 UTC
### Type

Other

### Tools used

RVX Manager

### Application

Revanced extended

### Bug description

![Screenshot_20241128_193837_ReVanced Extended](https://github.com/user-attachments/assets/aba789bf-62b6-4eab-b90a-403a1fbbd7cf)
pls fix this

### Device Environment

Android14 oneui 6.1

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [ ] This issue is not a duplicate of an existing bug report.
- [X] I did not use any settings marked as `Experimental Flags`.
- [ ] I have patched the APK according to the [documentation](https://github.com/inotia00/revanced-documentation#readme).
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment] 2024-11-28 22:24
Duplicate of https://github.com/inotia00/ReVanced_Extended/issues/2499

**Closed by inotia00** 2024-11-28 22:24 UTC
Labels: Bug report
