### ISSUE TITLE
bug: <title>RVX default video quality 

### ISSUE THREAD

**Issue by pathania07** [inotia00/ReVanced_Extended#1689] opened 2023-11-14 04:18 UTC
### Type

Other

### Tools used

RVX Manager

### Application

18.43.45

### Bug description

First I wants to thank inotia00 for RVX.

I have set the RVX video on wifi to 1440p on wifi and 360p on mobile network but when the video is not in 1440p. It automatically changes to 480p  or 720p instead of going to 1080p. 

### Steps to reproduce

1. Set the default video quality in RVX settings to 1440p and data quality in 360p
2. On videos where there is no support for 1440p videos it will go down to 480p or 720p

### Relevant log output

```shell
N/A
```

### Device Environment

Android 13,ColorOS 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by KobeW50** [comment] 2023-11-14 04:57
Likely a duplicate of https://github.com/inotia00/ReVanced_Extended/issues/321

**Closed** 2023-11-14 09:14 UTC
Labels: bug

**Comment by AlpenMeister** [comment] 2023-11-14 09:16
This is not a duplicate. The problem is that when there is no video quality available in the RVX video setting you put in (example 1440p) YouTube will automaticity play 480p video.  When there is a video with 1440p available it will play 1440p.

So there must be a fix defaulting video quality to the highest available on a video when the input of RVX can not be met. Than instead defaulting to 480p quality.

**Comment by inotia00** [comment] 2023-11-14 09:18
Even though this issue is not a duplicate, I have no plans to fix it.

If it's really important to you, use a different YouTube client than RVX.

**Comment by pathania07** [comment] 2023-11-14 10:38
RVX is still best for me so I ain't switching.
Well if you don't plan to fix it. There's nothing I can do.

**Comment by inotia00** [comment] 2023-11-20 07:23
RVX is open source, so anyone can modify the source code.

Open the PR after modifying the code to your liking.

**Comment by Aryan-Chauhan** [comment] 2023-11-23 06:17
Solution found for video quality not locking problem.

Clean-install v18.36.39

This version has no problem with quality locking + it has You tab (for people who want to solve their problem but also don't want to lose You tab).
