### ISSUE TITLE
bug(YouTube/Spoof streaming data): Spoofing does not work with `iOS`

### ISSUE THREAD

**Issue by ArcherLegend** [inotia00/ReVanced_Extended#2508] opened 2024-11-27 07:20 UTC
### Type

Error at runtime

### Tools used

rvx-builder

### Application

Youtube 19.16.39

### Bug description

Youtube has always played videos in their native language and if more than 1 audio track was available it was possible to change it via the track selection option in the player settings.

I have used Youtube 19.16.39 with the latest patches to date (4.16.1) since they came out and the track selection option has always been there, however since yesterday I am getting AI translated audio in non English speaking videos and all of a sudden the audio track selection option has gone missing (I have read that Youtube is pushing out AI translated audio so that may be the culprit?).

I am attaching a .txt file with the settings I am currently using.

[Revanced Extended options.txt](https://github.com/user-attachments/files/17930455/Revanced.Extended.options.txt)

### Device Environment

Galaxy S10+ SM-G975F Android 10

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I didn't use any settings marked as `Experimental Flags`.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment] 2024-11-28 08:20
It seems impossible to fetch streaming data from iOS clients now

(Same issue is also opened in [yt-dlp](https://github.com/yt-dlp/yt-dlp/issues/11640)

**Comment by Adity1243** [comment] 2024-11-28 08:25
So what is the cause the coockie ?

**Comment by ArcherLegend** [comment] 2024-11-28 08:26
> It seems impossible to fetch streaming data from iOS clients now
> 
> (Same issue is also opened in [yt-dlp](https://github.com/yt-dlp/yt-dlp/issues/11640))

That might explain it. I wanted to add that yesterday evening I had a closer look at the issue on my end and I noticed that in nerd starts the spoofed client was said to be Android VR despite the settings calling for iOS (and nerd stats always showed iOS as the spoofed client till the issue started to occur 1.5 days ago).

Is it possible for you to have a workaround for that in a future patch? These AI audio renders RVX unusable at the moment in the affected videos.

**Comment by Adity1243** [comment] 2024-11-28 08:39
> > It seems impossible to fetch streaming data from iOS clients now
> > (Same issue is also opened in [yt-dlp](https://github.com/yt-dlp/yt-dlp/issues/11640))
> 
> That might explain it. I wanted to add that yesterday evening I had a closer look at the issue on my end and I noticed that in nerd starts the spoofed client was said to be Android VR despite the settings calling for iOS (and nerd stats always showed iOS as the spoofed client till the issue started to occur 1.5 days ago).
> 
> Is it possible for you to have a workaround for that in a future patch? These AI audio renders RVX unusable at the moment in the affected videos.


I think its partially spoofing to ios client or maybe bug in state or nerds, A/B test , when i spoof to ios client i fell boost in sound which is stable volume function does but the state of nerds shows it spoofed to android VR and vp9 codec, but when i was on ios client my device renders AV1 codec before issue

**Comment by Gt2307** [comment] 2024-11-29 11:16
SAME PROBLEM
Please fix this

**Comment by inotia00** [comment] 2024-12-08 10:01
fixed in [revanced-patches-5.0.1](https://github.com/inotia00/revanced-patches/releases/tag/v5.0.1)

**Closed by inotia00** 2024-12-08 10:01 UTC
Labels: Bug report
