### ISSUE TITLE
bug: <title>player controller bug

### ISSUE THREAD

**Issue by Aditya646754** [inotia00/ReVanced_Extended#785] opened 2023-04-19 20:33 UTC
### Type

Error at runtime

### Application

YouTube Revanced Extended v18.14.41

### Bug description

Sometime video Player controller get stuck while playing video and can't vanish.

### Steps to reproduce

Step1 :- open YouTube 
Step2 :- play video

### Relevant log output

```shell
.
```

### Screenshots or videos

Screen record Google drive link:-
https://drive.google.com/file/d/13jSypPg0S8fOdetP5w2Zp_42xDkhJVmG/view?usp=drivesdk

### Device Environment

Android 12,miui 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment] 2023-04-19 21:14
This is an old YouTube bug, not a bug in ReVanced Extended

If you do a Google search for the keyword 'YouTube player button not dispearing', you'll see how old this issue has been.

This issue needs to be fixed by Google, so there is nothing I can do about it.

If you just run into this bug, force close ReVanced Extended

issue will be resolved

**Closed by inotia00** 2023-04-19 21:14 UTC
Labels: bug

**Comment by Aditya646754** [comment] 2023-04-20 14:46
I will report to official youtube
