### ISSUE TITLE
bug: `hide-mix-playlists` also hides history on the library tab

### ISSUE THREAD

**Issue by Evergard** [inotia00/ReVanced_Extended#507] opened 2023-03-18 06:24 UTC
### Type

Cosmetic

### Application

• YouTube v18.10.36
• Patch v2.166.1
• ReVanced Manager v0.0.57

### Bug description

Enabling `hide-mix-playlist` also hides the history panel on library

### Steps to reproduce

1. Enable `hide-mix-playlists`

### Relevant log output

```shell
N/A
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment] 2023-03-18 08:01
can you attach screenshot?

**Comment by Evergard** [comment] 2023-03-19 02:02
> This issue is not reproducible even in the tablet UI, old layout, and A/B test layout
> 
> Can you attach screenshot?

That's odd... I can't reproduce it either. I had no history for days and that was the solution for me.

**Comment by inotia00** [comment] 2023-03-19 02:24
That's weird.. since it doesn't reproduce anymore, I'll close the issue

**Closed by inotia00** 2023-03-19 02:24 UTC
Labels: bug, question
