### ISSUE TITLE
bug(YouTube/Hide feed components): `Hide expandable chip under videos` setting does not work

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#2173] opened 2024-06-20 14:37 UTC
### Type

Other

### Tools used

RVX Manager

### Application

YouTube v19.25.39

### Bug description

![Screenshot_20240620_152920_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/127908708/584b5edb-4457-4ef8-aab4-03219a9d844a)
![Screenshot_20240620_153007_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/127908708/17b6925c-0036-47bb-b87f-19b3b218edad)

### Solution

Rollback to YouTube 19.16.39

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by zerozero0022** [comment] 2024-06-20 17:26
Enable 'Hide expandable chip under videos'

**Comment by Kuddus73** [comment] 2024-06-20 19:10
> Enable 'Hide expandable chip under videos'

It's already enabled 🙄.

**Comment by inotia00** [comment] 2024-06-23 11:59
may fixed in [revanced-patches-4.9.2](https://github.com/inotia00/revanced-patches/releases/tag/v4.9.2), but I'm not sure
(It may be a layout that I haven't found yet)

**Comment by inotia00** [comment] 2024-07-17 18:12
In [revanced-patches-4.10.2](https://github.com/inotia00/revanced-patches/releases/tag/v4.10.2), the supported version has been rolled back to YouTube 19.16.39.
This bug is only reproducible on YouTube 19.20.xx+, so the issue is closed.

**Closed by inotia00** 2024-07-17 18:12 UTC
Labels: Bug report, A/B test
