### ISSUE TITLE
bug: Sponsor block skipping not working properly in background mode

### ISSUE THREAD

**Issue by rikinp93** [inotia00/ReVanced_Extended#524] opened 2023-03-20 15:55 UTC
### Type

Error while patching

### Application

YouTube v18.10.37

### Bug description

Same as issue: https://github.com/revanced/revanced-patches/issues/1761

Sponsorblock skipping when in background playback mode not working correctly. It doesn't skip in correct places on the videos, sometimes not even skipping.

When the app is open, not in background mode, skips are working correctly.

All sponsorblock settings are skip automatically.

Previous version 17.49.37 works fine.

### Steps to reproduce

Steps included in the comments of https://github.com/revanced/revanced-patches/issues/1761

### Relevant log output

```shell
-
```

### Solution

Solution for a fix created in https://github.com/revanced/revanced-patches/issues/1761
https://github.com/revanced/revanced-patches/pull/1765

### Device Environment

Android 13 beta 3 pixel 7 pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment] 2023-03-20 22:25
Unfortunately this issue is not reproducible

Unlike the official ReVanced, ReVanced Extended already has a PR for a fix reflected in it.

Also, sponsorblock segment submission is not skipped for other PlayerTypes including shorts.

**Comment by rikinp93** [comment] 2023-03-21 05:01
It is definitely happening for me on revanced extended as well. Weird

**Comment by rikinp93** [comment] 2023-03-29 17:38
Seems fixed now on revanced version https://github.com/revanced/revanced-patches/issues/1765

This fixed it

**Comment by inotia00** [comment] 2023-03-29 23:12
Can you test it on the latest Extended?

Because this commit is already applied to Extended..

**Comment by inotia00** [comment] 2023-04-02 10:26
fixed in [revanced-patches-v2.168.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.168.1)

**Closed by inotia00** 2023-04-02 10:26 UTC
Labels: bug
