### ISSUE TITLE
bug: cannot swipe down while video open

### ISSUE THREAD

**Issue by anyujinie** [inotia00/ReVanced_Extended#213] opened 2023-02-04 19:37 UTC
### Type

Error at runtime

### Application

Version 18.02.37

### Bug description

Recently I cannot swipe down. Please see attached videoclip.

### Steps to reproduce

Open Video
Try swiping down
I don't know if it happens to you too 

### Screenshots or videos

https://user-images.githubusercontent.com/73917917/216786474-d815aca2-7577-4bc5-8419-3863046e4728.mp4

### Device Environment

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment] 2023-02-05 02:42
It's a bug in the old layout
Please check if the bug reproduces in the new layout as well.

**Comment by anyujinie** [comment] 2023-02-05 02:47
> It's a bug in the old layout
> Please check if the bug reproduces in the new layout as well.

My account _still_ didn't receive the new layout. Nothing I can do except wait for global rollout ...

**Comment by inotia00** [comment] 2023-02-05 02:52
Follow the method below
1. Force close ReVanced Extended
2. Remove app data of ReVanced Extended
3. Launch ReVanced Extended, and do not log in to your Google account
4. Force close ReVanced Extended
5. Launch ReVanced Extended, and check if the new layout is applied

**Comment by anyujinie** [comment] 2023-02-05 02:55
Oh believe me I tried all those various methods of forcing the new UI. Every time usually after a few hours maybe 1 day I end up seeing the old layout reinstated. It's useless trying to force show it.

**Comment by inotia00** [comment] 2023-02-05 02:58
then.. i have no idea
All patches are written based on the new layout, so I cannot provide help for bugs that occur in the old layout..

**Comment by anyujinie** [comment] 2023-02-05 03:08
Gotchu. Thx for trying to help. I didn't know this bug only occurs with old layout, or the fact that the patches are written for new layout. Seems Rvx and old layout is a problematic combination now.
Guess I will have to wait for google to finally roll it out to all users and for new layout to hit my acc. 
God knows how many more weeks, months it will take to hit my Premium acc...

**Comment by rks2000** [comment] 2023-02-05 15:46
Using different Google account may help you getting the new layout.

**Comment by anyujinie** [comment] 2023-02-05 15:47
> Using different Google account may help you getting the new layout.

I don't want to use different acc. All my stuff is in my main account including proper suggestions lol.

**Comment by ILoveOpenSourceApplications** [comment] 2023-02-25 15:51
So this also can be closed since it's related to the old layout right?

**Comment by anyujinie** [comment] 2023-03-06 23:26
@inotia00 
I didn't want to open a new bug report, since this one exists. But as you can see this is even happening with the new layout. I can't scroll down to related videos. It's stuck:

https://streamable.com/sw5mor

**Comment by anyujinie** [comment] 2023-03-11 13:48
> Does the issue still persist in the latest release?

@inotia00 Still persists in latest version 18.09.37 cannot swipe down to related videos:
https://streamable.com/orov9c

**Comment by anyujinie** [comment] 2023-03-16 20:34
@inotia00 This bug is happening way too often. It's really annoying. Can we try to troubleshoot and try reproduce and fix it please?🙏🏻

**Comment by anyujinie** [comment] 2023-03-16 23:21
> At least it is not reproduced in my device, so I can't fix
> 
> If someone can reproduce this issue, debugging, and anyone who can reflect it in the source code, please leave a PR

I have an idea. Can I send you a backup of my rvx settings which you could apply on your end? And test it that way? Sounds good?

**Comment by anyujinie** [comment] 2023-03-16 23:39
Ok... Damn it just happens way too often lately that it doesn't let me scroll down to related videos...
And then there's this other extremely annoying, triggering bug "resource exhausted" which doesn't let me subscribe to channels, unless I try tapping the subscribe button 10-15 times..
It's fucked...

**Comment by anyujinie** [comment] 2023-03-17 06:36
@inotia00 https://mega.nz/file/uZFEUZQS#pLlsTTuh-wOPNm4uAaJKXLZOFP8hfa2JnK7K2kNje3Q

This is backup of my rvx settings. Using recommended version 18.09.39. Please try to apply on your end if you get to it. Might be able to reproduce it, in the case the bug is related to my settings. Yes we don't know that. But atleast we can try.

**Comment by inotia00** [comment] 2023-03-17 06:46
Even though I imported the settings, it still doesn't reproduce

**Comment by anyujinie** [comment] 2023-03-17 06:47
> Even though I imported the settings, it still doesn't reproduce

You have to give it time and use it for atleast a few days please. Just to make sure.

**Comment by inotia00** [comment] 2023-03-17 06:53
Unfortunately, not reproducible

It is recommended to exclude patches one by one until your issue disappears.

Then find out which patch is causing this issue and leave a comment.

**Comment by anyujinie** [comment] 2023-03-17 06:54
> Unfortunately, not reproducible
> 
> It is recommended to exclude patches one by one until your issue disappears.
> 
> Then find out which patch is causing this issue and leave a comment.

Omg this is causing me frustration and headaches 😭😭

**Comment by inotia00** [comment] 2023-03-17 06:56
Because I can't reproduce the issue in any way on my side.
(Also no one reported this issue other than you)

If this issue bothers you enough, you should spend your time trying to figure out which patch is causing the issue.

**Comment by cuynu** [comment] 2023-03-17 13:22
Bug in original YouTube

**Comment by cuynu** [comment] 2023-03-17 13:27
that problem usually occurs when watching videos in portrait mode for more than 1 hour, but it doesn't always appear after 1 hour, it can happen earlier or later. If it does, the error will persist until reopen YouTube

**Comment by inotia00** [comment] 2023-03-17 14:22
If so.. I'll close the issue

**Closed by inotia00** 2023-03-17 14:23 UTC
Labels: bug

**Comment by anyujinie** [comment] 2023-03-17 14:25
> If so.. I'll close the issue

Uhm.. Closing the issue on what grounds? Two people claiming it's a stock YouTube bug without providing any evidence whatsoever to work with??
Sometimes I use stock YouTube and this swipe bug never happens. Please reopen the issue.

**Comment by inotia00** [comment] 2023-03-17 14:29
If the issue is reproducible on unpatched YouTube, then this is a YouTube issue.

No matter how much I search my source code, there is no part that touches scrolling while watching.

If you think this is an rvx issue, exclude patches until the issue is reproduced.

For example, exclude all patches and include only settings patch and microg patch.

And test if the issue reproduces

**Comment by inotia00** [comment] 2023-03-17 14:30
I can't seem to reproduce it on my side, and I've hardly seen anyone reporting this issue.

Closed the issue because someone said the issue could be reproduced on unpatched YouTube as well.

Find out exactly which patch is causing the issue, then reopen the issue.
