### ISSUE TITLE
bug(YouTube/Video playback): default video quality applies even when video is playing

### ISSUE THREAD

**Issue by Adity1243** [inotia00/ReVanced_Extended#1959] opened 2024-05-09 08:12 UTC
### Type

Error at runtime

### Tools used

Revancify

### Application

Youtube

### Bug description

There is bug in rvx that if you change video quality while playing video the quality change to already set default quality in setting automatically after some time.

### Device Environment

Android 12, miui 14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment] 2024-05-09 10:47
There is not enough explanation of the issue.
Please attach procedures for reproducing the issue. (and attach screenshot)

**Comment by Adity1243** [comment] 2024-05-09 16:49
Steps to reproduce :-
1)Set 1440p value in revanced extended default video quality setting
2)play any video change video quality to 1080p it will affect only for 3 to 5 mins after that it will set to 1440p automatically.

**Comment by Adity1243** [comment] 2024-05-09 16:53
Strange its not happening now.

**Comment by inotia00** [comment] 2024-05-09 17:14
The explanation is still a little unclear.

1. `Remember video quality changes` setting is turned off.
2. `Default video quality` is 1440p.
3. When the video starts, the video quality starts at 1440p.
4. Change the video quality to 1080p.
5. Sometimes the video quality returns to 1440p.

Is this accurate?

**Comment by Adity1243** [comment] 2024-05-09 17:23
> The explanation is still a little unclear.
> 
> 1. `Remember video quality changes` setting is turned off.
> 2. `Default video quality` is 1440p.
> 3. When the video starts, the video quality is set to 1440p.
> 4. Change the video quality to 1080p.
> 5. Sometimes the video quality returns to 1440p.
> 
> Is this accurate?

Correct and when i try to reproduce it it wont happening and it sometime happen. And when it set to 1440p automatically  the continuous buffering comes video wont play.

**Comment by Adity1243** [comment] 2024-05-09 17:24
> 
![Screenshot_2024-05-09-22-52-40-884_app premium android youtube](https://github.com/inotia00/ReVanced_Extended/assets/131557644/563d3d9e-398e-46cb-967c-e319a356315f)

**Comment by inotia00** [comment] 2024-05-09 17:28
This issue doesn't seem to be reproducible on my side.

**Comment by Adity1243** [comment] 2024-05-09 17:50
Yes when i try to reproduce it wont happening but when i play video randomly it happening.

**Comment by Mohammed1520** [comment] 2024-05-09 20:50
I confirm that I can reproduce it on my side
This is Video illustrates the issue .. I can't upload it through GitHub because of its size

https://drive.google.com/file/d/1upI2zJpVDtblgnS6Tbzi22dIuBiyoM25/view?usp=drivesdk

**Comment by inotia00** [comment] 2024-05-10 17:18
fixed in [revanced-patches-4.8.0-dev.4](https://github.com/inotia00/revanced-patches/releases/tag/v4.8.0-dev.4)

**Comment by Mohammed1520** [comment] 2024-05-10 17:55
I think the old way is better.
For example 
Now if the wifi quality is set to be 720 and mobile data is set to be 240 
If you have turned wifi off and switched to Mobile data while video is playing the quality is still set as 720 and doesn't change to 144. You have to wait for some minutes to have 144 or you must close video and reopen it again

**Comment by Mohammed1520** [comment] 2024-05-10 17:56
In old way 
If the wifi is turned off and mobile data is turned on while video is playing
The quality automatically changes at the same moment without any delay
I think this is better than the new way introduced in dev.4

**Comment by inotia00** [comment] 2024-05-10 18:02
The method applied in `revanced-patches-4.8.0-dev.4` is similar to the method used by the ReVanced Team.

`Default video quality` refers to the video quality that is set `when the video starts`, so the current behavior is closest to the definition of the word.

**Comment by Mohammedibrahim15** [comment] 2024-05-12 11:37
This method has a problem 
For example 
My wifi default quality is 1880
My Mobile data default quality is 240
1- Play video with 1880 on wifi which is the default quality 
2- close the video and re open it again using mobile data at this time . You will get video playing at 1880 *same as wifi*
3- Try to close video again and again you will get video playing with 720p sometimes. Or 480 at other times 
You will never get it played at 240 unless you close video many times or change the quality manually to 240
The vice versa also occurs when you play video with mobile data and want to shift to wifi. The quality doesn't change automatically. You need to close video and reopen it or it may change by luck some times

**Comment by Mohammed1520** [comment] 2024-05-20 20:59
Hi @anddea
I have tried your patches that referenced this issue 
But it haven't been solved yet

**Comment by Mohammed1520** [comment] 2024-05-21 04:02
Thanks for your explanation 🙏

**Comment by inotia00** [comment] 2024-05-26 09:37
fixed in [revanced-patches-4.8.3](https://github.com/inotia00/revanced-patches/releases/tag/v4.8.3)

**Closed by inotia00** 2024-05-26 09:37 UTC
Labels: Bug report
