### ISSUE TITLE
bug: 1440p+ quality not supported

### ISSUE THREAD

**Issue by Adity1243** [inotia00/ReVanced_Extended#975] opened 2023-05-06 18:34 UTC
### Type

Error while patching

### Tools used

ReVanced Manager

### Application

YouTube revanced extended 18.16.39

### Bug description

The 1440p resolution is missing in videos when I was able to play that video in 1440p in old update. But I enabled HDR videos in my settings.

### Steps to reproduce

Play video
Choose video quality

### Relevant log output

```shell
.
```

### Device Environment

Miui 14,android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by Adity1243** [comment] 2023-05-06 18:49
Only 1440p HDR videos I was able to play but normal 1440p 60 not showing in video quality list, I downgraded YouTube revanced extended to v18.15.40 which is working fine. Please fix it.

**Comment by Adity1243** [comment] 2023-05-06 18:56
![Screenshot_2023-05-07-00-00-08-218_app rvx android youtube](https://user-images.githubusercontent.com/131557644/236641837-07eab496-f86c-408c-9bf5-fe975341f0de.jpg)

Revanced extended v18.16.39

**Comment by Adity1243** [comment] 2023-05-06 18:57
![Screenshot_2023-05-07-00-25-04-974_app rvx android youtube](https://user-images.githubusercontent.com/131557644/236641858-0c1c4a06-4bbd-4354-aba1-78e535a4b5f3.jpg)

Same video played on revanced extended v18.15.40

**Comment by inotia00** [comment] 2023-05-06 19:51
Check if the issue reproduces on unpatched YouTube v18.16.39

**Comment by Hennadz** [comment] 2023-05-06 22:15
Even this works
https://github.com/inotia00/revanced-patches/releases/tag/v2.173.2

![Screenshot_20230507-010704_EnTube](https://user-images.githubusercontent.com/130844239/236648501-93185550-da04-4e08-94fa-2b8f5b58275e.png)

**Comment by Metallifani666** [comment] 2023-05-06 22:45
I actually have an issue with this aswell, I watched the same video, my results:

Patches: 2.173.2
YouTube: 18.16.39

HDR enabled: hdr enabled (144p60 hdr -> 2160p60 hdr)
HDR disabled: hdr disabled (144p hdr -> 1080p60 hdr)

With hdr disabled I get max 1080 quality and hdr is enabled in 720p and 1080p qualities.

**Comment by inotia00** [comment] 2023-05-07 03:14
Try enabling VP9 codec
And check if the issue is resolved

then try disabling it again
And check if the issue is resolved

**Comment by Metallifani666** [comment] 2023-05-07 06:43
Disabling VP9 codec didn't fix it, also tried to use new layout for video quality selection, but no vail.

Ubpatched YouTube shows hdr in all qualities.

**Comment by Metallifani666** [comment] 2023-05-07 14:24
Doing some testing.

VP9 codec disabled, HDR disabled, video quality set to auto. I'm getting hdr in all qualities (144p -> 2160p60).

VP9 codec enabled, HDR disabled, video quality set to auto. I'm getting hdr in all qualities (144p -> 1080p60)

**Comment by Metallifani666** [comment] 2023-05-07 15:54
Further testing:

I watched 4K hdr video now instead of 2K.

VP9 enabled, HDR enabled, not getting hdr option (quality 144p -> 1080p)
VP9 disabled, HDR enabled, not getting hdr option (144p -> 2160p)

Something doesn't seem right, hdr seems to be always on in 2K videos, and always off in 4K videos.

**Comment by odkrys** [comment] 2023-05-08 09:05
This issue appears to occur when the device does not support HDR.
I have this problem only on my xiaomi mipad 4.

**Comment by Metallifani666** [comment] 2023-05-08 13:06
@odkrys 

HDR has some issue because on my end it's stuck on, when disabled I'm still getting hdr in videos, somehow setting up default video quality to auto broke it completely.

**Comment by odkrys** [comment] 2023-05-08 13:18
I don't have such a problem, but what I can think of is that if you are using a device that supports the av1 codec (s23 or some dimensity devices), the problem occurs somewhere between vp9 hdr and av1 hdr.

It would be nice to post a stats for nerds capture.

**Comment by Metallifani666** [comment] 2023-05-08 13:25
What was the setting to get stats for nerds menu visible again? I enabled the setting but I believe I need to enable something else too to get the menu visible.

**Comment by odkrys** [comment] 2023-05-08 13:29
settings - general - enable stats for nerds

Play the hdr video and press the top right button.

**Comment by odkrys** [comment] 2023-05-08 13:35
It's not in the extended setting, it's in YouTube's settings.

**Comment by Metallifani666** [comment] 2023-05-08 13:40
Ahh yes, silly me :D

HDR enabled:

![Screenshot_20230508_163756_ReVanced Extended](https://user-images.githubusercontent.com/131755431/236839171-495f5f59-d437-43ae-b2db-ca605af189aa.jpg)

HDR disabled:

![Screenshot_20230508_163848_ReVanced Extended](https://user-images.githubusercontent.com/131755431/236839258-3675e77d-1a15-41cc-aa53-9cf2122dbe1d.jpg)

**Comment by Metallifani666** [comment] 2023-05-08 13:48
And it my case when hdr is disabled I get max 1080p in vertical and horizontal.

**Comment by Metallifani666** [comment] 2023-05-08 13:57
VP9 disabled and HDR disabled, and I'm getting 2160p60 hdr.

**Comment by odkrys** [comment] 2023-05-08 14:05
VP9 codec disabled, HDR disabled, video quality set to auto. I'm getting hdr in all qualities (144p -> 2160p60).
VP9 codec enabled, HDR disabled, video quality set to auto. I'm getting hdr in all qualities (144p -> 1080p60).

Like you said, its number 1 bug. It appears that the patch only blocks the vp9 hdr and still loads the av1 hdr.

If you enable "enable vp9 codec" option, you will get a 2nd bug that will limit landscape video to 1080p.
This limits even non-hdr vidoes to 1080p.

**Comment by Metallifani666** [comment] 2023-05-08 14:06
That explains my issue, thank you.

**Comment by odkrys** [comment] 2023-05-08 14:08
Oh, then the 3rd bug is added.
It uses av1 codec even though you have "enable vp9 codec" option turned on.

**Comment by Metallifani666** [comment] 2023-05-08 14:09
Ohh yeah, it sure does.

**Comment by odkrys** [comment] 2023-05-08 14:10
This is probably because the option is for very old devices that do not support the vp9 codec and only support the h264 codec.
That's why devices with av1 have additional problem.

**Comment by Adity1243** [comment] 2023-05-08 15:16
At my case :-
Disabling force vp9 codec solves this problem but video still runs on vp9 codec.

Enabling force vp9 codec video plays on 1080p 60 max, but I can play 1440p HDR video, doesn't matter HDR setting is disabled.

Disabling HDR playback and disabling force vp9 codec affect same no difference as 1st condition I said.

The official YouTube doesn't have any problem of 1440p playback issue, I checked.

**Comment by odkrys** [comment] 2023-05-08 15:50
Oh I checked again.
"enable vp9 codec" restricts only VP9 SDR horizontal videos to 1080p. This is a confirmed bug in that option.

horizontal VP9 SDR = 1080p
horizontal VP9 HDR = 2160p
vertical VP9 SDR = 2160p 
vertical VP9 HDR = 2160p

horizontal AV1 ? = 1080P

@Metallifani666 Please check if the option limits 1080p to both SDR and HDR of the horizontal video of the av1 codec.

**Comment by Metallifani666** [comment] 2023-05-08 16:01
Vertical VP9 enabled: 2160 hdr
Horizontal VP9 enabled: 2160 hdr

Horizontal VP9 disabled: 2160 hdr
Vertical VP9 disabled: 2160 hdr

**Comment by Metallifani666** [comment] 2023-05-08 16:06
But in my case hdr is always on because of av1 isn't it? So how do I test it?

**Comment by odkrys** [comment] 2023-05-08 16:07
Play any non-hdr video.

**Comment by Metallifani666** [comment] 2023-05-08 16:10
Ahh lmfao!

VP9 disabled horizontal: 2160
VP9 disabled vertical: 2160

VP9 enabled horizontal: 1080
VP9 enabldd vertical: 1080

**Comment by Adity1243** [comment] 2023-05-08 16:18
I tried with portrait mode too its still same 1080p 60 no difference when enabled force vp9 codec. and idk my device supports av1 codec but it support avc1 and vp9 as default, so I don't think that setting should be problem for me and I can play 1440p max as default system capability.
If I choose 2160p it automatically sets 480p and video quality settings get buged 480p max until I didn't restart youtube again.

**Comment by odkrys** [comment] 2023-05-08 16:19
First you guys need to understand the "enable vp9 codec" option. About 10 days ago, the option to lift resolution restrictions (lift-vertical-video-restriction) was merged into that option.

https://github.com/inotia00/revanced-integrations/commit/2851061b114dc126211a26bfdf76da24d234ff8c

First of all, it seems clear that there is a bug in that option that limits the resolution to 1080p.
Matches the title of this issue.

Additionally, there is a bug in the disable-hdr patch that still loads the av1 hdr. This will be confirmed by the developer. I think it would be good to open the issues individually.

**Comment by odkrys** [comment] 2023-05-08 16:27
```
If I choose 2160p it automatically sets 480p and video quality settings get buged 480p max until I didn't restart youtube again.
```
"lift-vertical-video-restriction" option unlocks device resolution limitations.
If your device can only play 1440p, it is normal to get 480p when 2160p is selected.
The device is refusing to play 2160p.

**Comment by Metallifani666** [comment] 2023-05-08 16:34
Well you could've just put it that way in the first place without being an asshole.

There is always a good way and a bad way to say stuff, don't forget that.

**Comment by odkrys** [comment] 2023-05-08 16:40
Look again at the body of the person who opened the issue and your first comment. It only says that the HDR option is enabled, nowhere does it say that the "enable-vp9" option is enabled.

That led me to misunderstand that the "disable-hdr" option creates a resolution limit. I just confirmed this.

**Comment by Metallifani666** [comment] 2023-05-08 16:43
So I can't even comment on anything anymore? I get flagged instantly.

So be it, you can go fuck yourself. I'm out

**Comment by odkrys** [comment] 2023-05-08 16:49
well.
Anyway thanks to your time, I found out that there is a bug where the "disable-hdr" patch doesn't disable av1 hdr.
This is something the developer would not have known if there were no users on devices that supported the av1 codec. Perhaps the developer will read this thread and fix that bug too.

**Comment by inotia00** [comment] 2023-07-05 14:23
Please proceed with the patch in the following environment and let me know if the issue reproduces

YouTube v18.20.39
revanced-patches-2.181.1

**Comment by Adity1243** [comment] 2023-07-05 16:24
I did but i didnt getting youtube revanced extended setting i only getting general youtube revanced settings

**Comment by Adity1243** [comment] 2023-07-06 06:31
> Please proceed with the patch in the following environment and let me know if the issue reproduces
> 
> YouTube v18.20.39 revanced-patches-2.181.1

Yes,i cheaked about this issue in youtube extended, i didnt face this issue now. It got fixed.you can close this issue now.

Youtube revanced extended - v18.25.39
Revanced-patches - v2.181.4
Revanced CLI  - v2.21.6

**Closed** 2023-07-06 06:57 UTC
Labels: bug
