### ISSUE TITLE
bug (YouTube/`Hide ads`): Hide fullscreen ads doesn't allow opening community post images

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [inotia00/ReVanced_Extended#2017] opened 2024-05-14 12:30 UTC
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YouTube v19.16.39

### Bug description

Apparently youtube changed the way where if a community post wasn't of square resolution the user had to tap on the image to view the full image. Now instead it opens similar to how a fullscreen ad opens, and thus the patch doesn't allow opening the image to view the entire image.

### Solution

Probably if they plan to go ahead with this method (which sucks), community posts somehow will have to be whitelisted from the fullscreen ads patch or change the method of viewing the image to how it was.

Hopefully they'll revert back to the old ways and this can be closed without any patch or changes.

### Additional context

There's a chance that this is an A/B test and this may be reverted back, but since I noticed it, I decided to report it here.

A similar report:
https://www.reddit.com/r/youtube/comments/199hhwo/change_to_community_post_pictures_mobile/

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment] 2024-05-14 16:52
Please attach a screenshot of when the image in the community post is normally opened in fullscreen.
I didn't find any difference.

**Comment by ILoveOpenSourceApplications** [comment] 2024-05-14 17:07
Here.
<details><summary>Screenshots</summary>
<p>

How the preview looks:
![Screenshot_20240514_223324_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/117499019/9b9b5a83-1b7c-428d-beae-5da243865f37)

How it opens in incognito:
![Screenshot_20240514_223327_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/117499019/a7326112-66e5-4b63-8822-48321aa0d142)

How it opens when signed in:
![Screenshot_20240514_223341_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/117499019/237d56ae-e90c-4eeb-ba98-28021d53e7d0)


</p>
</details>

**Comment by ILoveOpenSourceApplications** [comment] 2024-05-15 15:36
*An update*: Mine reverted back to the old one. So it's definitely A/B testing. Hopefully it stays that way.

**Comment by inotia00** [comment] 2024-05-15 18:40
Some people may still be having issues with these A/B tests, so I'll keep this issue open.

Like the issue https://github.com/inotia00/ReVanced_Extended/issues/1820, I will close the issue once enough time has passed.

**Comment by inotia00** [comment] 2024-06-10 17:59
This issue is still reproduced to some users.

Therefore, I try to solve this issue by adding `Close fullscreen ads` setting.

1. If the `Close fullscreen ads` setting is turned on
: Click the `Close` button to close the fullscreen ads.
Fullscreen ad are exposed for about 0.5 seconds, but there is no side effect because it is closed only when the fullscreen ads are detected.

2. If the `Close fullscreen ads` setting is turned off
: The same method is used as before.
Always block the dialog without checking the fullscreen dialog in detail.
There is also a side effect that the community post image on the fullscreen is also closed. (A/B testing)

**Comment by ILoveOpenSourceApplications** [comment] 2024-06-10 18:46
YouTube briefly displayed the new layout for opening images in community posts, but then switched back to the old one when I reopened the app.

**Comment by inotia00** [comment] 2024-06-10 19:31
reflected in [revanced-patches-4.9.1-dev.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.9.1-dev.1)

**Comment by inotia00** [comment] 2024-06-12 15:41
reflected in [revanced-patches-4.9.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.9.1)

FYI: Hidden, but still left empty space

**Closed by inotia00** 2024-06-12 15:41 UTC
Labels: Bug report, A/B test

**Comment by inotia00** [comment] 2024-09-15 03:05
So far, we have not been able to identify whether the fullscreen dialog is an image of a community post or a fullscreen ad.

So, the `Close fullscreen ads` setting was added.

This issue can now be reproduced on my account as well.

Now we can identify whether fullscreen dialog is an image of a community post or not.

So I think it's okay to remove the `Close fullscreen ads` setting.

Since we no longer need the [toast](https://github.com/inotia00/ReVanced_Extended/issues/2167) for debugging, it will also be removed.
