### ISSUE TITLE
bug: Clips of shorts overlap each other

### ISSUE THREAD

**Issue by iBasim** [inotia00/ReVanced_Extended#543] opened 2023-03-23 11:58 UTC
### Type

Error at runtime

### Application

v2.166.8
YouTube v18.10.37

### Bug description

Clips of shorts overlap each other.

In other words, when playing short clips in a continuous manner, the problem appears after a certain number of clips. Part of the clip is played and moves on its own to the other clip.

### Steps to reproduce

1 Watch a number of short clips
2 Sometimes, after watching the number of clips, two clips overlap with each other without any control from me to move to the other clip

### Relevant log output

```shell
nothing
```

### Screenshots or videos

https://user-images.githubusercontent.com/57762287/227198483-2f1a87f6-0eee-487e-a98f-e427c8339080.mp4

_No response_

### Solution

I've been using version v18.05.40 v2.160.1 of YouTube ReVanced Extended for about a month and I've never had this problem.
Two days ago, I did a clean install of YouTube v18.10.37 v2.166.8  and i did notice this problem.

### Device Environment

android 10

### Acknowledgements

- [x] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment] 2023-03-23 13:10
hide shorts pivotbar
disable QUIC protocol
protobuf-spoof
sponsorblock

These are the patches that are presumed to be the cause of the issue.

Try disabling the above settings and test if the issue reproduces.
(It is not reproduced in my side)

**Comment by iBasim** [comment] 2023-03-23 14:06
hide shorts pivotbar
The only one that has been Enabled, I will disabling it and give you results

**Comment by iBasim** [comment] 2023-03-23 19:19
Even after disabling hide shorts pivotbar , the problem persists. I will try new version YouTube v18.11.35-v2.166.12 and give you the result later.

**Comment by iBasim** [comment] 2023-05-05 13:44
Since the latest Patches versions, I haven't noticed the problem, so I don't know if it was solved by inotia00 or YouTube developers.

**Comment by inotia00** [comment] 2023-05-05 13:48
Presumably, it was a YouTube server side issue.
Anyway, I'm closing the issue as it doesn't reproduce anymore

**Closed by inotia00** 2023-05-05 13:48 UTC
Labels: bug
