### ISSUE TITLE
App force closes when selecting video quality

### ISSUE THREAD

**Issue by Frank810803** [inotia00/ReVanced_Extended#1430] opened 2023-09-27 05:06 UTC
### Type

Other

### Tools used

rvx-builder

### Application

YouTube 18.31.40

### Bug description

After several attempts to clean install , and patched the latest YouTube app that it's supported (18.31.40) , it wasn't able to get rid of the bug that forces the app to close and crash when I'm selecting the resolution.

I just , uninstalled it, and transfer to my phone a previous patched version of YouTube(18.30.37) and now the app behaves like it should.

### Steps to reproduce

It's random, it can be in portrait or landscape mode , whenever I open the settings to set the quality of the video it's crashes.

### Relevant log output

```shell
I don't have a log output.
```

### Device Environment

Android 9 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment] 2023-09-27 13:02
Try spoofing to v18.20.39
Then turn off spoofing

Check if the issue reproduces

Since it does not reproduce on my side, logcat containing error is required

**Comment by inotia00** [comment] 2023-09-27 13:03
Also, it is not possible to identify which patch is causing the crash.

Check if the issue is reproduced when you exclude all patches and include only the `default-video-quality` patch and the `microg-support` patch

**Comment by girshcatt** [comment] 2023-09-27 13:05
I will try, but in fact i saw many messages about this in rvx group, much people facing this

**Comment by inotia00** [comment] 2023-09-27 13:13
anyway, attaching a crash log is the fastest way to detect and resolve the cause of the issue

I checked the group chat, but no one posted an error log

**Comment by Frank810803** [comment] 2023-09-27 20:39
> anyway, attaching a crash log is the fastest way to detect and resolve the cause of the issue
> 
> I checked the group chat, but no one posted an error log

Please tell me how do I log this issue , and I will try to upload it asap , and I will only patch the resolution and microG ,thanks

**Comment by Frank810803** [comment] 2023-09-27 23:30
> Also, it is not possible to identify which patch is causing the crash.
> 
> Check if the issue is reproduced when you exclude all patches and include only the `default-video-quality` patch and the `microg-support` patch

i just patched YT version 18.31.40 with only those 2 patches and its doesnt force close. maybe its something else, just point me into the right direction on how to export a crash log and ill upload it.

**Comment by Frank810803** [comment] 2023-09-28 00:58
Update

I just patched version 18.30.37 , with the latest ones and I have the same bug, it closes when selecting the resolution.

**Comment by inotia00** [comment] 2023-09-28 01:46
1. Connect the device to the PC
2. USB debugging should be turned on in developer options
3. Open cmd on your PC and type the following:
```
adb logcat *:E > logcat.txt
```
4. Reproduce the crash process in this state
5. Stop recording logcat by typing `Ctrl + C` in cmd.
6. Attach the generated `logcat.txt`

**Comment by Frank810803** [comment] 2023-09-28 02:12
her is the logcat 
[logcat.txt](https://github.com/inotia00/ReVanced_Extended/files/12744839/logcat.txt)

**Comment by inotia00** [comment] 2023-09-28 02:28
Thank you for attaching the logcat.

Thanks to this, I can guess what causes the crash.

I can't guarantee that it will be completely fixed because it is not reproduced on my side, but I will try to fix it in the next release.

**Comment by inotia00** [comment] 2023-09-28 02:32
One more thing, if your time allows, exclude only the `enable-old-quality-layout` patch and try the patch.

I guess that's the cause

**Comment by Frank810803** [comment] 2023-09-28 02:33
> ```
> adb logcat *:E > logcat.txt
> ```

ok i ll try it tomorrow, and thanks

**Comment by Frank810803** [comment] 2023-09-28 02:40
> One more thing, if your time allows, exclude only the `enable-old-quality-layout` patch and try the patch.
> 
> I guess that's the cause

ok i'll try asap

**Comment by Frank810803** [comment] 2023-09-28 02:51
> One more thing, if your time allows, exclude only the `enable-old-quality-layout` patch and try the patch.
> 
> I guess that's the cause

ok, i exclude it and that did the trick, now isn't crashing anymore, thanks :)

**Comment by inotia00** [comment] 2023-09-28 05:37
Thanks for reporting logcat.
This issue will be fixed in the next release

**Comment by inotia00** [comment] 2023-09-29 18:24
fixed in [revanced-patches-v2.190.15](https://github.com/inotia00/revanced-patches/releases/tag/v2.190.15)

**Closed by inotia00** 2023-09-29 18:24 UTC
Labels: bug, question
