### ISSUE TITLE
feat(patch): fix YouTube bug: Quitting the app after opening Autoplay settings resets some General settings.

### ISSUE THREAD

**Issue by pressRtowin** [inotia00/ReVanced_Extended#997] opened 2023-05-10 01:20 UTC
### Application

YouTube

#### Important note: Regarding the check box below which reads `I have searched the existing issues and this is a new and no duplicate or related to another open issue.`—this problem _was_ mentioned in a previous issue, but that was submitted as a _bug report_. Also the cause (which I have found) was not known at the time. As this is not a bug with ReVanced or Extended, I'm submitting this as a feature request to patch the bug (if possible).

See title. `Zoom to fill screen` does not seem to be affected but both `Double-tap to seek` and `Enable stats for nerds` are. I have not tested other settings.

To reproduce:
1. Open ReVanced.
2. Change affected settings in `General`.
3. Resume normal operation of YouTube.
4. At any point during normal operation, open the `Autoplay` tab in settings.
5. Fully close YouTube.
6. Open YouTube.
7. Check `General` settings and see that some settings have been reset.

### Patch

Fix the above behavior. All settings should be persistent regardless of menus opened.

### Motivation

It fixes a very annoying issue with YouTube.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by FlamySan** [comment] 2023-05-10 04:48
You must be referring to my bug report #538. Yeah, initially I thought of it as a bug with RVX but later got to know it's a [YouTube problem.](https://github.com/inotia00/ReVanced_Extended/issues/538#issuecomment-1480458427) With time I too have noticed opening the Autoplay menu resets the `Double tap to seek` & have avoided opening it. For me though the bigger issue was Autoplay enabling itself in `incognito mode` that was annoying AF. It's a shame that YT has still not fixed this issue. I hope we find a solution to this soon, even through a `patch` if possible.

**Comment by FlamySan** [comment] 2023-05-10 08:27
> Just copying in some of my thoughts from the same request I made in the official ReVanced repo, which was (in my opinion) prematurely closed.
>
Read your thoughts & I lowkey agree w/ it but you also need to understand this isn't their job, they do this for sheer good will for people like us. We don't possess the same coding prowess or know-how so we can just have our opinions/suggestions & tbh it ain't same as the original work they put in.
> @FlamySan If you want a better chance of a patch being created for this, might want to voice your opinions over in the official ReVanced repo too (should be near the top of recently closed issues).
>
Pardon me but I've this problem of being fixated at smaller things in life & tend to waste time in the process. I foresee the same in this case hence will avoid. Hope you understand :)

**Comment by FlamySan** [comment] 2023-05-10 08:42
> @FlamySan are you trying to use YouTube without having the algorithm adjust recommendations for your tastes? Or are you trying to watch some videos without having them affect recommendations on your account?
> 
> If the second, one workaround is to create a brand account under your main account. You can then switch to it quickly by holding the account button and selecting it. It's treated just as if you had added a second Google account (without actually having to create one) and you can keep your recommendations and watch history separate there.

The second one, Yes, I like to keep my watch & search history neat, so I tend to use incognito a lot to search random junk & I hate autoplay so it getting enabled by it's own is a bummer for me. I know about brand accounts but again I like having a single primary channel on my Google account (or my OCD senses go REEE) plus incognito is lot easier/hassle-free.

**Comment by FlamySan** [comment] 2023-05-10 09:24
Like I said earlier, I avoid the autoplay menu & no, I don't need to go access it. Yes, I've the toggle button disabled as it eats up lot of screen. Yeah, but you can always cancel the next video to be played & the issue exists only in incognito so..
Also we're going a bit off topic in here..so I'd say wait for @inotia00 to reply to your `patch-request` first.

**Comment by inotia00** [comment] 2023-05-10 12:41
this is not a bug
When YouTube is installed for the first time, innerTube is not fully loaded.
(Probably, when Google implemented the Android YouTube client, it seemed to be configured this way for compatibility with legacy code.)

So it's only after installing the app for the first time and then force closing and relaunching the app that innerTube is fully loaded and YouTube loads the intended settings and layout server-side.

In order to compensate for the inconvenience that YouTube has inherently, `revanced-patches-v2.173.4` has been changed to display a reboot dialog when the app is first installed.

Now when you install the app for the first time you will follow the steps below.

1. Patch with revanced-patches-v2.173.4
2. Launch the RVX
3. You will see a login dialog
4. Log in
5. You will see reboot dialog: `Restart to load the layout normally`
6. Tap `Reboot`
7. Since innerTube is fully loaded, YouTube's intended settings and layouts are loaded server-side

**Comment by FlamySan** [comment] 2023-05-10 14:22
@inotia00 I think you misunderstood the OP. I've tested it with latest patch too, the issue exists long after installing the app & can be reproduced again & again. For example, say I let the innertube load & then set the `Double-tap to seek` at 5 secs > Then I open the Autoplay menu from settings > Then close YT & clear from recents > Open YT & check general settings > `Double-tap to seek` is reset to 10 secs & you can repeat this cycle.

**Comment by inotia00** [comment] 2023-05-10 14:31
ah, I understand
As you said, this is a YouTube bug

I need YouTube's source code to fix this issue.

**Comment by inotia00** [comment] 2023-05-11 01:51
This is because we don't know the details of how YouTube's default settings work and how this bug is reproducible.

I can't identify if this bug is simply a bug in the process of saving the SharedPreference, or if it's in the process of overwriting the value on the server side.

Customizing the layout is clearly visible and easy to debug, but reversing the default YouTube settings is very difficult.

**Comment by inotia00** [comment] 2023-05-11 01:52
I'm not able to fix it, so I'm closing the issue.

Please report this issue to Google

**Closed by inotia00** 2023-05-11 01:52 UTC
Labels: patch-request
