### ISSUE TITLE
bug: Portrait videos aren't "obeying" Default Video Quality setting.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [inotia00/ReVanced_Extended#120] opened 2023-01-08 04:40 UTC
### Type

Other

### Application

YouTube version: 18.01.35

revanced-patches: 2.152.6

revanced-integrations: 0.91.3

### Bug description

NOTE: Here, Portarit Videos ≠ Shorts.
Shorts and portrait videos are two completely different things. Shorts are shorts. Portrait videos are just normal videos made in portarit orientation.

So, here's the issue:

I set the default video quality to 2160p (while on WiFi) and 360p (while on mobile data).
Whenever I open any portrait video, they start playing at random qualities like 360p, 480p, 720p, etc (even if 1080p, 1440p and 2160p are available for that particular video).

This should be considered a "bug" because it isn't obeying the ReVanced settings.

NOTE: Landscape videos are always obeying quality overrides.

### Steps to reproduce

To reproduce this issue, kindly play this video on your ReVanced Extended:

https://youtu.be/XpDwXkZwa74

### Relevant log output

```shell
Please check the steps to reproduce.
```

### Screenshots or videos

![IMG_20230108_095825](https://user-images.githubusercontent.com/91815107/211180468-2bd871c6-a0db-420d-a176-9f6b130ad849.jpg)

### Device Environment

Realme 7 Pro, running on Realme UI 3.0 (based on Android 12).

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment] 2023-01-08 06:56
duplicate of the following issue https://github.com/inotia00/ReVanced_Extended/issues/1

**Closed by inotia00** 2023-01-08 06:56 UTC
Labels: bug
