### ISSUE TITLE
bug(YouTube/Hide filmstrip overlay): filmstrip overlay is always hidden in YouTube v18.33.40

### ISSUE THREAD

**Issue by Adity1243** [inotia00/ReVanced_Extended#1463] opened 2023-10-02 16:40 UTC
### Type

Error at runtime

### Tools used

Revancify

### Application

Youtube 18.33.40

### Bug description

Swiping up the seekbar freezes the video permanently 

### Steps to reproduce

Open youtube
Start video
Swipe up seekbar for filmstrip overlay

### Relevant log output

```shell
.
```

### Screenshots or videos

Recorder link:-
https://drive.google.com/file/d/1EByoQsOgLCYRlWAW2--OyN--TvZTeJmi/view?usp=drivesdk

### Solution

Problem in filmstrip overlay patch

### Device Environment

Android 12, miui14

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [ ] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment] 2023-10-02 16:51
This is sometimes reproduced even on unpatched YouTube

It's most likely simply a bug in YouTube

Apply the patch to a lower version within the range supported by the current patch (v18.22.37 ~ v18.33.40)

**Comment by inotia00** [comment] 2023-10-02 17:12
Update:
On unpatched YouTube, this bug only reproduces when litho content is not loaded

This bug does not reproduce when all layouts are loaded normally in unpatched YouTube

I will take a look codes

**Comment by inotia00** [comment] 2023-10-02 17:37
I looked at the code again and realized I was wrong

wait for the next release or
Or roll back to YouTube v18.32.39
Or exclude the `hide-filmstrip-overlay` patch

Since it is a valid issue, I am reopening the issue

**Comment by Adity1243** [comment] 2023-10-02 19:12
Ok thanks

**Comment by inotia00** [comment] 2023-10-03 19:26
fixed in [revanced-patches-v2.190.21](https://github.com/inotia00/revanced-patches/releases/tag/v2.190.21)

**Closed by inotia00** 2023-10-03 19:26 UTC
Labels: bug
