### ISSUE TITLE
bug(YouTube/Custom speed overlay): `Disable speed overlay` breaks `Slide to seek` behavior

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#1574] opened 2023-10-19 20:54 UTC
### Type

Error while patching

### Tools used

ReVanced Manager

### Application

YouTube v18.39.41
Patches v2.193.18

### Bug description

Holding and sliding right and left doesn't move the seekbar pointer anymore.

https://github.com/inotia00/ReVanced_Extended/assets/127908708/62778acd-8907-4376-b899-8987773f79f2

### Steps to reproduce

N/A

### Relevant log output

```shell
N/A
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment] 2023-10-19 21:12
If `press and hold to play at 2x speed` is enabled on your account, slide to seek is disabled.

Since this is disabled on the server side, it cannot be fixed.

**Comment by KobeW50** [comment] 2023-10-19 21:15
> If `press and hold to play at 2x speed` is enabled on your account, slide to seek is disabled.
> 
> Since this is disabled on the server side, it cannot be fixed.

Both are enabled on my account and work (in stock YT and YT RVX). Maybe A/B tests?

https://github.com/inotia00/ReVanced_Extended/assets/84587632/146a86b5-44a9-431a-82c7-e070469024ba

**Comment by inotia00** [comment] 2023-10-19 21:24
Thanks to you, I found the cause

To fix this issue I need to remove the following patches:
- `Custom speed overlay`
- `Enable new thumbnail preview`

Since `slide to seek` is quite important, I will remove these patches in the next release

Reopen issue

**Comment by KobeW50** [comment] 2023-10-19 21:31
> To fix this issue I need to remove the following patches:
> - `Custom speed overlay`
> - `Enable new thumbnail preview`
> 
> Since `slide to seek` is quite important, I will remove these patches in the next release

Perhaps I am missing something, but I thought `Slide to seek` can only be enabled when swiping from the middle of the player while the video is paused. If this is the case, why is `Slide to seek` so important? Users can still slide on the seekbar with the same effect.

**Comment by Kuddus73** [comment] 2023-10-19 23:32
> Thanks to you, I found the cause
> 
> To fix this issue I need to remove the following patches:
> 
>     * `Custom speed overlay`
> 
>     * `Enable new thumbnail preview`
> 
> 
> Since `slide to seek` is quite important, I will remove these patches in the next release
> 
> Reopen issue

I can confirm that "Slide to seek" only breaks with the new UI, with the old one it still works fine.
I thought you would like to know this before you removing them.

**Comment by inotia00** [comment] 2023-10-19 23:48
After testing several times, it is clear that ‘Disable speed overlay’ is the key cause
Therefore, there is no need to remove all patches, but the `Disable speed overlay` settings will inevitably be removed

**Comment by Kuddus73** [comment] 2023-10-20 00:07
Instead of removing it, wouldn't it be simple to just put a note that says that `Slide to seek` won't work if you enable `Disable speed overlay`?

**Comment by inotia00** [comment] 2023-10-20 02:16
The `Custom speed overlay` patch and the `Disable speed overlay` patch should be separate.

Therefore, I think it would be appropriate to remove the 'Disable speed overlay' setting from the 'Custom speed overlay' patch.

I will add `Disable speed overlay` patch once I can implement the appropriate patch without any issues.

**Comment by inotia00** [comment] 2023-10-21 02:19
fixed in [revanced-patches-v2.195.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.195.1)

**Closed by inotia00** 2023-10-21 02:19 UTC
Labels: bug

**Comment by inotia00** [comment] 2023-10-30 08:42
> I will add `Disable speed overlay` patch when I can implement the appropriate patch without issue.

reflected in [revanced-patches-v2.195.8](https://github.com/inotia00/revanced-patches/releases/tag/v2.195.8)
