### ISSUE TITLE
bug: Overlay buttons disappearance speed don't match

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#631] opened 2023-04-02 18:24 UTC
### Type

Other

### Application

YouTube v18.12.35
Revanced Patches v2.168.1

### Bug description

**The Overlay buttons' disappearance speed don't match the regular buttons.
As you can see from the video Overlay buttons stay longer.**

https://user-images.githubusercontent.com/127908708/229371258-0f1d5a5e-321c-49c8-b24a-d466f988a52a.mp4

### Steps to reproduce

Swipe the seek bar of any video by enabling any overlay button.

### Relevant log output

```shell
N/A
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by jhon1282** [comment] 2023-04-02 19:22
In previous versions this didn't happen because the overlay buttons didn't disappear

**Comment by inotia00** [comment] 2023-04-03 00:30
[Previously reported bug](https://github.com/inotia00/ReVanced_Extended/issues/504) and this bug cannot be fixed at the same time

**Comment by Kuddus73** [comment] 2023-04-03 01:45
> [Previously reported bug](https://github.com/inotia00/ReVanced_Extended/issues/504) and this bug cannot be fixed at the same time

There isn't a way to match the timing of disappearance?

**Comment by inotia00** [comment] 2023-04-03 04:03
I can either roll back to the previous version (overlay button appears when tapping the navigation bar, an issue from Vanced), or keep it current (issue on this page).

**Comment by Kuddus73** [comment] 2023-04-03 05:21
Oh, then keep it as it is currently

**Comment by inotia00** [comment] 2023-04-03 09:45
fixed in [revanced-patches-v2.168.3](https://github.com/inotia00/revanced-patches/releases/tag/v2.168.3)

**Closed by inotia00** 2023-04-03 09:45 UTC
Labels: bug

**Comment by Kuddus73** [comment] 2023-04-03 11:55
Now it exactly matches the disappearance timing, thank you.

The only problem that remains, which I didn't realise from the video attached but which is now evident, is that the timing of the reappearance of the overlay buttons is also wrong.

**Comment by inotia00** [comment] 2023-04-03 11:59
It's reproducible, but it doesn't seem like a fix right now
I've spent the whole day just fixing this issue (I'm a little tired)

I'll check it later when I have time

**Comment by Kuddus73** [comment] 2023-04-03 12:12
> It's reproducible, but it doesn't seem like a fix right now I've spent the whole day just fixing this issue (I'm a little tired)
> 
> I'll check it later when I have time

Take all the time you need, sorry if I seemeed pushy or something, I was just reporting

Last thing, should I open another bug issue _(as this is actually a different bug than originally reported and currently also closed)_?
