### ISSUE TITLE
bug(YouTube/Hide mix playlists): description of some videos is hidden

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#1642] opened 2023-11-03 00:52 UTC
### Type

Error while patching

### Tools used

RVX Manager

### Application

YouTube v18.40.34
Patches v2.195.12

### Bug description

https://github.com/inotia00/ReVanced_Extended/assets/127908708/0fe15e2b-7900-4eb6-a7ec-de36204f0ce3

### Steps to reproduce

N/A

### Relevant log output

```shell
N/A
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment] 2023-11-03 07:40
It does not reproduce on my side
Change all switches to OFF in settings until the issue is resolved
And please leave a comment which patch is causing the issue

**Comment by Kuddus73** [comment] 2023-11-03 14:56
Took me a while but found it:
`Hide mix playlist`

https://github.com/inotia00/ReVanced_Extended/assets/127908708/6a7ed524-8438-4caa-83ac-47d3487505b5

**Comment by inotia00** [comment] 2023-11-11 15:29
fixed in [revanced-patches-v2.196.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.196.1)

**Closed by inotia00** 2023-11-11 15:29 UTC
Labels: bug
