### ISSUE TITLE
bug: swipe gesture not working in certain situations

### ISSUE THREAD

**Issue by Faszom11** [inotia00/ReVanced_Extended#517] opened 2023-03-20 03:06 UTC
### Type

Error at runtime

### Application

YouTube 18.10.37

### Bug description

After importing revanced settings or setting up layout manually, swipe controls won't work anymore.
[YouTube_v18.10.37_2023-03-19.zip](https://github.com/inotia00/ReVanced_Extended/files/11013318/YouTube_v18.10.37_2023-03-19.zip)
(.json file included)

### Steps to reproduce

Import .json file, click on a video and swipe up /down

### Relevant log output

```shell
No logs
```

### Screenshots or videos

https://user-images.githubusercontent.com/127752289/226237200-fa0830b9-8eec-4c59-864e-126c7bc107a7.mp4

### Additional context

Included patches:

Variant: nonRoot
Arch: arm64-v8a
App: YouTube-18-10-37.apk
CLI: inotia00-cli-v2.21.0.jar
Patches: inotia00-patches-v2.166.8.jar
Integrations: inotia00-integrations-v0.100.8.apk
Patches argument:
-i custom-branding-icon-afn-red
-i custom-branding-name
-i custom-video-speed
-i default-video-quality
-i enable-external-browser
-i enable-minimized-playback
-i enable-old-quality-layout
-i enable-seekbar-tapping
-i force-premium-heading
-i hide-auto-captions
-i hide-auto-player-popup-panels
-i hide-channel-watermark
-i hide-email-address
-i hide-endscreen-cards
-i hide-general-ads
-i hide-info-cards
-i hide-mix-playlists
-i hide-player-button-background
-i hide-video-ads
-i microg-support
-i optimize-resource
-i overlay-buttons
-i patch-options
-i return-youtube-dislike
-i settings
-i sponsorblock
-i swipe-controls
-i theme

### Device Environment

Android 13, OneUI 5.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment] 2023-03-20 09:37
Even on official ReVanced, the issue is reproduced if the following conditions are met:

- include `hide-autoplay-button`
- turn off `Hide autoplay button` settings
- turn off `Enable press-to-swipe gesture` settings

If you are going to use `Hide autoplay button` off, just exclude `hide-autoplay-button` patch when proceeding with the patch.

It will take some time to completely fix

**Comment by inotia00** [comment] 2023-10-03 13:59
Ironically, after removing all code related to the `press-to-swipe gesture`, this bug was fixed

There may be many users using `press-to-swipe gesture`, but `press-to-swipe gesture` has the potential to break the entire swipe gesture patch

Additionally, there are no longer active developers maintaining swipe gesture patch

For the sake of code maintenance, I will remove `press-to-swipe gesture` in the next release

**Comment by inotia00** [comment] 2023-10-03 19:26
fixed in [revanced-patches-v2.190.21](https://github.com/inotia00/revanced-patches/releases/tag/v2.190.21)

**Closed by inotia00** 2023-10-03 19:26 UTC
Labels: bug

**Comment by ANi1XO** [comment] 2023-10-04 04:30
Solution applied it patch v2.190.21 has broken "enable auto brightness when brightness is set to 0". now even when the patch it turned on and auto brightness doesn't get enabled instead the brightness gets set to 0.

**Comment by inotia00** [comment] 2023-10-04 04:45
> Solution applied in patch v2.190.21 has broken "enable auto brightness when brightness is set to 0". now even when the patch it turned on, auto brightness doesn't get enabled instead the brightness gets set to 0.

not reproduced

open new issues, including appropriate reproduce processes

**Comment by anil-al** [comment] 2023-10-05 18:53
`press-to-swipe gesture` has an important role which is blocking accidental swipes. As a tablet user, I use many swipe actions due to using apps in multi-window, pop-up etc. and also the navigation gestures. When I don't use `press-to-swipe gesture`, I regularly experience the trouble of turning volume on acutely. Please do not delete it, a warning can be added to the patch description.

**Comment by inotia00** [comment] 2023-11-28 06:38
To restore this functionality, I rolled back the integration dependencies to a year ago and rebased the entire integrations code.
(It is presumed that the cause of this bug is because too recent versions of dependencies and build tools were used)

This was quite an arduous task, but it looks like this feature will be restored in the next release.
