### ISSUE TITLE
Return YouTube Dislike bug

### ISSUE THREAD

**Issue by walti0** [inotia00/ReVanced_Extended#206] opened 2023-01-31 15:59 UTC
![IMG_20230131_165346](https://user-images.githubusercontent.com/95646872/215813646-060353ea-93d3-4e87-a541-01ef6be35c0c.jpg)
So when I turn on this stick in settings, it's looks okey but when I restart YouTube it's fully white, and it's terrible. I have this issue on every version and on my both phones.

**Comment by inotia00** [comment] 2023-01-31 16:22
It is a bug in the official revanced, and is an issue that occurs in a specific manufacturer ROM.

If the issue is not reproduced in my device, I can't fix, so I set it to hide the ryd separator with a default.

this issue report is not written according to the form, so I will close it
please write report within form

**Closed by inotia00** 2023-01-31 16:22 UTC
