### ISSUE TITLE
bug(music/settings): library tab stuck when opening device files in library tab

### ISSUE THREAD

**Issue by buiducanh142qn** [inotia00/ReVanced_Extended#906] opened 2023-04-30 06:11 UTC
### Type

Error at runtime

### Application

YouTube Music ReVanced Extended v5.54.52.
Patch: v2.171.2.

### Bug description

While you are in the Library tab, keep clicking on Library tab to open the "View my" dialog.
After that, if you select Device files, Library tab will get stuck, and you won't be able to tap on the Library tab to open other functions (Unless you press the title at the top, haha).

### Steps to reproduce

.

### Relevant log output

```shell
.
```

### Screenshots or videos

![photo_2023-04-30_13-06-31](https://user-images.githubusercontent.com/54460494/235338498-3950c61c-bf11-4822-8c7e-b6d09c2db8b9.jpg)

### Device Environment

Android 13, MIUI 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment] 2023-04-30 07:32
![0430163053705148](https://user-images.githubusercontent.com/108592928/235341406-7a5c6be4-8404-45e8-98e9-a7a2dd9b6257.jpg)

I tested it but the issue is not reproducible

If you are using a root environment, try a clean install
Also, try manually granting YT Music permission.

**Comment by buiducanh142qn** [comment] 2023-04-30 07:41
I tried a clean install and gave all permissions to MRVX, but this error still occurs.
Here is the video.
https://user-images.githubusercontent.com/54460494/235341623-2702aa6c-949e-4fce-b127-fa4cf22defec.mp4

**Comment by inotia00** [comment] 2023-04-30 08:03
ah, I misunderstood the issue
yeah this is reproducible

**Comment by inotia00** [comment] 2023-09-20 07:29
fixed in [revanced-patches-v2.190.8](https://github.com/inotia00/revanced-patches/releases/tag/v2.190.8)

**Closed by inotia00** 2023-09-20 07:29 UTC
Labels: bug
