### ISSUE TITLE
bug: Enable save and restore brightness option working even before not enabling that

### ISSUE THREAD

**Issue by rks2000** [inotia00/ReVanced_Extended#1349] opened 2023-09-08 18:35 UTC
### Type

Other

### Tools used

Revancify

### Application

Youtube version 18.31.40

Enable save and restore brightness option present in swipe control is working even if i disable this option

### Bug description

So i don't want my fullscreen brightness to be saved. So didn't enable this option but even after this whenever i change the brightness in fullscreen it gets saved and restore that sane brightness level next time

### Steps to reproduce

Step 1 - Don't Enable save brightness option present in swipe controls settings

Step 2 - play video in fullscreen increase its brightness 

Step 3 - close YT app 

Step 4 - reopen the video in fullcreen and screen brightness restored ( which i dont want )

### Relevant log output

```shell
None
```

### Device Environment

Android 13 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by 33DCs** [comment] 2023-09-17 18:42
I am also having this issue.

Youtube 18.31.40 patched with RVX manager 1.9.7

Steps to reproduce issue:
1. Open revanced extended youtube 
2. Settings > revanced extended > swipe controls
3. Uncheck option for "disable save and restore brightness"
4. Close revanced extended youtube 
5. Force close and clear app cache
6. Reopen revanced extended 18.31.40
7. Set custom brightness via swipe method in any video
8. Close video
9. Open any video
10. Brightness is still saved from previous video (in landscape mode)

Android 13
Samsung Galaxy S23
One UI 5.1

**Comment by inotia00** [comment] 2023-10-03 19:30
there are no longer active developers maintaining swipe gesture patch

Since the `save and restore brightness` option was an `Experimental Flags`, [I just removed the settings](https://github.com/inotia00/revanced-patches/releases/tag/v2.190.21)

closing the issue

**Closed by inotia00** 2023-10-03 19:30 UTC
Labels: bug
