### ISSUE TITLE
bug(YouTube/Hide player flyout panel): components are not hidden in new layout

### ISSUE THREAD

**Issue by Mohammed1520** [inotia00/ReVanced_Extended#1410] opened 2023-09-23 09:45 UTC
### Type

Other

### Tools used

Revancify

### Application

YouTube 18.31.40

### Bug description

Report menu is still shown deapite hiding it from settings

### Steps to reproduce

Hide report menu from Hide flyout menu section 

### Relevant log output

```shell
.
```

### Screenshots or videos

![Screenshot_20230923_124010_app rvx android youtube_edit_1002438371581930](https://github.com/inotia00/ReVanced_Extended/assets/107951133/08a8b9c1-bd17-477f-934b-e4b85be2fb72)
![Screenshot_20230923_124030_app rvx android youtube_edit_1002427707412140](https://github.com/inotia00/ReVanced_Extended/assets/107951133/d38dedad-795f-4364-99ba-0f9fa6542d3f)

### Solution

**Patch to YouTube v18.24.37 or v18.25.40, which does not apply A/B tests**

### Additional context

..

### Device Environment

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment] 2023-09-23 09:49
Looks like A/B tests
Since it does not reproduce in my account, fix is not possible right now

Temporarily you can disable these A/B tests with the following steps:
1. Patch to YouTube v18.19.36, the minimum supported version
2. Install on your device
3. Open RVX and finish setup
4. Patch to YouTube v18.31.40
5. Install on your device

**Comment by Mohammed1520** [comment] 2023-09-23 10:15
Now it works. It seems that the bug is related to new shape of flyout menu(like pic i have attached above)  as this problem is also present in Rex and in YouTube 18.33.xx and 18.35.xx 
![Screenshot_20230923_130727_app rvx android youtube_edit_1004059091970745](https://github.com/inotia00/ReVanced_Extended/assets/107951133/89d7fbd4-57ef-40a7-a293-139bb9ddf832)

**Comment by inotia00** [comment] 2023-09-23 11:50
The patch does not support all A/B tests, and if unsupported A/B tests are applied to your account, the patch will not work like this issue.

The higher the YouTube version, the more A/B tests are likely to be applied.

This is why the RVX patch is limiting supported YouTube versions to v18.31.40
(To minimize patches being broken by A/B tests)

**Comment by Mohammed1520** [comment] 2023-09-23 14:57
The issue have returned😅 it is definitely A/B tests

**Comment by inotia00** [comment] 2023-09-23 16:15
If so, there is no clear solution
Fixing is not possible until this A/B layout is reproduced in my account.
Temporarily patch a version old enough, such as YouTube v18.25.40

**Comment by YT-Advanced** [comment] 2023-10-18 13:05
Since I don't have any account with this new A/B Layout, so I can check this PRs
https://github.com/ReVanced/revanced-integrations/pull/502

**Comment by inotia00** [comment] 2023-10-18 23:43
It probably works well

**Comment by inotia00** [comment] 2023-10-19 03:56
fixed in [revanced-patches-v2.193.18](https://github.com/inotia00/revanced-patches/releases/tag/v2.193.18)

**Closed by inotia00** 2023-10-19 03:56 UTC
Labels: bug, A/B test
