### ISSUE TITLE
bug(YouTube/Hide shorts components): on 18.34.xx+ like and dislike buttons cant be hidden

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1525] opened 2023-10-13 09:03 UTC
### Type

Error at runtime

### Tools used

Revancify

### Application

YouTube 18.34.38 ~ 18.36.39

### Bug description

On 18.34.xx+ like and dislike buttons cant be hidden. This is bug that reproducable for all, you can just see in RVX chat, i think it not need more detailed description

### Steps to reproduce

1. Patch 18.34.38, 18.35.36, 18.36.39
2. Include `settings` and `hide-shorts-components` patches
3. Hide like and dislike button in shorts

### Relevant log output

```shell
:/
```

### Solution

Only solution for this moment to spoof or patch on 18.33.40 or lower

### Device Environment

Android 12 One Ui 4.1.1; Android 13 MiUi 14.0.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by girshcatt** [comment] 2023-10-13 09:28
> YouTube-v18.36.39 version same.

Did you see that i wrote 18.34.xx+? It mean that it affect all versions higher than 18.34.xx, also comment as: I expiriencing the same issue is useless

**Comment by inotia00** [comment] 2023-10-13 09:49
This issue is most likely a bug due to the complexity of the Shorts component filter rather than A/B tests.
(at least it works fine for me)

Please export and upload the settings you are using.

**Comment by girshcatt** [comment] 2023-10-13 09:54
> This issue is most likely a bug due to the complexity of the Shorts component filter rather than A/B tests. (at least it works fine for me)
> 
> Please export and upload the settings you are using.

[ReVanced Extended_v18.36.39_2023-10-13.json](https://github.com/inotia00/ReVanced_Extended/files/12892209/ReVanced.Extended_v18.36.39_2023-10-13.json)

**Comment by inotia00** [comment] 2023-10-13 09:56
It is now possible to reproduce
It will probably be fixed in the next release

**Comment by inotia00** [comment] 2023-10-13 16:42
fixed in [revanced-patches-v2.193.12](https://github.com/inotia00/revanced-patches/releases/tag/v2.193.12)

**Closed by inotia00** 2023-10-13 16:42 UTC
Labels: bug
