### ISSUE TITLE
bug: Problem reading Comments with Read More button in Arabic interface

### ISSUE THREAD

**Issue by iBasim** [inotia00/ReVanced_Extended#1219] opened 2023-07-25 04:03 UTC
### Type

Error at runtime

### Tools used

Revancify

### Application

YouTube v18.27.35
v2.186.4

### Bug description

It is a very old problem, and frankly, I am tired of it. The problem is when language of YouTube application is in Arabic, and when reading responses to the comments, with some long comments, there is a "read more" button when pressed,He does not expand the response to view it, nothing happens, and sometimes he opens the keyboard to type a response, the Video explains the problem

### Steps to reproduce

1- Let Language of YouTube be Arabic
2-Go to one of the long comment replies and try to press the Read More button. reply will not expand and you will not see the full comment.

### Relevant log output

```shell
none
```

### Screenshots or videos

https://github.com/inotia00/ReVanced_Extended/assets/57762287/fa587998-b69c-4be5-96d3-397a33835056

### Solution

I really do not know what is the solution to the problem, and it is very old. I hope that you, Brother inotia00, will find a solution

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment] 2023-07-25 04:22
Does the issue reproduce on unpatched YouTube?

**Comment by iBasim** [comment] 2023-07-25 05:09
> 

I'm not sure, in fact, I haven't tried it at all on my phone. I was used Vanced and moved to ReVanced Extended, and the same problem persists.

**Comment by inotia00** [comment] 2023-08-05 00:06
It seems to be an issue of stock YouTube. closing the issue

**Closed by inotia00** 2023-08-05 00:06 UTC
Labels: bug
