### ISSUE TITLE
bug: `protobuf-spoof` patch broke the feature that showing thumbnails when tapping seekbar

### ISSUE THREAD

**Issue by VadimMillerVMMR** [inotia00/ReVanced_Extended#481] opened 2023-03-14 14:29 UTC
### Type

Other

### Application

YouTube 18.09.39, patches version 2.164.32.

### Bug description

Frame-by-frame rewind doesn't work and also there's no the video preview when tap on the seek bar.

### Steps to reproduce

1) Open any video
2) Try to use frame-by-frame rewind (pull your finger up from the current location in the video.)
3) There is only a vibration when pulling the finger up. Also, there's no video preview when tap on the seek bar.

### Relevant log output

```shell
—
```

### Screenshots or videos

https://user-images.githubusercontent.com/127863693/225031487-1bed3964-6826-49b5-8314-d015d614ed41.mp4

### Device Environment

Android 13, MIUI 14.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by jhon1282** [comment] 2023-03-14 15:33
Same issue 

https://user-images.githubusercontent.com/125223735/225053276-26b00e69-d556-4a2c-bbd5-a4d89971058e.mp4

YouTube stock 

https://user-images.githubusercontent.com/125223735/225053464-8878af5b-68b3-442b-bd78-97b47f721451.mp4

**Comment by inotia00** [comment] 2023-03-14 23:01
Exclude the `protobuf-spoof` patch until the issue is fixed

**Comment by Ackmard** [comment] 2023-03-15 00:40
I'm having the same issue even without the patch.

**Comment by Kuddus73** [comment] 2023-03-15 01:02
> Exclude the `protobuf-spoof` patch until the issue is fixed

I tried excluding that patch as you said, the issue is still there tho.

**Comment by inotia00** [comment] 2023-03-15 02:49
1. Patch again with revanced-patches-v2.165.1
2. If you have video buffer issues on your device, change `Enable protobuf spoof` to ON
2-1. Change `Select protobuf to spoof` to ON

**Comment by Ackmard** [comment] 2023-03-15 03:09
> 1. Patch again with revanced-patches-v2.165.1
> 2. If you have video buffer issues on your device, change `Enable protobuf spoof` to ON
> 2-1. Change `Select protobuf to spoof` to ON

That fixed it, also ambient mode seems fixed for me as well.

**Comment by madhurvarshney** [comment] 2023-03-15 05:49
> 1. Patch again with revanced-patches-v2.165.1
> 2. If you have video buffer issues on your device, change `Enable protobuf spoof` to ON
>    2-1. Change `Select protobuf to spoof` to ON

Can anyone please explain me what "Select protobuf to spoof" option does and in what case should it be enabled/disabled?
Because the video playback issue seems to be resolved when "Enable protobuf spoof" is turned ON, irrespective of "Select protobuf to spoof".
The only difference I find currently is:
1. When the "Select protobuf to spoof" is OFF, the captions appear at the bottom while tge thu

**Comment by madhurvarshney** [comment] 2023-03-15 05:53
> 1. Patch again with revanced-patches-v2.165.1
> 2. If you have video buffer issues on your device, change `Enable protobuf spoof` to ON
>    2-1. Change `Select protobuf to spoof` to ON

Can anyone please explain me what "Select protobuf to spoof" option does and in what case should it be enabled/disabled?
Because the video playback issue seems to be resolved when "Enable protobuf spoof" is turned ON, irrespective of "Select protobuf to spoof".
The only difference I find currently is:
1. When the "Select protobuf to spoof" is OFF, the captions appear at the bottom but the thumbnails are not shown when tapping seekbar.
2. When it is ON, the thumbnails are shown when tapping seekbar but now the captions appear the the top.

**Comment by inotia00** [comment] 2023-03-15 08:00
yeah it's exactly what you wrote
I couldn't fix all three issues at once, so I just added all three options to the settings to choose from.

**Comment by inotia00** [comment] 2023-03-15 15:25
There is no valid fix for this

If you don't want to face this issue, just turn off the protobuf-spoof

**Comment by Kuddus73** [comment] 2023-03-15 16:34
> but now the captions appear the the top.

Is it possibile to fix this issue?

**Comment by FlamySan** [comment] 2023-03-25 05:55
@inotia00 I've a good news..watch history seems to have been fixed on 18.12.34 with latest patch when protobuf is spoofed as shorts. The endscreen & subtitle remain broken though.

**Comment by madhurvarshney** [comment] 2023-03-25 06:13
> @inotia00 I've a good news..watch history seems to have been fixed on 18.12.34 with latest patch when protobuf is spoofed as shorts. The endscreen & subtitle remain broken though.

Yeah, even on v18.11.35 with patch v2.166.12, the watch history seems to be fixed when protobuf is spoofed as shorts.

**Comment by inotia00** [comment] 2023-04-02 10:27
fixed in [revanced-patches-v2.168.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.168.1)

**Closed by inotia00** 2023-04-02 10:27 UTC
Labels: bug
