### ISSUE TITLE
bug: (YouTube/Shorts) Shorts appearing in search results feed alongside regular videos

### ISSUE THREAD

**Issue by 1node0001** [inotia00/ReVanced_Extended#2401] opened 2024-09-23 21:13 UTC
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YouTube 19.16 39
Patches 4.14.1-dev.1

### Bug description

1. Enable Hide in search results (Shorts)
2. Search something like Failtime
3. Notice how shorts are appearing in the feed alongside regular videos (I attach a screenshot for this)

### Error logs

```shell
No available
```

### Solution

Fix Hide in search results patch for Shorts

### Additional context

![Screenshot_20240924_000547_RVX](https://github.com/user-attachments/assets/355cc296-3c0e-4b30-b894-e43de7526f0f)

### Device Environment

Android 14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I didn't use any settings marked as `Experimental Flags`.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment] 2024-09-23 22:08
This is an issue that is not reproducible on my side

1. Please attach the full list of patches that are included or excluded
2. Export the settings you are using and attach them here

**Comment by 1node0001** [comment] 2024-09-23 22:51
> This is an issue that is not reproducible on my side
> 
> 1. Please attach the full list of patches that are included or excluded
> 2. Export the settings you are using and attach them here

All patches included except Debug Logging and Translate.

Settings: 
[RVX_v19.16.39_2024-09-24.txt](https://github.com/user-attachments/files/17105292/RVX_v19.16.39_2024-09-24.txt)

**Comment by inotia00** [comment] 2024-09-23 23:27
In the same condition, I imported the settings, but it was not reproduced on my side

Recently Google changed the paths of litho components on the server side
(still only for some users)

Maybe that's the reason

**Comment by 1node0001** [comment] 2024-09-23 23:48
> In the same condition, I imported the settings, but it was not reproduced on my side
> 
> Recently Google changed the paths of litho components on the server side (still only for some users)
> 
> Maybe that's the reason

Are A/B tests also active for users who are not logged in? I dont login to MicroG.

**Comment by inotia00** [comment] 2024-09-24 04:21
To be precise, A/B testing is enabled or disabled by the `Phenotype Flag` in GmsCore

(The most common Magisk module that forces this value to be enabled is [GAppsMod](https://github.com/jacopotediosi/GAppsMod))

This value is updated when you are logged into your Google account, but is also used when you are not logged into your Google account

(A typical example is when the layout loaded from your Google account is different from the layout loaded in Incognito mode)

**Comment by 1node0001** [comment] 2024-09-25 08:26
I uninstalled and reinstalled, and Im not seeing Shorts anymore alomgside regular videos. You can close this issue or keep it open just in case this happens to someone else.

**Comment by inotia00** [comment] 2024-09-25 13:54
This bug can occur very rarely when updating from an old RVX

(The same issue was reported before, but I couldn't find it)

Yeah, in this case, it's related to a conflict in the RVX app data, so a simple clean install will solve it

It doesn't seem to be an A/B test, I'll close the issue

**Closed by inotia00** 2024-09-25 13:54 UTC
Labels: Bug report, A/B test
