### ISSUE TITLE
bug: SponsorBlock "Time with Skips Removed" and Video Speed in Right to Left Languages 

### ISSUE THREAD

**Issue by blacktornadog7** [inotia00/ReVanced_Extended#506] opened 2023-03-17 23:42 UTC
### Type

Cosmetic

### Application

YouTube 18.08.39

### Bug description

In Right to Left Languages the "x" from the video speed (as in 1.0x, 1.25x...) comes after the SponsorBlock "Time with Skips Removed" instead. (screenshot below)

### Steps to reproduce

1. Change Youtube's display language to a right to left language
2. Enable SponsorBlock
3. Play a video with skippable segments 

### Relevant log output

```shell
no logs
```

### **What it looks like:**
![Screenshot_20230317_114303_ReVanced Extended](https://user-images.githubusercontent.com/74029985/226063241-2db7c062-8e82-415b-9789-bc9a9c7dd32e.png)

### **What it's supposed to look like:**
![Screenshot_20230318_003212_ReVanced Extended](https://user-images.githubusercontent.com/74029985/226064197-4babe984-2f23-4230-83f0-56f7da08ec0b.jpg)

### Solution

🤷🤷🤷

### Device Environment

Android 13 (One UI 5)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment] 2023-03-18 14:16
fixed in [revanced-patches-v2.166.4](https://github.com/inotia00/revanced-patches/releases/tag/v2.166.4)

**Comment by blacktornadog7** [comment] 2023-03-19 23:33
### I really hate to be that guy but this is somehow worse than before:

![Screenshot_20230320_004325_ReVanced Extended](https://user-images.githubusercontent.com/74029985/226215342-abadfefd-1ae5-4f8f-ba3b-075a400cc343.jpg)

(I don't know if I should open a new issue or not?)
P.S @inotia00 I just wanted to say you're a fucking legend for making this whole fork in the first place, maintaining it by yourself and with the rate you're fixing and adding new features, simply kudos to you, thanks a lot.
(btw this is definitely me buttering you up to fix this)
you know I'm joking right ? or I'm I? 😁😁😁

**Comment by inotia00** [comment] 2023-03-19 23:43
what do you mean? Does the issue still reproduce?

**Comment by blacktornadog7** [comment] 2023-03-20 00:05
Yes it does even with the latest patch, I even double checked when Installing.
(but it's a little different now, **before** the bug was that the time and speed sort of switched places and the "x" came after the time instead, **now** It's the the dot that should be between the time and the speed is between the speed and the "x")

**Comment by inotia00** [comment] 2023-03-20 00:22
When tested on another device using AOSP ROM, the issue was reproduced.

Maybe.. my main device doesn't support RTL layout (but why..?)

Anyway, this issue is still valid, so I'll reopen it

**Comment by inotia00** [comment] 2023-03-20 09:40
Fortunately, this issue seems to be fixable.

It will be reflected in the next release

by the way.. This project is a kind of talent donation that goes on without any donations or sponsors.

I know you're upset, but I hope you'll be a bit more polite when reporting issues.

**Comment by blacktornadog7** [comment] 2023-03-20 10:48
I'm not upset in any way? why would I be?
And I'm really sorry if anything I said came out as impolite, I was joking and had nothing but praise, idk I thought I made that 
clearly obvious? 
Anyway my bad, sorry again.

**Comment by inotia00** [comment] 2023-03-22 02:52
fixed in [revanced-patches-v2.166.10](https://github.com/inotia00/revanced-patches/releases/tag/v2.166.10)

**Comment by inotia00** [comment] 2023-03-22 02:52
![ReVanced](https://user-images.githubusercontent.com/108592928/226789794-37b81a0c-1efa-4b8a-be75-04aa7d0e762d.png)

**Closed by inotia00** 2023-03-22 02:52 UTC
Labels: bug

**Comment by blacktornadog7** [comment] 2023-03-22 21:44
is it possible for the "time with skipped segments" and speed to come after the full length as in normal (non RTL layout) ?

**Comment by blacktornadog7** [comment] 2023-04-26 00:05
### broken again after being [fixed](https://github.com/revanced/revanced-patches/issues/1901) in Revanced:
![Screenshot_20230426_025446_ReVanced Extended](https://user-images.githubusercontent.com/74029985/234433478-7e37f966-e9fc-4cab-84df-3b0ae9703d9b.jpg)

**Comment by inotia00** [comment] 2023-04-26 00:35
Unfortunately, no further fixes are planned.

Use the official ReVanced
