### ISSUE TITLE
bug(YouTube/SponsorBlock): applying the outline icon makes skip buttons overlap

### ISSUE THREAD

**Issue by Rairof** [inotia00/ReVanced_Extended#1651] opened 2023-11-06 12:03 UTC
### Type

Cosmetic

### Tools used

RVX Manager

### Application

YouTube v18.40.34

### Bug description

Sponsorblock skip buttons on YouTube player gets overlapped when 2 or more segments are present.

### Steps to reproduce

1. Patch youtube with sponsorblock patch
2. Watch a video having multiple segments marked on same timeline.

### Relevant log output

```shell
N/A
```

### Screenshots or videos

![Screenshot_2023-11-06-17-29-36-456_app rvx android youtube-edit](https://github.com/inotia00/ReVanced_Extended/assets/107706560/2c3326aa-be27-4434-8434-7ca5a60695da)

### Solution

Seperate multiple skip buttons on top of another

### Additional context

Using Xiaomi 11T pro

### Device Environment

Android 13 MIUI 14.0.4

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment] 2023-11-06 12:08
please attach video url

**Comment by Rairof** [comment] 2023-11-06 12:10
https://github.com/inotia00/ReVanced_Extended/issues/1651#issuecomment-1794681883
https://youtu.be/FCR1i5oj8bk?si=Ev1_UbK4P6sBrx0I

**Comment by Rairof** [comment] 2023-11-06 12:58
Oh okay. I can provide the .json of my settings if needed.

**Comment by anddea** [comment] 2023-11-08 18:34
I can't reproduce this issue. Because there's no highlight segment for me in that video.

This problem occurs if highlight segment is enabled in Sponsorblock settings, and it shows skip to highlight and then overlaps it with skip any other segment when the seekbar reaches that segment. 

I'm not on my computer to take a closer look but it seems to do with the same margin and aligning for sponsor and highlight buttons. For example, check difference on line 9 in these files, I think copying from default to outline (only line 9) will fix the issue:

Default
https://github.com/inotia00/revanced-patches/blob/revanced-extended/src/main/resources/youtube/sponsorblock/default/layout/inline_sponsor_overlay.XML

Outline 
https://github.com/inotia00/revanced-patches/blob/revanced-extended/src/main/resources/youtube/sponsorblock/outline/layout/inline_sponsor_overlay.xml

and maybe some other corresponding files as well. If what I said doesn't work, then I will take a look when I'm free but otherwise default or outline icons shouldn't matter, only layout.

**Comment by inotia00** [comment] 2023-11-11 15:29
fixed in [revanced-patches-v2.196.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.196.1)

**Closed by inotia00** 2023-11-11 15:29 UTC
Labels: bug
