### ISSUE TITLE
feat(patch): 'add video to playlist' on YouTube Kids videos

### ISSUE THREAD

**Issue by hi-im-karma** [inotia00/ReVanced_Extended#39] opened 2022-12-24 17:26 UTC
YouTube Kids videos have that annoying infobar suggesting to open the YT Kids app. Please remove the infobar altogether as its taking up unneccesary space.

![Screenshot_20221224-180235888 (1)](https://user-images.githubusercontent.com/73917917/209446005-09e291a6-7d5f-41da-a5b7-fb4c76f4e439.jpg)

Also adding such a video to a playlist is blocked with the playlist button. Please release this block and make it possible to add such videos to a playlist.

![Screenshot_20221224-181550250 (1)](https://user-images.githubusercontent.com/73917917/209446009-c12bbdcb-ee74-4ad4-8616-31de152afa68.jpg)

**Comment by inotia00** [comment] 2022-12-24 17:30
Can you attach the video url of the screenshot?

**Comment by Eiskrem** [comment] 2022-12-24 17:35
> Can you attach the video url of the screenshot?

Sure. https://youtu.be/6FUP6fCNGrI
Its the same thing with any video uploaded as "YouTube Kids". You can test any  YouTube Kids video. 

The infobar and that dumb restriction needs to be 
removed. 
Currently the only way around it is by going to history and tapping the 3 dots to use "add video to playlist'"....

**Comment by venkat2305** [comment] 2022-12-24 18:17
Are you on the latest patches ?

**Comment by Eiskrem** [comment] 2022-12-24 18:20
> Are you on the latest patches ? 

Uhm yes latest 17.49.37
This has nothing to do with app version.

**Comment by venkat2305** [comment] 2022-12-24 18:30
![Screenshot_2022-12-24-23-59-21-057_app.revanced.android.youtube.jpg](https://user-images.githubusercontent.com/55329452/209447594-184c1d34-30b4-4665-a0ce-9c2db42528be.jpg)

![Screenshot_2022-12-24-23-59-18-053_app.revanced.android.youtube.jpg](https://user-images.githubusercontent.com/55329452/209447596-889a91c6-41cc-45a5-97a6-5c032541f5e7.jpg)

**Comment by Eiskrem** [comment] 2022-12-24 18:34
OK you don't seem to have the Kids infobar in the new layout. I don't know if the infobar is removed by Inotia in new layout, but it needs to be removed from old layout aswell.
The new layout still didn't hit my app.

But you still can't use the playlist button with YT Kids videos. I can see that since it's greyed out.

**Comment by inotia00** [comment] 2022-12-24 18:38
Same.. I also don't see the YouTube Kids banner (old layout/new layout)

**Comment by Eiskrem** [comment] 2022-12-24 18:41
> Same.. I also don't see the YouTube Kids banner (old layout/new layout)

🤔 Can you show me a screenshot with my layout? 
Do I need to enable a certain Rvx toggle to remove the banner, or what do I need to do?

/But you also can't use the playlist button with YT Kids videos is that correct?

**Comment by Eiskrem** [comment] 2022-12-24 18:51
@inotia00 Found out. I had the second ADS toggle disabled thinking i wouldn't need it as YouTube Premium user. Now enabled and the banner is gone.

![Screenshot_20221224-195009808 (1)](https://user-images.githubusercontent.com/73917917/209448130-e1b3d64d-7f78-406d-a414-9aa04690c394.jpg)

Now all thats left is being able to use the playlist button with YouTube Kids videos.

**Comment by venkat2305** [comment] 2022-12-24 19:44
The playlist button is disabled in the new layout as well.

**Comment by inotia00** [comment] 2022-12-24 19:53
Glad you found the cause
Since the question appears to be resolved, I will close this issue.

**Comment by Eiskrem** [comment] 2022-12-24 19:56
> Glad you found the cause
> Since the question appears to be resolved, I will close this issue.

Thank you, but no it wasn't simply about the banner, but the fact that the playlist button is blocked with YouTube Kids videos. It doesn't work as you might've seen for yourself? That's why I changed the topic title :)

Kindly asking you to reopen the issue, or should  I open a new one about the playlist button not working with YouTube Kids videos?

**Comment by inotia00** [comment] 2022-12-24 21:12
If you changed the title, this is a valid issue
I will reopen this issue

**Comment by inotia00** [comment] 2023-09-06 21:52
In case of YouTube, I have no plans to add new features.

**Closed by inotia00** 2023-09-06 21:52 UTC
Labels: patch-request
