### ISSUE TITLE
bug(YouTube): in 18.33.40 on tablet i see space between feed category bar and videos

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1467] opened 2023-10-02 20:58 UTC
### Type

Error at runtime

### Tools used

rvx-builder

### Application

YouTube 18.33.40

### Bug description

Error occurs only 18.33.40, now i rolled back to 18.32.39 and all fine. On tablet i see much space between feed category bar and videos.
How all on 18.22.37 ~ 18.32.39
![Screenshot_20231002_193220_ReVanced Extended](https://github.com/inotia00/ReVanced_Extended/assets/110785596/0361092e-c8c6-43ba-bcfd-4727c8747893)
And how on 18.33.40
![Screenshot_20231002_193216_ReVanced Extended](https://github.com/inotia00/ReVanced_Extended/assets/110785596/96bcf8eb-797b-4469-ab3d-5d643aa52ae2)
And unpatched YT 18.33.40 has no this problem.
In RVX error not need some extra settings to reproduce, you can just patch 18.33.40 with recommended patches and not change the settings, error is here

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment] 2023-10-02 21:24
did you checked unpatched YouTube?

**Comment by girshcatt** [comment] 2023-10-02 21:57
> I think it would be good to specify which patch is causing the error - since I don't have device that can reproduce issue

Oh, i think i will lose so much time to find what patch cause it😅 But i will try to do it tomorrow

**Comment by inotia00** [comment] 2023-10-02 22:02
This is a list of suspect patches

- Hide general ads
- Hide layout component
- Hide suggestion shelf
- Hide mix playlists

Exclude all these patches and see if the issue reproduces

**Comment by girshcatt** [comment] 2023-10-02 23:17
I excluded these four patches that you said and issue not reproduced, all work as normal

**Comment by inotia00** [comment] 2023-10-03 05:13
If so, one of these four patches may be the cause

If possible, please find which of these four patches is causing the issue - for anyone who visits this issues in the future

**Comment by girshcatt** [comment] 2023-10-03 09:04
Damn, now i cant reproduce it anyway, i even have exported settings from the time when this issue appeared, i patched yt the same way and imported settings, but all normal. I dont know how this bug not appear now, yesterday i reinstalled all many times, but i remained.
I think you can close the issue, if bug will appear in future i will reopen issue.

But i have some interesting info, i tried to patch with `microg-support` `settings` `hide-suggestions-shelf` and it crash immediately, i tried repatch, i tried on my phone. If you will patch `microg-support` `settings` all will be fine, but if you add `hide-suggestions-shelf` all start to crash immediately.
I even tried to install 18.33.40 patched with `microg-support` `settings` and update with apk patched `microg-support` `settings` `hide-suggestions-shelf` and the same problem. When i tried to reproduce one issue i found another 😅

**Comment by inotia00** [comment] 2023-10-03 09:41
I think other bugs you found in the process you are trying to reproduce are more important

Like the issue that follows, this is a fairly difficult bug to notice https://github.com/inotia00/ReVanced_Extended/issues/1458

Ideally, you should open a separate issue for new bugs, but you don't have to

It will be fixed in the next release

Anyway, I don't know why no longer reproducable the original issue, but since can't reproducable it anymore, I'll close the issue

**Closed by inotia00** 2023-10-03 09:41 UTC
Labels: bug

**Comment by girshcatt** [comment] 2023-10-08 15:43
I dont know need this issue to be reopened or no, but minute ago i saw this problem on phone, it disappeared after reopen. Well, now we know that this can appear not only on tablets, and not only in 18.33.40, because now i use 18.32.39
![Screenshot_2023-10-08-18-37-59-673_app rvx android youtube](https://github.com/inotia00/ReVanced_Extended/assets/110785596/3ad9dc97-0412-4a7d-a28a-0f2f15ebd594)

**Comment by girshcatt** [comment] 2023-10-08 15:44
All that stop me from asking to reopen issue is that i dont know how it can be reproduced(

**Comment by inotia00** [comment] 2023-10-08 15:46
Rather than a bug, it would be more accurate to think of it as YouTube's new A/B test

To avoid this A/B testing, just patch to YouTube v18.27.36 or earlier
Less A/B testing is available on YouTube v18.27.36 or earlier
