### ISSUE TITLE
bug: Double Tap to seek (Backwards) not working.

### ISSUE THREAD

**Issue by Abhinav1217** [inotia00/ReVanced_Extended#91] opened 2023-01-02 17:17 UTC
### Type

Other

### Application

Youtube 17.49.37 
Patch: 2.151.0
Builder: rvx-builder 3.8.0 

Created a patch on linux machine and transferred the apk to phone using USB.

### Bug description

This was happening in last patched version also. 

Basically, double tap to move forward is working, but double tap to move backward is not working. If I move forward, then immediately tap backward, then it does register the behavior but not when tapping normally. 

Also swipe up for showing playlist is also not working properly. Earlier, when you swipe up around the center, volume up would toggle, and if you swipe up from bottom, the playlist screen would show up, but now only volume is working.

### Steps to reproduce

1. Play a video,
2. fullscreen the video.
3. double tap to seek backward

### Relevant log output

```shell
?
```

### Screenshots or videos

https://user-images.githubusercontent.com/740584/210262402-dafa23cc-10b0-4006-9033-39734b6fd120.mp4

### Additional context

This was working in the build I made in September. After that, I made a build around 16th December, in which I encountered this error first time,  and then I made another updated build half an hour ago where I noticed this issue still exists. Therefore, something must have broken between September and December. 

### Device Environment

Android 12, 

OxygenOS 12

Oneplus 7 pro,

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment] 2023-01-02 17:20
![ReVanced](https://user-images.githubusercontent.com/108592928/210262436-9288b76c-8d17-4a5e-b629-a185bec43dfa.png)

Do you turn off this option?

**Comment by Abhinav1217** [comment] 2023-01-02 17:20
Is video not visible? Is there another way to send the screenrecording.

**Comment by inotia00** [comment] 2023-01-02 17:23
I checked the attached screen record

If `Enable always swipe gesture`(Experimental Flags) is on, there is a bug in the double tap to seek (same as attached video)

**Comment by Abhinav1217** [comment] 2023-01-02 17:23
Yes, This option was off.

**Comment by Abhinav1217** [comment] 2023-01-02 17:26
Ok, I just noticed, Even though I am building using rvx builder, I am generating revanced apk, not extended apk.

**Comment by Abhinav1217** [comment] 2023-01-02 17:33
Are the instructions for rvx-builder changed? What should I configure here for getting revanced extended patches?

![Screenshot from 2023-01-02 23-01-47](https://user-images.githubusercontent.com/740584/210263412-50c94396-c336-4110-a104-c0a351d02e11.png)

**Comment by inotia00** [comment] 2023-01-02 17:36
Is it correct that you downloaded it from the rvx-builder release page?
https://github.com/inotia00/rvx-builder/releases/tag/v3.8.0

[rvx-builder-win.exe](https://github.com/inotia00/rvx-builder/releases/download/v3.8.0/rvx-builder-win.exe)
[rvx-builder-macos](https://github.com/inotia00/rvx-builder/releases/download/v3.8.0/rvx-builder-macos)
[rvx-builder-linux](https://github.com/inotia00/rvx-builder/releases/download/v3.8.0/rvx-builder-linux)

**Comment by Abhinav1217** [comment] 2023-01-02 17:48
Yes.

Double checked it.

The Binary I downloaded is rvx-builder-linux

```

abhinav@abhinav-sol ~/Project $ cd RVX/
abhinav@abhinav-sol ~/Project/RVX $ ls
rvx-builder-linux
abhinav@abhinav-sol ~/Project/RVX $ sha1sum rvx-builder-linux
5bbe44f409aec9fc3972306d253f44490a156b57  rvx-builder-linux
```

**Comment by Abhinav1217** [comment] 2023-01-02 17:54
Probably because of old cache in browser. I will make one in private browser mode. Clean cache should do the trick. Also I will uninstall the old apk from phone and install the new one instead of upgrading. 

About the actual Issue, I am sure that in the option was disabled. Because other than volume, I don't use any other swipe gesture, so I tend to disable them. (Also I prefer not to change anything marked as experimental)

**Comment by inotia00** [comment] 2023-01-02 17:58
It's weird.. Could you test it even when you change press to swipe to on?

**Comment by Abhinav1217** [comment] 2023-01-03 12:36
About the issue with rvx-builder, It was cache issue, I opened the localhost:8000 on a private window and it showed the inotia as source.

Maybe it has to do with the fact that before downloading the release binaries, I tried to build it myself using the instructions from developer.md.   FYI, on your readme, the link for developer.md still points to the upstream reisxd, not the one on your own repo.  so maybe I missed changing the URL and accidentally pulled from upstream. 

----------------------

About the actual Issue, If I disable Press-to-swipe haptic feedback, then it is not working with similar issue above.    
Upon enabling it, What now happens is that :
1. Double tapping while no overlay: Not working.
2. Double tapping with Overlay: Working. 

Note this is for "Backward" only, "Forward" is working regardless of state of overlay. 

Also it is only an issue on landscape full video mode, On portrait mode with video above the comments, everything is working as expected. I played with press-to-swipe settings too, but I could not notice any pattern from it, only from haptic feedback toggle. 

In my current swipe control settings, only "Enable Volume gesture" and "Enable press-to-swipe haptic feedback" is enabled.

**Comment by inotia00** [comment] 2023-01-03 15:07
Same issue even though `Enable always swipe gesture` option is OFF?

Because this answer is important in solving this issue

**Comment by Abhinav1217** [comment] 2023-01-04 10:35
> In my current swipe control settings, only "Enable Volume gesture" and "Enable press-to-swipe haptic feedback" is enabled.

Yes, `Enable always swipe gesture` option **is** OFF with above behavior. i.e double tapping is working only if overlay is on, and only for back tapping, no issues with front tapping. 

If I set it to ON, then back taping is not working at all, No effect on forward button. I can double tap to forward irrespective of state of overlay.

**Comment by inotia00** [comment] 2023-01-05 03:54
revanced-patches-v2.152.0
revanced-integrations-v0.91.2

Could you patch again in this environment and test if the issue is reproduced?

**Comment by jackblk** [comment] 2023-01-05 07:20
@inotia00 I have a similar isue on patch: 2.151.0, but only on forward seek (right side).

Settings:

* Left swipe (brightness) enabled
* Right swipe (volume) disabled

I will not be able to do forward seek by double tapping. However if I double tap backward first, then do the forward then it works.

Enable/Disable Enable Always Swipe Gesture doesn't fix the issue.

Just patched 2.152.1, everything works like expected now.

**Comment by inotia00** [comment] 2023-01-05 07:48
yeah.. I think it was caused by `Experimental Flags` that I added in the past (removed that setting in the latest release)

Anyway, I'm glad the issue has been resolved.
I will close the issue page if you try it for a few more days and the issue doesn't reproduce.

**Comment by Abhinav1217** [comment] 2023-01-06 10:18
@jackblk 

Nice observation. I just tried same on my device, 
- If I enable volume but disable brightness, Backwards is not working but forward is.
- If I disable volume but enable brightness, Backwards is working but forwards is not.
- If I disable/enable both volume and brightness, Both sides are showing issues (I think, didn't try long enough to figure out pattern, but when it works, it works, when it didn't, it didn't. )


I will build with updated patches again when I am back home from office, and let you know.

**Comment by inotia00** [comment] 2023-01-06 12:21
@Abhinav1217 
It is already a fix issue on the latest revanced-patches.

If the issue is still reproduced, the RVX client you are using would have been outdated.

Progress the patch again

latest support stable version
: YT v17.49.37
latest support beta version
: TY V18.01.32

**Closed** 2023-01-06 14:38 UTC
Labels: bug
