### ISSUE TITLE
bug: Change version code patch applied but still an update showing in play store

### ISSUE THREAD

**Issue by iswac** [inotia00/ReVanced_Extended#2230] opened 2024-07-07 17:01 UTC
### Type

Other

### Tools used

RVX Manager

### Application

Reddit  2024.17.0

### Bug description

I tried patch reddit with `Change version code` patch but still play store showing an update for reddit. I used only default patches with Change version code patch and patching ended with successfully. I didn't understand where I'm doing wrong.
![Screenshot_20240707_194627_RVX Manager](https://github.com/inotia00/ReVanced_Extended/assets/157625006/388b258f-a021-40e5-a53b-8269546c5e98)
![Screenshot_20240707_194558_Google Play Store](https://github.com/inotia00/ReVanced_Extended/assets/157625006/d3eb73d4-27f1-473f-85e8-696daaf5b24c)

### Device Environment

A13

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment] 2024-07-07 17:16
Did you select root install?

**Comment by iswac** [comment] 2024-07-07 17:39
> Did you select root install?

I used both RVX Manager and Revancify from termux and yes root was selected.

**Comment by inotia00** [comment] 2024-07-07 17:44
Due to limitations in ReVanced CLI and ReVanced Manager, the `Change version code` patch does not work in root environment

To be precise, the actual version code is changed, but when installed in a root environment, PlayStore recognizes the version code of the original app

Since it is not a bug on the patch side, closing the issue

**Closed by inotia00** 2024-07-07 17:44 UTC
Labels: Bug report

**Comment by iswac** [comment] 2024-07-07 17:57
So what should i do now? Patch apk on non-root environment or something?

**Comment by inotia00** [comment] 2024-07-07 18:10
Follow the non-root installation instructions in the [documentation](https://github.com/inotia00/revanced-documentation/blob/main/docs/rvx-manager.md)
