### ISSUE TITLE
bug (YouTube): buffering pre video without buffer issues

### ISSUE THREAD

**Issue by ayushTNM** [inotia00/ReVanced_Extended#2026] opened 2024-05-15 21:26 UTC
### Type

Error while patching

### Tools used

RVX Manager

### Application

YouTube 19.16.39, patches 4.8.0-dev. 6

### Bug description

If device is not affected by buffering issues, in some cases, the video and suggested videos screen loads for quite some time before it plays

Rvx 4.8.0-dev. 6:

https://github.com/inotia00/ReVanced_Extended/assets/78740080/f4777b13-3a34-4c21-af24-38cd6c8a7b9f

Pre rvx 4.7.1 (anddea 2.224.0):

https://github.com/inotia00/ReVanced_Extended/assets/78740080/1cf3e7d5-9729-41c7-ac62-8a45bd259150

(Recording made after rvx recording)

### Additional context

Spoof format data and spoof test client off.

### Device Environment

Android 14, pixel 7

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment] 2024-05-15 21:31
https://github.com/inotia00/ReVanced_Extended/issues/1954

**Comment by ayushTNM** [comment] 2024-05-15 21:44
This is a bug regarding devices not affected by buffering issues...

**Comment by ayushTNM** [comment] 2024-05-15 21:58
The videos still play, they just load longer at the start compared to rvx patched using.a version before 4.7.1.

**Comment by inotia00** [comment] 2024-05-15 22:06
It does not reproduce on my side
Exclude patches one by one and guess which patch is causing the issue

**Comment by ayushTNM** [comment] 2024-05-16 15:07
Before i do. here is a log during the issue. Lmk if that helps. otherwise I'll test by removing patches 1 by 1.
[log.txt](https://github.com/inotia00/ReVanced_Extended/files/15337210/log.txt)

**Comment by ayushTNM** [comment] 2024-05-18 10:04
Is the issue prevalent from the log?

**Comment by inotia00** [comment] 2024-05-18 10:40
I didn't find anything special in the log

Exclude patches one by one and report back

**Comment by ayushTNM** [comment] 2024-05-18 18:42
The issue is caused by replace software av1 codec setting in video playback patch

**Comment by inotia00** [comment] 2024-05-19 00:18
`Replace software av1 codec` setting may cause other side effects due to changes on the server side at any time.
Therefore, this setting has been designated as an `Experimental Flags`.

Thank you for defining the cause of the issue. Closing the issue.

**Closed by inotia00** 2024-05-19 00:18 UTC
Labels: Bug report, Waiting on author
