### ISSUE TITLE
bug(YouTube/Spoof player parameters): thumbnail preview is not updated

### ISSUE THREAD

**Issue by DGlmMortal** [inotia00/ReVanced_Extended#1821] opened 2023-12-13 14:37 UTC
### Type

Other

### Tools used

rvx-builder

### Application

RV𝕏 - [ Non-Rooted Builds ]
V18.46.43 

### Bug description

Bro Seekbar preview is not working properly
Means sometimes it shows completely black, and sometimes another video scene shows another video Seekbar.
![IMG_20231213_195845_757](https://github.com/inotia00/ReVanced_Extended/assets/130741447/10a60b58-4560-42dc-911d-9d58d730a381)

### Error logs

```shell
I don't have logs
```

### Solution

Please Solve this issue 🙏🏼

### Additional context

And thanks for the amazing effort for us♥️

### Device Environment

Android -12
MIUI-13.0.2

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by KobeW50** [comment] 2023-12-13 15:22
This was fixed in [patches v2.203.2](https://github.com/inotia00/revanced-patches/releases/tag/v2.203.2).

Since support for 18.46.43 was dropped, you will not be able to install the new YT RVX as an update to your existing app since it will be a lower version. So you may want to export your settings from your current installation into the new one.

**Comment by jhon1282** [comment] 2023-12-13 16:38
This is a problem that can also be found in 18.45.43.
Not always but randomly an empty thumbnail is shown, if you move the cursor sometimes a preview is shown but not of the exact point of the video, or the same thumbnail remains fixed on a certain frame.Not easy to reproduce because it is not repeated constantly but randomly.
Usually moving the cursor back and forth normalizes it.

**Comment by KobeW50** [comment] 2023-12-13 16:41
> This is a problem that can also be found in 18.45.43.

What patches version? You can check by going to Settings > ReVanced Extended > Miscellaneous > Patches information

**Comment by jhon1282** [comment] 2023-12-13 16:53
> > This is a problem that can also be found in 18.45.43.
> 
> What patches version? You can check by going to Settings > ReVanced Extended > Miscellaneous > Patches information

Patch v2.204.1
![Screenshot_2023-12-13-17-51-43-904_app rvx android youtube](https://github.com/inotia00/ReVanced_Extended/assets/125223735/7537f866-0bde-45ef-9b1e-2eedb63a2687)

**Comment by inotia00** [comment] 2023-12-13 18:32
reflected in [revanced-patches-v2.205.1](https://github.com/inotia00/revanced-patches/releases)

**Closed by inotia00** 2023-12-13 18:32 UTC
Labels: Bug report
