### ISSUE TITLE
bug(spoof-player-parameter): channel watermark is not shown even if the option is enabled.

### ISSUE THREAD

**Issue by jhon1282** [inotia00/ReVanced_Extended#1045] opened 2023-07-05 18:54 UTC
### Type

Other

### Tools used

Revancify

### Application

Youtube 18. 24.37

### Bug description

Channel watermark is not shown even if the option is enabled.

### Steps to reproduce

Disable hide watermarks.
Open any video.
The watermark is not shown.

### Relevant log output

```shell
Na
```

### Screenshots or videos

![Screenshot_2023-07-05-20-52-22-320_app rvx android youtube](https://github.com/inotia00/ReVanced_Extended/assets/125223735/a4f6cc92-4324-4c1b-8c5f-0288c6e37680)

No watermark 

### Additional context

Device Redmi note 10 pro 

### Device Environment

Android 13 miui 14 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by jhon1282** [comment] 2023-07-05 19:10
Same video in youtube stock
![Screenshot_2023-07-05-21-06-44-026_app revanced android youtube](https://github.com/inotia00/ReVanced_Extended/assets/125223735/17eaf9f7-b5c6-424b-93da-4a90300ad151)

**Comment by inotia00** [comment] 2023-07-06 06:02
Please re-patch to the version released today

YouTube v18.25.39
revanced-patches-v2.181.4

Issue is not reproducible in this environment

**Comment by jhon1282** [comment] 2023-07-06 09:40
> 

Thank you so much for your availability but unfortunately the problem persists. Watermark is not shown.

**Comment by inotia00** [comment] 2023-07-06 09:53
I think.. it might be an A/B test.

**Comment by inotia00** [comment] 2023-07-06 09:54
If I exclude the channel watermark patch, how is it displayed?

**Comment by jhon1282** [comment] 2023-07-06 10:01
> If I exclude the channel watermark patch, how is it displayed?

I tried to exclude the patch, but the problem persists, I tried the original YouTube itself version itself and the watermark is shown, if it were an A/B test I think it should also be on this.

**Comment by S23u512** [comment] 2023-07-06 10:41
I confirm this bug.

YouTube 18.25.39
Patches 2.181.4

**Comment by jhon1282** [comment] 2023-07-06 10:41
The thing is curious, now I have tried original revanced and the watermark is shown or not depending on the settings, it works as it should, only on Revanced_Extended it does not work 🤔

**Comment by jhon1282** [comment] 2023-07-06 14:26
![Screenshot_2023-07-06-16-17-51-090_app rvx android youtube](https://github.com/inotia00/ReVanced_Extended/assets/125223735/31405f79-5545-48c0-8f95-27ff88bc0216)
The problem is due to these settings, with the first activated it doesn't show watermark, if active the second watermark is shown but I have other problems... No thumbnail etcc..

**Comment by inotia00** [comment] 2023-07-07 04:22
thanks for letting me know
yeah this is a side effect of spoofing player parameter

**Comment by inotia00** [comment] 2023-08-04 23:58
since it is no longer spoofing with shorts player parameters in latest patches, closing the issue

**Closed by inotia00** 2023-08-04 23:58 UTC
Labels: bug
