### ISSUE TITLE
bug: Copy link button Timestamp doesn't work properly 

### ISSUE THREAD

**Issue by giwrgosmant** [inotia00/ReVanced_Extended#62] opened 2022-12-28 04:52 UTC
### Type

Other

### Application

YT version 17.49.37
ReVanced Manager v0.52
Builded day: today
Build type: Non Root

### Bug description

The copy link button timestamp doesn't work properly. It always show "0" time and start from the begging of a video like the normal copy link to video button.
(It used to work fine before the recent update)
I tried with 2 devices.

### Steps to reproduce

1. Open ReVanced Extended
2. Enable the option for copy link button timestamp at Overlay Settings
3. Restart the app
4. Go to video, move forward the time a bit and press the button.
5. You will it shows "0" time when you copy, and when you paste the link the video starts from the begging.

### Relevant log output

```shell
-
```

### Screenshots or videos

![Screenshot_20221228-064951_YouTube](https://user-images.githubusercontent.com/51835189/209759346-ab3fe96b-aaad-425d-8099-567058807a0e.png)

### Device Environment

Android 13, crDroid ROM, non root version

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment] 2022-12-28 05:44
Please add version of revanced-patches and revanced-integrations

**Comment by giwrgosmant** [comment] 2022-12-28 06:14
> Please add version of revanced-patches and revanced-integrations

![Screenshot_20221228-081354_ReVanced Extended.png](https://user-images.githubusercontent.com/51835189/209766800-0503a5b1-4b24-4d48-a310-f91ff5dede1f.png)

**Comment by inotia00** [comment] 2022-12-28 07:28
Fortunately, this is a bug reproduced in my device
I will mention it if it is fixed

**Comment by giwrgosmant** [comment] 2022-12-28 07:33
> Fortunately, this is a bug reproduced in my device I will mention it if it is fixed

Thank you.

I don't want to create another issue, so I will do a quick question here and if you want reply:
It's on your plans to include import/export revanced settings?
Also I maintain [this xda thread](https://forum.xda-developers.com/t/revanced-revanced-extended-guides-useful-links.4523967/), is there any group for Extended (telegram or discord or something) which people can contact beside github, so I can add it?

Thanks again for your work.

**Comment by inotia00** [comment] 2022-12-28 08:15
Unfortunately, I have already tried for about a month to implement a function for setting import/export, but without success.

My Telegram channel is..

[@revanced_extended](https://t.me/revanced_extended)
: Main channel, mainly announcements are uploaded

[@revanced_extended_repo](https://t.me/revanced_extended_repo)
: Whenever a new github release occurs, the github notification bot notifies you of the news in real time.

**Comment by giwrgosmant** [comment] 2022-12-28 08:52
> Unfortunately, I have already tried for about a month to implement a function for setting import/export, but without success.
> 
> My Telegram channel is..
> 
> [@revanced_extended](https://t.me/revanced_extended) : Main channel, mainly announcements are uploaded
> 
> [@revanced_extended_repo](https://t.me/revanced_extended_repo) : Whenever a new github release occurs, the github notification bot notifies you of the news in real time.

Thank you, I've updated my thread including your channels.
Thanks for your work, Keep it up 👍

**Comment by giwrgosmant** [comment] 2023-01-01 06:40
Hello @inotia00, Happy Nea Year!
I just want to inform you (if you are not already aware) regarding this bug, Official ReVanced on the latest release patches added the option to copy link button and timestamp etc. It's working properly.
Take a [here](https://github.com/revanced/revanced-patches/pull/1402) and [here](https://github.com/revanced/revanced-patches/commit/bf982e8d7765c2a89a5475b6db8b203a3ac4ddf9) if you like.

**Comment by inotia00** [comment] 2023-01-01 12:08
my confirmation was delayed
This bug was already fixed in a commit a few days ago, and the release is being delayed because it couldn't reflect some additional fixes

**Comment by inotia00** [comment] 2023-01-01 16:28
fixed in v2.151.0 releases
try to test it

**Comment by giwrgosmant** [comment] 2023-01-01 16:58
> fixed in v2.151.0 releases try to test it

Already tested it. Working fine 👍
Thanks!

**Comment by inotia00** [comment] 2023-01-01 17:06
👍

**Closed by inotia00** 2023-01-01 17:06 UTC
Labels: bug
