### ISSUE TITLE
question:Not all ads are blocked? 

### ISSUE THREAD

**Issue by jhon1282** [inotia00/ReVanced_Extended#741] opened 2023-04-15 04:59 UTC
### Application

YouTube

### Description

What are these ads? They appeared today, it seems something new that is not blocked? 

![Screenshot_2023-04-15-06-30-59-501_app rvx android youtube](https://user-images.githubusercontent.com/125223735/232183777-829130ad-697e-44da-8797-b1c239f22ca9.jpg)
![Screenshot_2023-04-15-06-32-58-593_app rvx android youtube](https://user-images.githubusercontent.com/125223735/232183851-d6b4514a-ffc2-4703-8e1e-6a1ce56561e1.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment] 2023-04-15 09:35
Can't reproduce on my side

The types of advertisements displayed differ depending on the user's region/account.

If this is a new type of ad, I need access to your account to debug this ad

**Comment by jhon1282** [comment] 2023-04-15 11:24
I'm not logged in with any account right now, my location is Italy and I can't always reproduce it either.
It's really strange, by the way another new section has appeared as in screen

![IMG_20230415_123707](https://user-images.githubusercontent.com/125223735/232211378-11f6e794-05ef-4bcc-ac37-07828b7075a3.jpg)

**Comment by inotia00** [comment] 2023-04-15 12:56
What is the version you use?

**Comment by jhon1282** [comment] 2023-04-15 13:04
ReVanced Extended 18.14.40 patches 2.168.36.
Revancify used

**Comment by inotia00** [comment] 2023-04-15 21:01
Probably, it was fixed in revanced-integrations-v0.102.0
Please patch again with the latest resources and let me know the results.

**Comment by jhon1282** [comment] 2023-04-15 21:46
Ok I updated integrations, ads seem to be gone, thanks a lot for your work.
The new, "Unexplored Channels" section remained, probably a new layout or A/B test.
This is no problem.

**Comment by inotia00** [comment] 2023-04-15 22:01
yep it seems to another A/B tests

**Closed by inotia00** 2023-04-15 22:01 UTC
Labels: question
